### ISSUE TITLE
Suggestion: changing zip target to dmg

### ISSUE THREAD

**Issue by Jackymancs4** [will-stone/browserosaurus#10]
This way is faster to install/substitute new versions of the app, and it's also an habit i saw for most of  mac apps. Certainly an habit of mine xD

It's also a good excuse to rollout a lighter 1.0.5 release ( #9 )

**Comment by will-stone** [comment]
I've not had any experience of making dmg's. I simply use the built-in tools of electron-forge. I will look into making a lighter version soon (probably tonight, maybe tomorrow). I also want to look into adding an updater at some point. I don't really see any issue with unzip > drag to Applications folder > confirm overwrite, therefore I'll close this. If it's easy to add and you know how, please feel free to send PR. Thanks.
