### ISSUE TITLE
Browserosaurus doesn't show in menubar or dock when opened.

### ISSUE THREAD

**Issue by Ornataweaver** [will-stone/browserosaurus#11]
So how can I open it's preferences?
Or for closing it, I need to use "Activity Monitor.app".
And there can be an autoupdate feature in preferences, which is another issue to be opened. Should I?

**Comment by will-stone** [comment]
Sounds like a bug.

- What version are you using?
- What version of MacOS are you using?
- How did you open Browserosaurus? Click a link, or directly?
- Had you closed the previous version of the app before upgrading? (if that's what you did)
- Does it work (show in menubar) after closing it in Activity Monitor and then reopening it?

Don't bother opening an issue for autoupdate unless you plan to research and add it yourself. I know I'd like to add it but don't have time to do it at the moment. I'm happy to do bug fixes and add browsers but that's about it at the moment. Just setting expectations 👍

**Comment by Ornataweaver** [comment]
- Browserosaurus Version 1.0.4
- macOS Sierra Version 10.12.6 (16G1036)
- I opened it by right clicking on the app, choosing open
- Yes I did close it via "Activity Monitor"
- No, I closed and reopened it, yet nothing in the menubar. I'm going to restart my computer. Maybe that works.

I don't know how to add autoupdate feature. If I knew I would send you a pull request.
Thank you for your time and the time you save for us.

**Comment by Ornataweaver** [comment]
Restarting apple's system didn't work. (I wanted to say my system, then I realized it's not mine)

**Comment by will-stone** [comment]
Hmmm... very strange, I'm using the same setup. Just to confirm, it's not because you've got so much in your menubar that it's fallen off? Try opening something with little amount of menu items like TextEdit to give you more space.

Otherwise, can you downgrade to v1.0.3 and see if that works?

**Comment by Ornataweaver** [comment]
Both v1.03 and v1.0.4 show menubar on "macOS High Sierra Version 10.13.1 (17B48)"
Maybe it's because I fuck around with my system too much, without always knowing what I'm doing. 👯‍♂️

**Comment by will-stone** [comment]
Yeah I'm not sure how much more I can help. Try deleting Browserosaurus using https://freemacsoft.net/appcleaner/ then restart, then install it again, then start it from Launchpad (not from a link) and wait for it to finish scanning for browsers (about 10-15seconds) and see if that works. Otherwise I'm out of ideas.

**Comment by Ornataweaver** [comment]
I just realized it's not working at all on my computer.

**Comment by will-stone** [comment]
- Check Settings > General > Default Web Browser, is Browserosaurus set as default?
- Is it running in Activity when you run it from Launchpad?
- Does it need allowing to run from Settings > Security & Privacy > General?

**Comment by Ornataweaver** [comment]
Actually using "AppCleaner.app" and downloading it again worked. It is now open in the menubar, and perfectly opens links as it is supposed to.
I hope I have not wasted your time.

**Comment by Ornataweaver** [comment]
Maybe after I put it in the "/Applications/" folder, it worked out.
But now I have put it in my custom Applications folder and it's working out fine.
Maybe the first time it must be opened in the "/Applications/" subdirectories.

**Comment by will-stone** [comment]
Ok, glad you got it working.
