### ISSUE TITLE
Support automatic selection based on rules (per-app; per-URL)

### ISSUE THREAD

**Issue by stewartadam** [will-stone/browserosaurus#113]
Browsersaurus is awesome! I would like to request adding support for automatically launching a browser based on customizable rules or criteria. I think to start, the most useful would be:
1. Per-app: launch a specific browser based on the app the link was clicked in
2. Per-URL: launch a specific browser if a pattern matches the URL

**Comment by will-stone** [comment]
Hi. Thanks for your suggestion. However, this is out of scope for the project. Please see #91 #53 #32 

Essentially, I would like to keep the feature set for the project small; only augmenting current features where sensible. I'm a great believer in muscle-memory and I find knowing the picker will open _every time_ is far more powerful than tinkering with rules.

I suggest looking into something like [Choosy](https://www.choosyosx.com/).
