### ISSUE TITLE
[Poll] Should favourite browser be a larger or standard size button?

### ISSUE THREAD

**Issue by will-stone** [will-stone/browserosaurus#115]
Large (current):
![image](https://user-images.githubusercontent.com/654103/61596728-2e1a5a80-abff-11e9-86be-e744081d2713.png)

Standard size. Favourite still moves to nearest to mouse, and is assigned the "enter" key:
![image](https://user-images.githubusercontent.com/654103/61596705-e72c6500-abfe-11e9-8f39-97887b4f67bd.png)

Click your preference:

[![](https://api.gh-polls.com/poll/01DGB3ET815CFDZRETY3VC8KRM/Large%20Favourite)](https://api.gh-polls.com/poll/01DGB3ET815CFDZRETY3VC8KRM/Large%20Favourite/vote)
[![](https://api.gh-polls.com/poll/01DGB3ET815CFDZRETY3VC8KRM/Standard-size%20Favourite)](https://api.gh-polls.com/poll/01DGB3ET815CFDZRETY3VC8KRM/Standard-size%20Favourite/vote)

**Comment by bendem** [comment]
I like it better with a larger size, but that's because the widget is perfectly sized (odd number of items):
![Screenshot 2019-07-22 at 09 30 59](https://user-images.githubusercontent.com/2681677/61614236-82572600-ac63-11e9-8027-65749d5aa380.png)

I wouldn't like it at all if it looked like your first screenshot.

**Comment by will-stone** [comment]
@bendem yeah, that's why I started this poll, because that first screenshot is what it looks like to for me, as I have to test so many browsers for this app 😆 I'm thinking I prefer the standard-size favourite but I could set it so that if the grid does not divide nicely by 3, that it shows some placeholders:

![b](https://user-images.githubusercontent.com/654103/61615164-3a350500-ac5d-11e9-9f5b-6ee0bb9990b6.png)

Then re-jig the maths so it does this (`b` = browser, `c` = copy to clipboard, `.` = placeholder):

1 x browser (only Safari installed):
```
b c
```

2 x browsers:
```
b b c
```

3 x browsers:
```
b b
b c
```

4 x browsers:
```
b b b
b c .
```

5 x browsers:
```
b b b
b b c
```

6 x browsers:
```
b b b b
b b c .
```

7 x browsers:
```
b b b b
b b b c
```

8 x browsers:
```
b b b
b b b
b b c
```

9 x browsers:
```
b b b b b
b b b b c
```

Where if the number of browsers is above 3, and if the number of browsers + 1 is prime, it will have a placeholder dot, otherwise will keep adding rows or columns to fit all in.

**Comment by evanwarner** [comment]
I think about it like this:
- If I'm launching via keyboard, the button size doesn't make a difference.
- If I'm launching my favorite browser via my mouse, the button size doesn't make a difference (it's still the first pixels I'll hit).
- If I'm launching a non-favorite browser via my mouse, I have to move farther to pass over a large favorite.

That last point is the only one that has an effect on my interaction, so I voted regular size button. Also, I like the dynamic grid idea you posted above.

**Comment by nmcc1212** [comment]
my idea, make enter primary then num keys for the rest e.g 
safari = enter
chrome = 1
firefox = 2
edge dev = 3 
opera = 4
clipboard = space key

**Comment by will-stone** [comment]
Hi @nmcc1212. I'm a big fan of _learnt_ behaviour. Unfortunately your suggestion would break this. For example, If you were to install or remove a browser, all the number hotkeys would shift around. Whereas knowing that you can hit "f" each time to open Firefox, means you can use touch typing / muscle memory to open the browser.

**Comment by nmcc1212** [comment]
how about making it toggleable in the menu bar?

**Comment by will-stone** [comment]
@nmcc1212 Here's a mini rant about settings I wrote the other day: https://github.com/will-stone/browserosaurus/issues/119#issuecomment-533453728 I think if you are using a browser enough, then set it as your favourite, otherwise I think only supporting prod channels with hotkeys suffices. More than happy to review a PR if you'd like to take a look, though. For now I'll mark this as off topic. Thanks for the suggestions, always to happy to hear more 😄

**Comment by will-stone** [comment]
Okay, poll closed, from v7 you will always have a favourite (which defaults to Safari). All browsers are the same size, but the favourite is nearest the mouse.
