### ISSUE TITLE
[Feature Request] Support for Qutebrowser

### ISSUE THREAD

**Issue by AndyMakous** [will-stone/browserosaurus#116]
[Vim-based](https://github.com/qutebrowser/qutebrowser) browser I like to use in some contexts, would be neat to see it up.

**Comment by will-stone** [comment]
Will do. Could you please do me a favour and ask for the logo to be added here: https://github.com/alrra/browser-logos ? Thanks.

**Comment by will-stone** [comment]
@AndyMakous Please put a link to the request here once you've done that so I can follow it. Thanks.

**Comment by kklot** [comment]
@will-stone qutebrowser is added

**Comment by will-stone** [comment]
Added in v6.4.0
