### ISSUE TITLE
Brave Browser Beta and Dev not detected

### ISSUE THREAD

**Issue by mikaelf** [will-stone/browserosaurus#117]
👋

Brave Browser Beta and Dev isn't detected by Browserosaurus.

**Comment by Victorio115** [comment]
It happens with [Nightly Channel](https://brave.com/download-nightly/) too.

**Comment by will-stone** [comment]
Will add when I have a moment. Thanks both.

**Comment by mikaelf** [comment]
Great, thanks!

**Comment by lsahil** [comment]
Any update ? I love using brave but i have to change to chrome for google work apps. Would be really handy !!! Thanks !

**Comment by will-stone** [comment]
Fixed in v6.4.0

**Comment by gottabeleGIT** [comment]
Brave Nightly does not show up for me

**Comment by will-stone** [comment]
@gottabeleGIT Is Brave Nightly different from Brave Dev? If so, please log a new issue for a new browser to be supported. If not, please log a new bug that Brave Dev is not showing. Thanks.

**Comment by gottabeleGIT** [comment]
Yes, it is a separate browser. I will open a new issue for it.
