### ISSUE TITLE
Beta, Dev, and Nightly Channel of Brave Browser, in the App please.

### ISSUE THREAD

**Issue by Victorio115** [will-stone/browserosaurus#118]
[Brave Browser](https://brave.com/) has [The Release Channel](https://brave.com/download), [the Beta Channel](https://brave.com/download-beta), [The Dev Channel](https://brave.com/download-dev), and [The Nightly Channel](https://brave.com/download-nightly).  
  
But only [The Release Channel](https://brave.com/download) is available in the App.  
   
## Example  
  
My computer has The Release Channel, and The Nightly of Brave Browser.
![image](https://user-images.githubusercontent.com/50971728/63903114-2ea5ce00-c9c1-11e9-93ef-21f039a4bc40.png)  
  
But only The Release Channel of Brave appears when I click on a Link.
![image](https://user-images.githubusercontent.com/50971728/63903094-19c93a80-c9c1-11e9-80f9-2c663850eac8.png)  
  
## Highly Relevant Fact  
  
This could be an extension for the Issue #117.

**Comment by Victorio115** [comment]
This could be an extension for #117.

**Comment by will-stone** [comment]
Thanks for the detailed report, however I think we can safely say this will be covered by #117 👍
