### ISSUE TITLE
Browserosaurus doesn't appear in Menu bar

### ISSUE THREAD

**Issue by mb916** [will-stone/browserosaurus#120]
I can't figure out how to update Settings. When the app is running, I can never get it to display in the Menu bar. Is there a trick to this?

I'm on MacOS Mojave 10.14.6

**Comment by will-stone** [comment]
Hi. You don't see the "B" in the menu bar after opening the app?

**Comment by mb916** [comment]
Hi Will - I don't. There is actually no indication I can see that the app is running (other than the fact that it works when I click links, which is great, btw). But there is no 'dot' indicator beneath the app icon in the dock, it doesn't appear in the Force Quite menu, etc. It's like it's hidden. Maybe that's intentional? But it doesn't allow me a method to update any preferences.

**Comment by mb916** [comment]
Hi Will - My apologies. I did a full reboot and I see the 'B' now. I think the other behavior is intentional. Thank you for the quick reply!

**Comment by will-stone** [comment]
No worries. Maybe it was because there is quite a lot in your menu bar and it's being truncated?
