### ISSUE TITLE
Update checker not working

### ISSUE THREAD

**Issue by nmcc1212** [will-stone/browserosaurus#122]
The update checker offers an update I click restart wait 1 min try again and I am yet again prompted for the update (am on 6.1 updating to 6.4) this has happened 10 times and have now just downloaded it from the website

**Comment by will-stone** [comment]
This is a known bug (to me) with the update checker package. After you click "Restart", you still need to click "Quit" in the menu-bar menu. B will then restart with the new version. I'm trying to figure-out a way around this. I'm thinking I'll just extract the code from the package and make my own updater.
