### ISSUE TITLE
Edge

### ISSUE THREAD

**Issue by nmcc1212** [will-stone/browserosaurus#123]
Edge beta and edge canary are not detected but edge dev is? I need to swap between browsers a lot for my work, and that is why I love Browserosaurus

**Comment by will-stone** [comment]
Beta and canary weren't out when I last added them. I'll add these when I get a moment. Or PR if you need them quicker. You can start here: https://github.com/will-stone/browserosaurus/blob/master/src/config/activities.ts#L46

**Comment by nmcc1212** [comment]
[activities.ts.zip](https://github.com/will-stone/browserosaurus/files/3657053/activities.ts.zip)

**Comment by nmcc1212** [comment]
I think that might work I am not familiar with your code fully though

**Comment by nmcc1212** [comment]
Pull Request has been made
