### ISSUE TITLE
Small problems under Catalina

### ISSUE THREAD

**Issue by i0ntempest** [will-stone/browserosaurus#125]
Under macOS Catalina (I'm using 19A573a at the moment), when clicking a link, the app icon will appear in the dock, and after opening the app icon would remain in the dock as hidden, occupying one of the slots for recently opened apps. This does not happen under macOS Mojave on another computer.
(Also I can help testing if you don't have a mac running Catalina)

**Comment by will-stone** [comment]
Thank-you for being the brave soul to test Browserosaurus on Catalina. I won't be upgrading until the official release but hopefully it won't take much more than upgrade to Electron to sort the issue.

**Comment by albertparedandan** [comment]
i encountered this issue too!

**Comment by will-stone** [comment]
I'm not getting this. Can you confirm you are starting B from `/Applications` folder? As I noticed it was showing in two different locations after my upgrade to Catalina:

<img width="637" alt="image" src="https://user-images.githubusercontent.com/654103/66393774-4ebaab00-e9cb-11e9-8d95-b975993214f2.png">

**Comment by albertparedandan** [comment]
> I'm not getting this. Can you confirm you are starting B from `/Applications` folder? As I noticed it was showing in two different locations after my upgrade to Catalina:
> 
> <img alt="image" width="637" src="https://user-images.githubusercontent.com/654103/66393774-4ebaab00-e9cb-11e9-8d95-b975993214f2.png">

confirmed that B starting from /Applications folder still encounters the same issue. 

btw it seems catalina moved location of applications so apps are duplicated in search box. u have to run "reload" in alfred to clear the cache.

**Comment by will-stone** [comment]
Thanks for that: I ran reload and now only have the `/System/Volumes/...` one. However I've found that one crashes! 😢 I'll have to see what's going on.

**Comment by will-stone** [comment]
Oh, no, now it's working again. But I still don't see the dock icon appearing.

**Comment by albertparedandan** [comment]
interesting, i tried resinstalling B n it still has the same issue

**Comment by chrisands** [comment]
Hmmm... Have the same issue. It seems it's working from `/Application` folder, but icon still appears in dock. It doesn't show up in dock until I click on a link.

**Comment by will-stone** [comment]
Thanks @albertparedandan and @chrisands, do one of you mind recording the behaviour? I’d quite like to see the bug in action. Thanks.

**Comment by chrisands** [comment]
Record on video?

**Comment by i0ntempest** [comment]
@will-stone I'm recording a video now, should be up in mins

**Comment by i0ntempest** [comment]
Here u go
https://puu.sh/EqtJm.mov

**Comment by chrisands** [comment]
Recorded too.
Noticed that it not always opens on sidebar. When I open link in iTerm it works fine. If I do in email app or some messenger it opens on sidebar.
https://imgur.com/a/XYhLnDi

**Comment by gmcinalli** [comment]
I'm also experiencing this.

**Comment by will-stone** [comment]
Thanks all. I'm getting it now too, when I try to open it from Mail.app.

Right, no idea what's going on there. I'll try to have a look as soon as I can. I hoping I can just upgrade Electron, as this may be a bug with `app.dock.hide()`

**Comment by will-stone** [comment]
Might be related: https://github.com/electron/electron/issues/19896

**Comment by i0ntempest** [comment]
Also, not related to this issue but Tor Browser got a new icon a few versions ago, would be nice to have that icon in browserosaurus.

**Comment by will-stone** [comment]
@i0ntempest Please open a new issue for that. Thanks.

**Comment by gmcinalli** [comment]
Ok @will-stone , keep us posted!

**Comment by will-stone** [comment]
This has been fixed by @chrisands and will be in the next release.
