### ISSUE TITLE
Firefox Developer Edition not showing in menu

### ISSUE THREAD

**Issue by abbydigital** [will-stone/browserosaurus#127]
I tried renaming the app to 'ForefoxDevEdition' (it was originally named 'FirefoxDeveloperEdition') but that had no effect.

I did quit Browserosaurus and re-open it before trying: no change.

Also, there Is an item in the menu labeled 'SPACE' and I don't have a browser with that name.

Any suggestions as to what I should try to get the Developer Edition of Firefox into the menu?

In any event, thanks for a great piece of software!

**Comment by will-stone** [comment]
Hi. Thanks for using Browserosaurus. I think it should be named "Firefox Developer Edition". If in doubt, remove the browser and reinstall it, it should keep your profile, but maybe back it up just in case 😄 

"SPACE" refers to the space-key. All the letters refer to keys on the keyboard. That one is _copy-to-clipboard_.

**Comment by abbydigital** [comment]
The rename worked.  Thanks!  (Also glad to know about the copy-to-clipboard function!)

- Abby

**Comment by will-stone** [comment]
Great! 😃  Thanks for letting me know. I'll close this out.
