### ISSUE TITLE
Feature Request: Change keyboard shortcuts

### ISSUE THREAD

**Issue by albertparedandan** [will-stone/browserosaurus#128]
Hi, first of all thanks for the awesome and useful tool. Never realised I needed it until I discovered it.

In the future, is it possible to customise the shortcut buttons? Right now default/favourite browser is set to "Enter" and copy link is set to "Space", but when using a laptop, I think it makes more sense to have "Space" set as favourite browser since it's closer to the trackpad and "Enter" to be copy since it's less used? Thanks for the awesome tool!

**Comment by will-stone** [comment]
Hi. Thanks for the suggestion. Firstly, please see [here](https://github.com/will-stone/browserosaurus/issues/119#issuecomment-533453728) for my view on adding customisation. However, I do agree that space is an easier key to hit and opening a favourite is the most likely action one would take. Therefore, I'm gonna say this is a feature I'll add. It won't be any more than "swap enter/space hotkeys" boolean toggle in the menubar menu.

**Comment by albertparedandan** [comment]
honestly, i think swapping those two would be more than enough since that's about what the average users needs anyway. thanks!

**Comment by will-stone** [comment]
I reviewed this request and have decided that from version 7, the shortcut to copy will be `⌘+C` to be consistent with every other app on macOS. I'll then make `SPACE` the default key to open a favourite but keep `ENTER` key bound to that action as well, but deprecated.

**Comment by long-lazuli** [comment]
on a fork I did (based on much older version), 
I used a double-click to open link in the favorite browser.

I did it on checking if the link was the same as the previous one, and if it was less than some time the last click occurs.

Maybe this can resolve this issue without letting user mess-around with configuration ?

**Comment by will-stone** [comment]
Released in v7
