### ISSUE TITLE
A new line is added to the copied URL

### ISSUE THREAD

**Issue by butaminas** [will-stone/browserosaurus#129]
First of all, great app, I love how it works and it is really convenient for work and in general.

I often use the copy URL feature to copy / paste URL to configs and whenever I copy the URL using Browserosaurus I always get a new line (or '\n') at the end of the URL that I have to delete manually.

I don't know if this is by design or not but it would be awesome if only the URL would be copied and no new lines would be added.

Thanks.

**Comment by will-stone** [comment]
Oh yeah! Good spot, thanks. This should be fairly easy to fix by trimming any white space from the URL.
