### ISSUE TITLE
Link with Firefox Nightly not opening if Nightly isn't running

### ISSUE THREAD

**Issue by daletman** [will-stone/browserosaurus#130]
When Firefox Nightly is not running, opening a link via Browsersaurus will only launch Firefox Nightly but not the link.

- macOS 10.14.6 (18G103)
- Browsersaurus 6.3.0
- Firefox Nightly 71.0a1 (2019-10-04)

Firefox Nightly is set to open the last session with all opened Tabs

**Comment by will-stone** [comment]
I've seen this issue too. Can you please set Nightly as your default browser (in other words, disable Browserosaurus), quit Nightly, then try to open a link. Does this exhibit the same behaviour?

**Comment by will-stone** [comment]
Is this still an issue with v9.0.1 of Browserosaurus?

**Comment by will-stone** [comment]
Closing. Please reopen if the problem persists.
