### ISSUE TITLE
Mac OS Catalina: browserosaurus doesn't work in fullscreen apps

### ISSUE THREAD

**Issue by PierrickGT** [will-stone/browserosaurus#136]
I've recently updated to Mac OS Catalina (Mac OS 10.15) and since I'm also using Brave, I've decided to pull the latest version from master and build it myself. Brave now works again but there is now a problem with apps in fullscreen, the Browserosaurus popup position itself right but on another window on the desktop instead of in the app.

Here is a screenshot of the problem:
<img width="1436" alt="Screenshot 2019-10-14 at 11 44 28" src="https://user-images.githubusercontent.com/2401738/66749690-ce90bb80-ee8a-11e9-9bb2-21745b52e5f7.png">

**Comment by will-stone** [comment]
Hmmm, thanks for this. I reckon this may be due to it not hiding from the dock correctly on Catalina.

**Comment by PierrickGT** [comment]
It works perfectly with the last version (6.5.2), thank you !

**Comment by will-stone** [comment]
Oh, that's great. I didn't think it would, but that's good news 😄

**Comment by GaldanM** [comment]
Hey,

Sorry to open a closed issue but I have the same exact problem, when I try to open a link in, let's say Slack, it only works when not in fullscreen mode. 
When on fullscreen mode, the Browserosaurus icon appears in the Dock but I have to switch to an empty Desktop in order for the pop-up to appear too.

Do you have any idea why ? I'm running v8.1.1 and I tried to "uninstall & reinstall several times" even using "cleanup tools".

Thanks for your work btw, love this app ! 😄

**Comment by will-stone** [comment]
@GaldanM Please see https://github.com/will-stone/browserosaurus/issues/148

**Comment by PierrickGT** [comment]
Thanks for the explanation @will-stone!
I have the problem again too, so it looks like it's pretty random.

**Comment by sadbuttrue** [comment]
Hi,
I have this exact problem. I am on a dual screen setup and when I click on a link in Mail (13.4), on Catalina 10.15.4, it moves to a blank screen and nothing else happens.
