### ISSUE TITLE
macOS Catalina：All gone

### ISSUE THREAD

**Issue by ralphsun73221** [will-stone/browserosaurus#138]
<img width="1066" alt="截圖 2019-10-17 20 59 49" src="https://user-images.githubusercontent.com/26322077/67011185-ad95c800-f121-11e9-95fd-b879b2faed04.png">

This is before I update, but my Brave browser still can't find it.

<img width="1109" alt="截圖 2019-10-17 21 01 00" src="https://user-images.githubusercontent.com/26322077/67011265-d61dc200-f121-11e9-93cc-e95bdfa104bb.png">

This is updated to 6.50, even Safari and Firefox can not find

**Comment by will-stone** [comment]
Hi. Can you please run this and see if you get a list of your applications? `mdfind -onlyin /Applications kMDItemKind=Application`

**Comment by derRaab** [comment]
I can confirm the same problem on macOS Mojave Version 10.14.6. Did downgrade to v6.4.0 and now everything works fine again.

Running `mdfind -onlyin /Applications kMDItemKind=Application` in terminal doesn't print any result.

**Comment by ralphsun73221** [comment]
> Well that's not good. Let's stick to Catalina as that's all I can test with; I may release a frozen v6.4 (without the updater) for Mojave users.
> 
> Is your Applications folder located at `/Applications`? Just wondering if it's a locale/spelling thing.

Yes, I am sure they are all in the application folder

<img width="1523" alt="Finder 2019-10-18 at 09 58 19@2x" src="https://user-images.githubusercontent.com/26322077/67060000-d3f14d00-f18d-11e9-9394-a4958428c768.png">
†

I hope I didn’t misunderstand what you mean.

**Comment by chrisands** [comment]
Can you try command bellow in terminal? @ralphsun73221 @derRaab 
`mdfind -onlyin /System/Volumes/Data/Applications kMDItemKind=Application`

If it doesn't show list of apps can you reply with output of `ls /`?

**Comment by ralphsun73221** [comment]
> Can you please go to the terminal `cd /` and then `ls` to list all files and folders and tell me if the Applications folder is called "Applications". I'm guessing it's not written in English and that's the problem.
> 
> @chrisands We may need to go back to using the profiler to get all apps ^

![終端機 2019-10-18 at 22 02 29@2x](https://user-images.githubusercontent.com/26322077/67100859-0bdeab80-f1f3-11e9-9c70-baf0aca902cc.png)

**Comment by chrisands** [comment]
Thank you. May I ask you to launch few more commands? 
`mdfind -onlyin /Applications .` - this should list all files in Applications folder. Did it listed anything?
`mdls /Applications/Safari.app` - this should get meta data of Safari. Can you send output of command? <details> 
  <summary>Second command should be similar:</summary>
  <img width="541" alt="Screenshot 2019-10-18 at 17 26 30" src="https://user-images.githubusercontent.com/12214583/67102625-6dd7ea80-f1cc-11e9-9176-19f135be5145.png">
</details>

**Comment by derRaab** [comment]
I think I found something: `kMDItemKind` seems to be 'Programm' not 'Application'.

This lists a lot (maybe all) applications:
`mdfind -onlyin /Applications kMDItemKind=Programm`

**Comment by chrisands** [comment]
@derRaab don't know why, but it seems to different on different macs. 
I think I know how to solve it. I'll push today/tomorrow PR to fix it.

**Comment by will-stone** [comment]
I’m on hols for a couple of days. Thanks @chrisands for helping with diagnosis, I’ll review when I get back.

**Comment by ralphsun73221** [comment]
> Thank you. May I ask you to launch few more commands?
> `mdfind -onlyin /Applications .` - this should list all files in Applications folder. Did it listed anything?
> `mdls /Applications/Safari.app` - this should get meta data of Safari. Can you send output of command?
> 
> Second command should be similar:
> <img alt="Screenshot 2019-10-18 at 17 26 30" width="541" src="https://user-images.githubusercontent.com/12214583/67102625-6dd7ea80-f1cc-11e9-9176-19f135be5145.png">

![終端機 2019-10-18 at 23 55 21@2x](https://user-images.githubusercontent.com/26322077/67109306-c9bd6600-f202-11e9-888b-d42ea19b6a97.png)

**Comment by ralphsun73221** [comment]
There may be different language reasons, I am a Chinese user.

**Comment by evanwarner** [comment]
FYI nothing beyond 6.4.0 works in El Capitan. 6.5.2 crashes on launch, and 6.6.x launches but has the problem outlined in this issue. The `mdfind` command finds all the apps in my Applications folder though.

I don't expect much support for my old ass computer these days, but thought it'd be worth mentioning.

**Comment by cocoonkid** [comment]
I was able to fix this issue finally after a few hours.

1. Disable SIP
2.Turn off spotlight:

sudo mdutil -a -i off

3.Unload it:

sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist

4.Load It:

sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist


5.Turn on spotlight again:

sudo mdutil -a -i on

Now everything is being reindexed as expected.Browserosaurus finds all browsers yay!
