### ISSUE TITLE
Whitelist dissenter browser

### ISSUE THREAD

**Issue by boscovn** [will-stone/browserosaurus#139]
I was wondering if you could whitelist the Dissenter Browser (https://dissenter.com)

**Comment by will-stone** [comment]
Could you please open a feature request on Alrra's [browser logos repo](https://github.com/alrra/browser-logos/issues) to ask him to add the logo for Dissenter? Thanks.

**Comment by will-stone** [comment]
Please open Terminal and run:

```bash
mdls -name kMDItemCFBundleIdentifier -r /Applications/dissenter.app
```

replacing "dissenter.app" if this isn't the correct file name, and paste the result here? Thanks.
