### ISSUE TITLE
Suggestion: creating Gitter room for the project

### ISSUE THREAD

**Issue by Jackymancs4** [will-stone/browserosaurus#14]
In order to permit an easier grow of the user community for the app, and allow a more stream lined conversation model I would suggest to create a community on [Gitter](https://gitter.im/home/explore)..

It's rich of slack-like features, has a small learning curve and just need a github account.

The main advantage is for people who want to ask questions without the need to open/close new issue, or the hassle of asking for the permission to open new issues on already opened and unrelated issues.

**Comment by will-stone** [comment]
Sure. I'll set one up now (not done it before so bear with me...)

**Comment by Jackymancs4** [comment]
Great! You also get an awesome badge to append on the Readme xD

**Comment by will-stone** [comment]
You should have been invited.

https://gitter.im/Browserosaurus

**Comment by Ornataweaver** [comment]
You can add the link to README.md
