### ISSUE TITLE
Feature request: Open links in background

### ISSUE THREAD

**Issue by pintapass** [will-stone/browserosaurus#142]
I'd like the option for the Browsersaurus link to open in the background in the selected browser.

At the moment the behavior is to automatically switch to the browser. There are times, however, when I'm clicking multiple links, and I'd like them to remain in the app while the links open quietly in the background. Is this possible?

**Comment by will-stone** [comment]
This is enabled for Firefox, Safari, and the Tor browsers; just hold alt/opt. Not all browsers support this feature but as I find more, they will be added. Browsers that are not supported will fade-out after you hold alt. Note, you must hold alt _after_ clicking the link; whilst the picker window is open.

**Comment by pintapass** [comment]
Thanks. Is there a way to make that the default behavior to avoid having to click Alt/Opt?

**Comment by will-stone** [comment]
Not currently. If every browser supported it, then I wouldn't mind adding this option. However, it would mean a lot of browsers being faded-out (not clickable) by default until alt is held which I don't think is acceptable behaviour.
