### ISSUE TITLE
HTML files

### ISSUE THREAD

**Issue by pniedzwiedzinski** [will-stone/browserosaurus#143]
Hey! I use browserosaurus a lot and I love it ❤️.
I have an idea how it can be even better. The idea is to add option for opening html files that are located on local disk (all path like `/*.html`) with code editor like vscode.
I think that might be useful. How about you guys?

**Comment by will-stone** [comment]
Thanks, glad you like it 🤗 Hmmm... can you guide me through step-by-step the flow you would like. i.e. double click file... blah blah blah. I ask because I kinda feel this is covered by right-click, open with..., select VSCode.

**Comment by pniedzwiedzinski** [comment]
When you open a link from a terminal it opens with default program, hence HTML default is broserosuarus it might be good at this point to have this option. Similar when you open the downloaded file directly from a browser. It's not the problem that this project targets but it might be a nice enhancement

**Comment by will-stone** [comment]
Right, got yer. So if you run `open example.html` it opens Browserosaurus. If you want to open in VSCode, you can run `code example.html`. Nice suggestion but I think this is out of scope for B. Thanks.
