### ISSUE TITLE
can't open files ?

### ISSUE THREAD

**Issue by long-lazuli** [will-stone/browserosaurus#146]
I can't open `.html` files in Browserozaurus :(

**Comment by will-stone** [comment]
Why would you want to?

**Comment by long-lazuli** [comment]
I had to work on a 'webpage packaging' today.
And I got some offline files to test out (like few dozen times, (debug/retry style) );

I had to use the Open with contextual menu.
Without Browserosaurus, I usually do those actions with keyboard only.

I don't know how it works and if it's easier to restrict browserosaurus association to hypertext protocols, or to be able to handle file://...

**Comment by will-stone** [comment]
Isn’t the “open with...” context menu the equivalent of Browserosaurus? You’re opening a menu which shows you a list of browsers to choose from, sound familiar? 😉

If I’m not understanding the issue, please write the steps exactly, including expected and actual outcomes. [Here’s a nice article by Testlio](https://testlio.com/blog/the-ideal-bug-report/) for some tips on what to include in a bug report. Thanks 😊

**Comment by evanwarner** [comment]
@long-lazuli Select any HTML file in the Finder and choose File > Get Info. In the "Open with" section is Browserosaurus the chosen app in the dropdown? If not, set it to be then hit the "Change all..." button below that. Now when you open an HTML file it'll trigger Browserosaurus.

**Comment by long-lazuli** [comment]
@evanwarner , that's exactly the point. Did you even try that ?

I'm sorry if this issue is poorly written.
And I don't know if the article "how to answer 'bad-written bug reports'" even exists, but that could come handy.

---

Here's a GIF that might help to understand the problem.

![browserorsaurus-issue-146](https://user-images.githubusercontent.com/1178625/68687485-8b029d80-056d-11ea-9dfd-b78b546313d5.gif)

As you can see nothing happens when I tried to open a .html from the Finder.

Feel free to close this issue if I failed again to explain my problem.
Thanx

**Comment by evanwarner** [comment]
Strange. Yes, opening an HTML file triggers Browserosaurus for me. I'm still on version 6.4.0 though (old computer). You could try an older version from the [releases page](https://github.com/will-stone/browserosaurus/releases) and see if it works for you.

**Comment by will-stone** [comment]
Opening Browserosaurus for `.html` files from the finder is working for me.

- macOS 10.15.2
- Browserosaurus 9.0.1

Maybe try using latest version? I'm gonna close this for now.

**Comment by MichaelWatzke** [comment]
Same issue here,
Browserosaurus 9.3.0 (also on older version, switched from 6.5 today)
Macos 10.15.2 and 10.15.4

Issue is only in Finder. No popup window to pick a browser. Works ok in other apps. Same issue on two different computers - Macbook Pro and iMac.
