### ISSUE TITLE
Tweak app scan

### ISSUE THREAD

**Issue by will-stone** [will-stone/browserosaurus#147]
@chrisands do you reckon we could get away with just using `mdfind -onlyin /Applications kMDItemKind="*"` to scan for apps, rather than the current two-command approach?

**Comment by chrisands** [comment]
In `/Applications` folder might other files besides `*.app`. For example, I get a lot of other file types in apps folder.
It's just a small part of what I get in console.
```
/Applications/Utilities/Adobe Application Manager/LWA/ZStringResources/cs_CZ/stringtable.xml
/Applications/Utilities/Adobe Application Manager/LWA/ZStringResources/cs_CZ
/Applications/Utilities/Adobe Application Manager/LWA/ZStringResources
/Applications/Utilities/Adobe Application Manager/LWA/PWANative.dylib
/Applications/Utilities/Adobe Application Manager/LWA/PWAFlex.swf
/Applications/Utilities/Adobe Application Manager/LWA/assets/fonts_system.swf
/Applications/Utilities/Adobe Application Manager/LWA/assets/fonts_clean.swf
/Applications/Utilities/Adobe Application Manager/LWA/assets
```

An app still needs to sort `*.app` files I think, but to be sure let's test performance and select fastest. I probably can do it next week.

**Comment by will-stone** [comment]
Thanks. Much appreciated.

**Comment by will-stone** [comment]
Slightly different scanning mechanism: https://github.com/will-stone/browserosaurus/pull/151/files#diff-4a607cdc87ff22df72d295ce021e5b00

**Comment by chrisands** [comment]
I run few test and here's result:

| # of run | old search method | kMDItemKind="*" | getInstalledBrowsers |
| -------- | ----------------- | --------------- | -------------------- |
| 1        | 1465.842ms        | 1572.668ms      | 449.330ms            |
| 2        | 1494.082ms        | 1547.648ms      | 461.027ms            |
| 3        | 1438.420ms        | 1602.869ms      | 435.135ms            |
| 4        | 1526.333ms        | 1545.339ms      | 444.253ms            |
| 5        | 1540.188ms        | 1509.918ms      | 528.602ms            |



> old method

```javascript
const { stdout: kMDItemKind } = await execP(
  'mdls -name kMDItemKind -raw /Applications/Safari.app',
)

const { stdout: mdfind } = await execP(
  `mdfind -onlyin /Applications kMDItemKind=${kMDItemKind}`,
)

const paths = mdfind.trimRight().split('\n')
```



> kMDItemKind="*"  

```javascript
const { stdout: mdfind } = await execP(
  `mdfind -onlyin /Applications kMDItemKind="*"`,
)

const paths = mdfind.trimRight().split('\n')
const sortedPaths = paths.filter(path => path.match(/.+\.app/))
```

**Comment by will-stone** [comment]
Thanks! Looks like the whitelist _ping_ was the way to go.
