### ISSUE TITLE
History of opened links

### ISSUE THREAD

**Issue by kopach** [will-stone/browserosaurus#149]
**Is your feature request related to a problem? Please describe.**
Sometimes, when I click on some link in some app – browserosaurus window pops up but then previous app takes focus back e.g. by automatically closing it's window on link click. In this way I'm losing clicked link as browserosaurus window disappears once other app takes focus. 

**Describe the solution you'd like**
I suggest having history of opened links stored by browserosaurus. So, I can later open previously clicked link from context menu. This also may be helpful, when working with terminal and running logs. E.g. I click some link in terminal while terminal still gets updated with logs. At some point there are so many logs in terminal - I cannot find previously clicked link.

**Comment by will-stone** [comment]
Interesting idea. As a work around, you could use a clipboard manager (I use Alfred's), then you can use `command+c` to copy the URL to the clipboard, and your manager will keep the history for you.

**Comment by kopach** [comment]
Yes, I do so (I use Clipy). Anyway, described case is different (at least first case). browserosaurus gets closed so fast – I have no chance to copy that link to clipboard. On the other hand – I usually do not expect browserosaurus to be closed immediately, therefore I'm not ready to press `command+c` asap on link click :D

**Comment by will-stone** [comment]
Gotcha. Well this is certainly a nice idea. I've no idea how I'd implement the UI so don't expect this any time soon, but I'll certainly give it some thought.

**Comment by kopach** [comment]
Thank you @will-stone, that would be awesome 👍

**Comment by will-stone** [comment]
This feature will be in the upcoming redesign of Browserosaurus I'm working on. Keep an eye on GitHub issues and/or my twitter for updates.

**Comment by will-stone** [comment]
This will be in v10

**Comment by will-stone** [comment]
Released in v10.
