### ISSUE TITLE
Look for browsers also unde ~/Applications folder

### ISSUE THREAD

**Issue by kopach** [will-stone/browserosaurus#150]
**Describe the bug**
I have multiple users on my Mac and I prefer separating apps between them. Official way of doing this - Create `~/Applications` folder and having apps for each user there. Unfortunatelly browserosaurus doesn't search for browsers in `~/Applications` folder

**To Reproduce**
Steps to reproduce the behaviour:
1. `mkdir ~/Applications`
2. `move /Applications/Firefox ~/Applications/Firefox`
3. Open link in browserosaurus
4. No Firefox browser detected by browserosaurus

**Expected behaviour**
browserosaurus should see browsers from `~/Applications` folder (In scenario above it's Firefox) and suggest them to be used in order to open link

**Desktop (please complete the following information):**
 - OS: [macOS 10.14.6]
 - Version [e.g. 8.0.1]

**Comment by will-stone** [comment]
This should be easy enough to add. However, is `~/Applications` an "official" method? What about other languages? Also, I'd say this is a feature request rather than a bug (label updated).

**Comment by kopach** [comment]
> is ~/Applications an "official" method?

Unfortunately, have no time to search for official info, however, If you create `~/Applications` folder – it will automatically have same icon as for `/Applications`. Also, other programs like [Browser ChooserX](https://www.bdevapps.com/browser-chooserx1.html) does detect browsers correctly inside `~/Applications` folder

**Comment by will-stone** [comment]
Okay, thanks @kopach.

@chrisands As the project uses a whitelist system, maybe we just ping every browser? For example, I have Brave installed but not Brave Dev:

![image](https://user-images.githubusercontent.com/654103/68120892-4ee09480-fefe-11e9-8f0f-cd54db08b945.png)

**Comment by will-stone** [comment]
@kopach as you said you have Firefox in `~/Applications` could you please run `mdfind kMDItemCFBundleIdentifier = "org.mozilla.firefox" and see if it correctly finds it?

**Comment by kopach** [comment]
@will-stone, I've just moved Firefox temporary to `/Applications` folder in order to be compatible with browserosaurus and that required me to reconfigure Firefox. If it's not a problem for you – let me test this later today or tomorrow as I don't have much time right now.

**Comment by will-stone** [comment]
@chrisands If you have a moment can you please sanity check my PR: https://github.com/will-stone/browserosaurus/pull/151/files#diff-4a607cdc87ff22df72d295ce021e5b00 Thanks 🙂

**Comment by chrisands** [comment]
@will-stone looks good! 
Need to check what will be output if the same browser installed in different users.

**Comment by kopach** [comment]
> @kopach as you said you have Firefox in `~/Applications` could you please run `mdfind kMDItemCFBundleIdentifier = "org.mozilla.firefox"` and see if it correctly finds it?

@will-stone, here is result:

```
➜  ~ mv /Applications/Firefox.app ~/Applications/Firefox.app
➜  ~ mdfind kMDItemCFBundleIdentifier = "org.mozilla.firefox"
/Users/<my-home-folder>/Applications/Firefox.app
```

**Comment by will-stone** [comment]
Thanks @kopach. I just need to complete a little more testing, then there should be a fix ready for you.

**Comment by will-stone** [comment]
Release in v8.1.0
