### ISSUE TITLE
Naver Whale browser

### ISSUE THREAD

**Issue by Miracle7days** [will-stone/browserosaurus#153]
**Browser Name**
Whale Browser

**Link to browser's webpage**
https://whale.naver.com/en

**Comment by will-stone** [comment]
Could you please open a feature request on Alrra's [browser logos repo](https://github.com/alrra/browser-logos/issues) to ask him to add the logo for Whale? Thanks.

**Comment by Miracle7days** [comment]
how can i do that?

**Comment by will-stone** [comment]
Well, ideally send him a PR or simply log an issue on the repo.

**Comment by Miracle7days** [comment]
[https://upload.wikimedia.org/wikipedia/ko/7/7a/Naver_whale_logo.png](url)
you want this? I don't no what to do.. i'm not programer

**Comment by will-stone** [comment]
Please open Terminal and run:

```bash
mdls -name kMDItemCFBundleIdentifier -r /Applications/naver-whale.app
```

replacing "naver-whale.app" if this isn't the correct file name, and paste the result here? Thanks.
