### ISSUE TITLE
Chrome is not listed after update

### ISSUE THREAD

**Issue by dimaboyko** [will-stone/browserosaurus#156]
**Describe the bug**
After update, Google Chrome is not showing on the list 

**To Reproduce**
Steps to reproduce the behaviour:
Click any link
**Expected behaviour**
List of Firefox, Safari and Chrome in my case.

**Screenshots**
![image](https://user-images.githubusercontent.com/16645596/68397361-5f4d7500-0173-11ea-81e0-a9b4f94b10d4.png)
![image](https://user-images.githubusercontent.com/16645596/68397387-6aa0a080-0173-11ea-84e1-0560a1496760.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Version [e.g. 8.1.2]

**Comment by will-stone** [comment]
I've had this before. I relaunched Chrome, then relaunched B and that fixed it. Let me know if that works?

**Comment by dimaboyko** [comment]
I have tried that few times before reporting, but weird enough, but this has worked after few more attempts. Thanks for advise.

**Comment by will-stone** [comment]
Nice. This is a bug with macOS itself: it’s not finding Chrome in the Applications folder. Maybe a Spotlight indexing issue, not sure.
