### ISSUE TITLE
Feature request: Open links in background

### ISSUE THREAD

**Issue by SeeHavens** [will-stone/browserosaurus#161]
Hi, can there be an option to open links in the background without bringing the browser in focus?

**Comment by will-stone** [comment]
Hi. There already is: hold alt before clicking a browser. It only works with a couple of browsers so I don’t really see it as a finished feature and why it’s not documented.

**Comment by will-stone** [comment]
Please see: https://github.com/will-stone/browserosaurus/issues/142 and https://github.com/will-stone/browserosaurus/issues/54
