### ISSUE TITLE
Add support for new (stable) Microsoft Edge

### ISSUE THREAD

**Issue by ibanezda** [will-stone/browserosaurus#167]
Hi, I was wondering if you could add support for Edge given that it was just released officialy, let me know if I can be of any help

**Microsoft Edge **

**https://www.microsoft.com/en-us/edge?ranMID=24542&ranEAID=nOD/rLJHOac&ranSiteID=nOD_rLJHOac-n2eCPBfVNJcwHliEyJc34w&epi=nOD_rLJHOac-n2eCPBfVNJcwHliEyJc34w&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=(ir__qnpqbymg9x2vcvktwlt9lnguw32xlhgq1fdens2i00)(7593)(1243925)(nOD_rLJHOac-n2eCPBfVNJcwHliEyJc34w)()&irclickid=_qnpqbymg9x2vcvktwlt9lnguw32xlhgq1fdens2i00**

**Comment by will-stone** [comment]
Please read: https://css-tricks.com/open-source-etiquette-guidebook/#article-header-id-1

**Comment by will-stone** [comment]
Thanks. I noticed that came out yesterday too. I’ve got a bunch of stuff to do on B so I’ll probably work on it this weekend.

**Comment by will-stone** [comment]
Will be release in v9
