### ISSUE TITLE
Add support for Cliqz

### ISSUE THREAD

**Issue by mindfulsource** [will-stone/browserosaurus#170]
**Cliqz**

**https://cliqz.com/en/download**

**Comment by will-stone** [comment]
What a name! Sounds like spyware 😕 Will add when I get a moment. Or you can open a PR? Adding a browser is pretty straight forward these days and I can walk you through it if you fancy it?

**Comment by mindfulsource** [comment]
Hmm, OK! You mean a pull request? Happy to follow your instructions! Did you mean doing it over chat? I may have a moment to do that also, if we coordinate and timezones are compatible enough.

Cliqz seems like a cool browser actually. It has a feature to automatically dismiss those annoying GDPR cookie banners. Just hope it's not a Chinese-controlled spyware company eh?

It's just one of 20 browsers I use - I'm obsessed with having a million browsers LOL.

**Comment by will-stone** [comment]
I just meant I can write the steps. Don't worry if you don't fancy it. I'll put them here with the aim to migrate them to the README someday...

- Add the browser name to `browserNames` in `src/config/browsers.ts`.
- [Find the browser bundle identifier](https://github.com/will-stone/browserosaurus#finding-bundle-identifier-appid-for-an-app).
- Add the config to the `browsers` object in `src/config/browsers.ts`.
- Install the browser logo from here: https://github.com/alrra/browser-logos
- Add the logo to the `src/config/browserLogos.ts` file.
- `yarn typecheck`
- `yarn lint`
- done 🙂

Here's a commit that demonstrates the above: https://github.com/will-stone/browserosaurus/commit/45a1c6af324428a249789de811ffdb5fdc69d5fd

**Comment by mindfulsource** [comment]
Thanks. I'm working through it and working github stuff out. Can I confirm, since the Cliqz logo isn't in browser-logos project, I have to try to get it included in that before I can come back here to complete the pull request?

**Comment by will-stone** [comment]
You can bring in the logo yourself if you like; the manual additions live in `src/config/`. I've found 256x256 is a good size. Any bigger and they slow the loading of the app. Ideally use an SVG.

**Comment by mindfulsource** [comment]
OK, I've made an SVG and brought it into my own github fork.

I'm a complete n00b, but I'll come back tomorrow and work out how to submit a pull request for the 4-5 things in one convenient single pull request. (Any small tip on that would be great. I'm not using git, just github.com in the browser. I seem to have created multiple commits each time I make a change.)

Yay for github and open-source! I found a [possible mail version](https://github.com/will-stone/browserosaurus/issues/163) of Browserosaurus called '[Bumpr](https://getbumpr.com/faq.html)', but it's way more fun to contribute to an open-source project.

**Comment by will-stone** [comment]
Different commits are fine. You should be able to submit a PR on the PRs page and choose your fork's master as the compare branch. Don't worry if it all seems very confusing right now; you'll soon be contributing to all sorts of projects 😄 I do suggest some reading-up on beginner guides to git, it's a very powerful tool to have under your belt.

**Comment by mindfulsource** [comment]
I feel so clumsy, I _think_ I've done it. Let me know if I need to do anything else. :) (I'm sure I'll get better, thanks for the encouragement. :P)

Also, is shift-C possible for Cliqz if we put a capital `C` or the correct hotkey string in `browsers.ts`?

**Comment by will-stone** [comment]
I'll take a look when I get a moment. Have you given me permission to edit? It might be on by default.

Don't worry about the build errors for now, it looks like something I've done.

As for hotkey, no, the shift modifier isn't supported. I suggest `z`, which hasn't been taken yet. With all these browsers popping-up these days, we're sure to run out of letters and I'll have to rethink the hotkey strategy eventually 😕

**Comment by mindfulsource** [comment]
Yep I can see "Allow edits from maintainers" is ticked when I see the pull request.

OK, just added another commit adding 'z' as my nabbed shortcut. :) Thanks for that.

**Comment by will-stone** [comment]
Released in v9.1.0
