### ISSUE TITLE
Allow disabling check for default browser.

### ISSUE THREAD

**Issue by marcusramberg** [will-stone/browserosaurus#171]
I'm using Browsersaurus as a fallback for Hammerspoon, which has some default rules for sites I always want to open in a given browser, but after every startup Browsersaurus asks me if I want to change the default browser. Would be nice if it was possible to disable this dialog, like you can do with most browsers.

**Comment by will-stone** [comment]
Ooo, did not think of that. Yeah this should be a fairly straight forward option to add. It'll just be a boolean around this: https://github.com/will-stone/browserosaurus/blob/master/src/main/main.ts#L184 I'll look into when I next do my batch of updates.

**Comment by marcusramberg** [comment]
Thanks, been testing the beta. Works great :)
