### ISSUE TITLE
[Feature request] Don't ask which browser use, if only one browser is running

### ISSUE THREAD

**Issue by armandocin** [will-stone/browserosaurus#173]
Thank you for this great app.

In my opinion, a feature that could make this app more awesome is the option to choose whether or not prompt the user with the browser choice, when only one browser is running. 

I'd like to cut the time of clicking on the chose browser when only one of them is running, and directly open the link in the opened window.

**Comment by will-stone** [comment]
Thanks for the feedback.

Interesting idea, however I'm a fan of muscle memory and I like to know the picker will open _every time_. One of the benefits of Browserosaurus is the ability to back-out of opening a link, which you would lose if this feature were enabled.

The space-bar is currently set to open your favourite browser. This key has a large hit target and I find it very natural to click a link and whack the space-bar to open links quickly.
