### ISSUE TITLE
Firefox Developer Edition Support

### ISSUE THREAD

**Issue by Kulcanhez** [will-stone/browserosaurus#176]
**Browser Name**
Firefox Developer Edition
**Link to browser's webpage**
https://www.mozilla.org/en-US/firefox/developer/

Thank you for your amazing job!

**Comment by will-stone** [comment]
This should [already be supported](https://github.com/will-stone/browserosaurus/blob/master/src/config/browsers.ts#L15). Hmmm 🤔 Maybe Mozilla has changed the bundler ID. Could you please run `mdls -name kMDItemCFBundleIdentifier -r /Applications/[NAME OF APP].app` replacing `[NAME OF APP]` with the FF Dev addition name in your apps folder, and let me know the id?

**Comment by Kulcanhez** [comment]
The browser appears on the popup but with no shortcut. This what I got:
org.mozilla.firefoxdeveloperedition%

**Comment by will-stone** [comment]
Oh. The current hotkeys are for the stable versions of browsers only (due to everyone having dev channels these days). Set it as your favourite and then you can use `space` or `enter`.

**Comment by Kulcanhez** [comment]
Ahhh ok sorry. Makes sense that you made that way. Thank you!!
