### ISSUE TITLE
Opera GX Browser [add browser]

### ISSUE THREAD

**Issue by aaronkim98** [will-stone/browserosaurus#178]
Please add support for Opera GX browser!

**Comment by will-stone** [comment]
I can see you're new to open source development (I'm making the assumption from your empty GitHub history), for future reference, please fully read the linked article in the issue template. Also, it looks like you skipped using the "Add Browser" template, this requests that you link to the browser homepage (no worries, I found it 😄). It's always a good idea to use projects' provided issue templates where possible as they will inevitably prompt for more information than one thinks to provide.

That said, thanks for wanting to get involved with my project. If you'd like this browser added sooner, you can add the browser yourself and submit a Pull Request. I've written-out the steps in [this comment](https://github.com/will-stone/browserosaurus/issues/170#issuecomment-576193982) but I'm happy to help once you file the PR. The person who raised the issue where I wrote that comment was unsure too but submitted a PR and now B supports the Cliqz browser. [Here's a good article](https://opensource.com/article/19/7/create-pull-request-github) on how to submit a PR. Don't worry if the code isn't perfect or if tests don't pass, we can develop it together.
