### ISSUE TITLE
Any idea why the most recent build of browserosaurus only shows Safari as an option to open?

### ISSUE THREAD

**Issue by ngerasimatos** [will-stone/browserosaurus#179]
In the most recent release v9.2 I am only able to select Safari and not Chrome, Firefox, Brave, or any other browser to open with browserosaurus.

**Comment by will-stone** [comment]
Thanks for logging. Did you try the suggestions I mentioned on Twitter? Restart OS, reindex Spotlight?

Which version of macOS are you using?

**Comment by will-stone** [comment]
Please re-open if you are still experiencing issues after trying my suggestions.
