### ISSUE TITLE
Ability to reduce animations/eyecandy

### ISSUE THREAD

**Issue by prewk** [will-stone/browserosaurus#181]
Great tool, thanks!

**Is your feature request related to a problem? Please describe.**
On my computer (Mac Mini with a slow iGPU + 5k display) the fullscreen fade-in lags.

**Describe the solution you'd like**
I would love to be able to just toggle the animation parts of the application via the dropdown:

![image](https://user-images.githubusercontent.com/640102/77286345-51882e80-6cd3-11ea-9c2b-d261780dd3a6.png)

**Describe alternatives you've considered**
I don't have any alternatives, it's just too many pixels to push out for my integrated graphics card.

**Additional context**
A 60 fps video that sort of illustrates the problem: https://imgur.com/a/6gJikM3

**Comment by will-stone** [comment]
Thanks. Yeah, I've found the animations have mixed results depending on when Browserosaurus is initiated and hardware. I can imagine that combining a slow GPU and a 5k display isn't optimal. Maybe, rather than adding configuration to B, it respects the reduce motion and/or the reduce transparency system settings:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/654103/77306625-dc772200-6cef-11ea-9a46-19ec51f08d0e.png">

Depends if there is an Electron API to read that info.

**Comment by prewk** [comment]
Yeah I thought of those settings too, but then I felt that I wouldn't want to reduce it globally.. Wish I could set those settings on an application-to-application basis :) It works pretty smoothly most of the time.

If you wanna try out your own suggestion, try this (because it's just CSS, right?): https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by will-stone** [comment]
It currently uses React Spring for the animations. Looks like this package could help: https://www.npmjs.com/package/react-reduce-motion

**Comment by Kulcanhez** [comment]
Hello community! I came here to see if there was some update to the app because lately it's has been lagging on my MBP. It would be awesome to be able to reduce the animation for this application.

**Comment by will-stone** [comment]
PRs welcome. Here's a good place to start: https://www.electronjs.org/docs/all#systempreferencesgetanimationsettings

**Comment by RyanRoberts** [comment]
Just want to leave a comment to say that I'm also interested in reduced animation. Even on my 2019 15" i7 MBP I find B is slow and laggy more often than not. The animation feels excessive.

**Comment by will-stone** [comment]
Here’s where the animation for the picker is configured, please have a play and reply with your findings. https://github.com/will-stone/browserosaurus/blob/86781bc1d6f482ec052cbb4a826549325ba5b844/src/renderer/features/Picker.tsx#L70 Lets discuss solutions, not problems.

**Comment by will-stone** [comment]
I've removed React-Spring and released 9.3. Let me know your thoughts.

**Comment by prewk** [comment]
Thanks, it feels much snappier! Sorry I couldn't contribute, very busy times atm.

**Comment by will-stone** [comment]
Indeed. No need to apologise, we are living in weird times. Okay, let’s stick with this for a bit. Ideally, it would be as smooth as a popover on a Calendar event, this would also make it feel very native. However, I think we may be limited by Electron’s sluggishness when it returns to the forefront after a given time in the background (this is when I found it most janky).

**Comment by prewk** [comment]
Yeah that'd be awesome! I'm thinking it might be that the fullscreen overlay thing needs to push too many pixels (at least on my display), so I'm following #182 :)
