### ISSUE TITLE
Automatic browser rules

### ISSUE THREAD

**Issue by kemayo** [will-stone/browserosaurus#183]
It'd be convenient to be able to write rules to tell browserosaurus that some sites should *always* open in a specific browser.

The easiest form of this would be to specify domains / URL prefixes, e.g. "https://phabricator.wikimedia.org -> Google Chrome".

More complicated / harder to support options (as in, I don't know if the relevant information is even accessible) would include:
* all links opened from Apple Mail -> Safari
* all links opened on Space 3 -> Firefox

The main complication for this feature seems like it'd exist in the UI: some sort of preferences dialog would need to be added to write these rules. (Or, if it's done though something in the browser-picker like a "remember this choice for this domain" button or similar, at least UI to *remove* the rule).

**Comment by will-stone** [comment]
Thanks. Duplicate: https://github.com/will-stone/browserosaurus/issues/113 https://github.com/will-stone/browserosaurus/issues/53 https://github.com/will-stone/browserosaurus/issues/32
