### ISSUE TITLE
Add Waterfox browser

### ISSUE THREAD

**Issue by VandrerenErik** [will-stone/browserosaurus#186]
**Waterfox**

**https://www.waterfox.net/**

**Iridium**

**https://iridiumbrowser.de/**

**Comment by will-stone** [comment]
Iridium should [already be supported](https://github.com/will-stone/browserosaurus/blob/master/src/config/browsers.ts#L88), is it not showing up?

**Comment by VandrerenErik** [comment]
> Iridium should [already be supported](https://github.com/will-stone/browserosaurus/blob/master/src/config/browsers.ts#L88), is it not showing up?

Yes it is, it started showing up after restarting Broweserosaurus and I posted this before the restart.

**Comment by will-stone** [comment]
Please open Terminal and run:

```bash
mdls -name kMDItemCFBundleIdentifier -r /Applications/waterfox.app
```

replacing "waterfox.app" if this isn't the correct file name, and paste the result here? Thanks.
