### ISSUE TITLE
Remember last used browser for each website (map websites to browsers)

### ISSUE THREAD

**Issue by lucagiovagnoli** [will-stone/browserosaurus#187]
Hi, cool project!

**Describe the solution you'd like**
Wondering if anyone else would find useful for the browserosaurus to remember which browser was used last time for a specific website.

That way browserosaurus would know which browser to pick automatically for specific link types. I'd consider only the domain name, like wikipedia.com, not full links (so wikipedia.com is the same as https://en.wikipedia.org/something/something).

Eg:
gmail.com -> Chrome
wikipedia.com -> Safari
wikipedia.com/something -> Safari
...

**Comment by will-stone** [comment]
Thanks. Duplicate: #183 #113 #53 #32

However, I am currently rethinking how Browserosaurus works, turning it into more of Browser _manager_ than a Browser _picker_. This is all in conception stage at the moment, keep an eye on the issues and/or my Twitter as I'll probably post an RFC there first. Essentially, this feature could possibly exist in the new world but is not something I'd like to explore right now.

**Comment by will-stone** [comment]
Browserosaurus is a freely available open source app, so I'd suggest avoiding phrases such as "a deal breaker for me" or "if this feature gets added then I'll use it" as it gives the air of entitlement.

That aside: you can set up the workflow you need by combining Browserosaurus with Finicky: https://github.com/will-stone/browserosaurus/discussions/476

This feature will never be baked directly into Browserosaurus.

Thanks 🙂
