### ISSUE TITLE
Checks for updates too often

### ISSUE THREAD

**Issue by stgarf** [will-stone/browserosaurus#189]
Browserosaurus tries to "check for updates" way too often. This request for network access pops up every 10 minutes or so which is **crazy** (and you can bet  I've got a blanket **DENY ANY** now and I'll unblock it manually occasionally until this gets fixed). A much more _sane_ default is once a week at minimum -- base it on how often you are realistically pushing dire changes that a user should get.

![Screen Shot 2020-04-15 at 13 55 26](https://user-images.githubusercontent.com/1694002/79387616-de17bc80-7f20-11ea-923b-636f1a25fb06.png)

**Comment by will-stone** [comment]
Woah! Calm down. Don't log issues with mild forms of blackmail/entitlement 😠 Remember the app is provided for free.

Okay, yes it currently checks every 10 minutes. I will be changing this in a future release.

**Comment by stgarf** [comment]
Woah, I think you misread some tone into that that's not there. Just filing a bug report and I appreciate you're work @will-stone :)

**Comment by will-stone** [comment]
Remember that hours of spare time go into open source projects, and real money. Avoid phrases like "until this gets fixed", it makes it sound like you are demanding a change. It's best not to complain about a possible non-bug until you have found out the decisions behind it (which could quite likely be an accident left over from testing). I do appreciate the input from users, let's all be civil 😄
