### ISSUE TITLE
Add Local Browser Selection/Usage Statistical Information

### ISSUE THREAD

**Issue by stgarf** [will-stone/browserosaurus#190]
I used to use [MultiBrowser](https://sites.google.com/site/tesseractsoftware/multibrowser) (but it doesn't work properly anymore on macOS Catalina)... since trying out browsersaurus one of the things I'd like are local usage statistics on which browser I've selected. 

Here's an real-world example of my current usage:
![Screen Shot 2020-04-15 at 14 04 33](https://user-images.githubusercontent.com/1694002/79390248-3a301000-7f24-11ea-80cc-96a00fc84423.png)

MultiBrowser can also take those statistics and make (if you ask/allow it to) a simple API call to Google to create a small pie chart. (Since you're running electron natively, locally, you might just try something like [charts.js](https://www.chartjs.org/) instead to no external network calls need to be made.

![Screen Shot 2020-04-15 at 14 04 42](https://user-images.githubusercontent.com/1694002/79390257-3ef4c400-7f24-11ea-84f5-bef91dee1420.png)

**Comment by will-stone** [comment]
I had this idea the other day too 😄 I will look to add it to the upcoming rewrite.

**Comment by will-stone** [comment]
I've been thinking about this and I'm not sure if I should add this feature; firstly, I'm really am unsure on the benefit it brings. And secondly, for those that don't know the inner workings of B, may see it as B collecting data about them and could potentially feel intrusive even if it isn't. Happy to discuss further if there's an application for this feature that I'm missing.
