### ISSUE TITLE
Allow Browsers to be Chosen/Configured & Re-ordered

### ISSUE THREAD

**Issue by stgarf** [will-stone/browserosaurus#191]
I previously used another tool that no longer works properly on macOS Catalina, [MultiBrowser](https://sites.google.com/site/tesseractsoftware/multibrowser), and that tool allows you to both configure all your desired browsers (e.g. I can send links to iTerm for instance) and also allows you to choose the desired order they show up in. This would be a nice feature to have in browserosaurus.

e.g.:
![Screen Shot 2020-04-15 at 14 34 17](https://user-images.githubusercontent.com/1694002/79391497-88461300-7f26-11ea-93f8-e674028c0a9e.png)

**Comment by will-stone** [comment]
I don't think this will have much benefit for the effort required to code it; more settings means more code to maintain and check when changes are made. If you'd like to disable B finding browsers on your system, there is a hidden feature where you can create a `.browserosaurus.json` in your home directory and fill it for example like so:

```json
{
  "ignored": [
    "Brave",
    "Brave Beta",
    "Brave Dev",
    "Chromium",
    "Cliqz",
    "Firefox Developer Edition",
    "Firefox Nightly",
    "Google Chrome Canary",
    "Iridium",
    "Maxthon",
    "Microsoft Edge Beta",
    "Microsoft Edge Canary",
    "Microsoft Edge Dev",
    "Min",
    "Opera",
    "Opera Beta",
    "Opera Developer",
    "Polypane",
    "qutebrowser",
    "Safari Technology Preview",
    "Tor Browser",
    "Vivaldi",
    "Yandex"
  ]
}
```

**Comment by stgarf** [comment]
I guess then I can tell it to send URLs to iTerm? 

For instance sometimes there are hostnames in Slack or whatever that I want to click on to start an SSH session to in iTerm.

**Comment by will-stone** [comment]
Non-browsers are not currently supported. The upcoming release (a long way off) may support plugins so you'd be able to add this functionality yourself (no promises though 😄). I'd say for now, it's best to `cmd-c` to copy-to-clipboard and paste into iTerm.

**Comment by ihorvorotnov** [comment]
> If you'd like to disable B finding browsers on your system, there is a hidden feature where you can create a `.browserosaurus.json` in your home directory

Oh, that would be nice! However, it doesn't work for some reason – created a file, added couple browsers I'd like to ignore, reloaded the app – no changes, all 6 browsers are still shown. Am I doing smth wrong?

Contents of `~/.browserosaurus.json`
```
{
  "ignored": [
    "Firefox",
    "Opera",
    "Safari Technology Preview"
  ]
}
```

The app:
<img width="912" alt="Screenshot 2020-06-17 at 14 53 42" src="https://user-images.githubusercontent.com/1066083/84894958-5843f900-b0aa-11ea-9dab-9325f2572dba.png">

Thanks!

**Comment by will-stone** [comment]
@ihorvorotnov You're not doing anything wrong. The `.browserosaurus.json` file was never an official feature and it didn't make it into the new v10 rewrite. I'll reopen this as I think hiding browsers could be useful.

**Comment by ihorvorotnov** [comment]
Makes sense now. Yes, this feature is nice to have. Thanks for reconsidering.

**Comment by will-stone** [comment]
The ability to hide browser tiles will be in the next release. Note this does not include reordering as that's not relevant with v10: the window is shown in the centre of the screen rather than relative to the mouse.

**Comment by jovobe** [comment]
@will-stone can you confirm this was working with some version after v10? I tested it today and with 17.2.0 it's not working.

**Comment by will-stone** [comment]
@jovobe Are you talking about hiding apps? If so, please see v16 release notes: https://github.com/will-stone/browserosaurus/releases/tag/v16.0.6
