### ISSUE TITLE
Option+Click to Bypass Browser Selection & Use ⭐️

### ISSUE THREAD

**Issue by stgarf** [will-stone/browserosaurus#192]
(sorry for all the features/issues @will-stone I just had a coffee -- great work, your tool is so far a mostly seamless replacement thanks!)

I would like that ability to bypass the choosing of a browser with something like `Option+Click` to bypass the chooser UI and go straight to using the ⭐️ favorite browser.

**Comment by will-stone** [comment]
No worries. Thanks for all the input. Please do search issues though, I think I've had this one before (although it might be buried in another request). My stance on these sorts of things is that I like B to open every time -> predictable functionality. By that I mean, you'd either forget to hold alt before clicking, or you'd get into the habit of it and do it all the time by accident. It's far better, in my opinion, to know that every link opens B and you can just slam down on the spacebar to open your favourite browser.

The other issue is that I don't think this would be possible. By the time B has focus, it doesn't know you originally clicked using a modifier key.
