### ISSUE TITLE
autoplay of links

### ISSUE THREAD

**Issue by 5knnbdwm** [will-stone/browserosaurus#193]
**Describe the bug**
Hey, so some days ago I upgraded to version 9.3.0. I really liked it cuz it removed some bugs that I previously had. And I think that the feature I'm talking about got introduced in this update, the ability to open links with browserosaurus from spotlight.

And although I kinda get why people would like it. But when copying a youtube link and highlighting it starts playing the video. Which in itself can potentially be quite a danger (running js), don't know how exactly it is implemented so won't say too much there. 

But videos also continue to play when closing spotlight again. Which well is even worse. In addition to that spotlight/browserosaurus will continue to load videos when the link was the last selected thing and start playing them in the background. Stopping them is only possible when opening spotlight again with the link still there and either pressing escape until spotlight closes or selecting a different item in the list.

All can be seen in the video: [https://imgur.com/a/Z4bF04J](https://imgur.com/a/Z4bF04J)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'youtube'
2. Copy a link to a video
3. Open spotlight, paste the link into spotlight
4. Wait until the website is loaded
5. Close spotlight via shortcut or by clicking anywhere outside of spotlight

**Expected behaviour**
Well that links aren't just loaded and run. Preferably that it only shows browserosaurus as an app that can open the link. But then opens browserosaurus and lets the user decide where to open the link.

**Screenshots**
[https://imgur.com/a/Z4bF04J](https://imgur.com/a/Z4bF04J)

**Desktop (please complete the following information):**
 - OS: 10.15.4
 - Version 9.3.0

**Comment by 5knnbdwm** [comment]
And yes, I know my OS version is above the currently supported version. But I believe that the feature affects the currently supported version as well.

**Comment by will-stone** [comment]
I did not even know Spotlight could do this. That's not B. Try setting Safari as your default browser and repeat your steps, you'll get the same issue, therefore you've found an OS bug 🙃
