### ISSUE TITLE
v9.3 is not showing Safari as an option

### ISSUE THREAD

**Issue by catarino** [will-stone/browserosaurus#195]
**Browserosaurus is not showing Safari as an option as of v9.3**

**Steps to reproduce the behaviour:**
1. Click on a link to select browser or go to Menubar to select preferred Browser
2. See error

**Expected behaviour:**
Floating popup and menubar preferences should show Safari as an option

![Uploading 
<img width="302" alt="Screenshot 2020-04-25 at 12 02 50" src="https://user-images.githubusercontent.com/609172/80278363-9269cd80-86ed-11ea-8f5a-05b0df563083.png">
<img width="216" alt="Screenshot 2020-04-25 at 12 06 03" src="https://user-images.githubusercontent.com/609172/80278365-939afa80-86ed-11ea-87c3-ce1a604a6e69.png">

**Desktop (please complete the following information):**
 - OS: 10.14.6
 - Version  (18G4032)

**Comment by will-stone** [comment]
Hi. Can you please run `mdfind 'kMDItemContentType == "com.apple.application-bundle" && kMDItemCFBundleIdentifier == "com.apple.Safari"'` in the Terminal. You should get something like `/Applications/Safari.app`

**Comment by catarino** [comment]
Hi @will-stone here's a screenshot: 
<img width="712" alt="Screenshot 2020-04-25 at 16 28 40" src="https://user-images.githubusercontent.com/609172/80283746-01f1b400-8712-11ea-91c3-9a813ceafae8.png">

It's not showing what's supposed to show, I guess.

**Comment by will-stone** [comment]
That is odd. It's like Safari isn't even installed on you Mac. It could be a Spotlight indexing issue, have you restarted your machine? The try going to System Prefs > Spotlight and unticking Applications and then ticking it again. And ensure Safari is definitely in your Applications directory. Please bear in mind that you are running an unsupported version of macOS.

**Comment by catarino** [comment]
> That is odd. It's like Safari isn't even installed on you Mac. 
Yeah, It is.

> It could be a Spotlight indexing issue, have you restarted your machine?
I did restart several times, for unrelated reasons. But I can confirm that Spotlight is behaving strangely lately, doing several reindexes


> The try going to System Prefs > Spotlight and unticking Applications and then ticking it again. 
I will. 

>And ensure Safari is definitely in your Applications directory. 
This I can confirm. I have never moved it. I (actually thought that it wasn't even possible. :) )


> Please bear in mind that you are running an unsupported version of macOS.
Well, it's the last from Mojave, I didn't know it was "unsupported". 

I will feedback on point 3 when I can.

Thanks for the quick reply.

**Comment by will-stone** [comment]
> Well, it's the last from Mojave, I didn't know it was "unsupported".

Alas, I only have one Mac to test on and I usually stay up to date with current releases.

Hopefully it's just a Spotlight issue. Others have experienced similar issues.

**Comment by catarino** [comment]
Yeah, I’m suspecting it is Spotlight. I’ll update on progress.

Thx

**Comment by will-stone** [comment]
I'm guessing this is no longer an issue. Please reopen if Safari is still not showing.
