### ISSUE TITLE
feature request: auto opened dev tools per browser or hotkey (favorite) 

### ISSUE THREAD

**Issue by cocoonkid** [will-stone/browserosaurus#196]
source : https://addyosmani.com/blog/automatically-open-chrome-devtools-in-each-new-tab/

**Comment by will-stone** [comment]
Interesting. What's your use case? Here's my initial thoughts:
1. Not a fan of browser-specific code.
2. Is the effort involved in adding and testing (on each new release) this feature really worth the effort to save the flow of: open browser > hit `cmd-alt-i` ?
3. Looks like it's a launch flag, so you wouldn't be able to pick and choose which links open with dev tools (once Chrome has opened with this flag, all tabs open with dev tools): this UX could be really hard to portray.
4. Could it actually get annoying?

**Comment by will-stone** [comment]
Oops, accidentally hit submit. Essentially I was gonna sign-off with that I think 3 would be the greatest issue.

**Comment by cocoonkid** [comment]
Makes sense. Thank you for commenting!
