### ISSUE TITLE
feature request: Resize Icons

### ISSUE THREAD

**Issue by cocoonkid** [will-stone/browserosaurus#197]
Feature request: option to Resize Icons

They are really too big IMHO.

Allow to choose the precise size or just offer 2 or 3 different sizes.

**Comment by will-stone** [comment]
Out of interest, how many browsers do you have?

**Comment by cocoonkid** [comment]
5- Firefox Dev Edition, Firefox, Chrome, Brave & Blisk :-)
And indeed every Browser is for its specific things.
(I'm a massive ADD head so I need all these compartments).

**Comment by will-stone** [comment]
Oh, I cannot imagine 5 is too much space. I wanted them to be easy targets to hit with a mouse.

Anyway, I highly doubt I'll include this in v9 unless my grand plans for v10 (no release date planned) don't work out. I'll keep this open for now though as it may be relevant in the future version.

**Comment by cocoonkid** [comment]
Awesome! Looking forward to it.

**Comment by will-stone** [comment]
Thanks! v10 should look better; 7 browsers will be two rows of 4 and 3.

**Comment by will-stone** [comment]
Are you happy with the sizes of everything in v10?

Changing the sizes of icons has a knock-on effect on window size, which must be calculated from the size of the tiles (icons), therefore I think I'd rather keep everything as is for the time being. I may put in options for more customisation of window size later on. Happy to see any designs you'd like share if you have thoughts on this.

**Comment by cocoonkid** [comment]
Yes, looks better. Still, too big for me but I guess I am just too minimalistic in my personal taste! Great job anyways!

**Comment by cocoonkid** [comment]
Okay, the new, new look is tops!

**Comment by will-stone** [comment]
Thanks @cocoonkid! I really appreciate the compliment (and the sponsorship 😄).
