### ISSUE TITLE
Feature Request: color picker?

### ISSUE THREAD

**Issue by idontlie** [will-stone/browserosaurus#199]
Thanks for the great software. It would be cool if the user could choose what color the UI is and modify the transparency in some sort of preferences pane.

**Comment by will-stone** [comment]
Colours are delicate balances but I'm not adverse to this, maybe only a dark/light variant to begin with. v10 will be released soon which will afford me more options for things like this. I will add you to the alpha testing list once it's ready (next few days or so... hopefully).

**Comment by will-stone** [comment]
A theme picker will be in the next release. It'll have a small selection to begin with but will provide an alternative for those that don't like the dark theme, or would simply like a change.
