### ISSUE TITLE
How can I add a new browser to Browserosaurus?

### ISSUE THREAD

**Issue by DeviatedMind** [will-stone/browserosaurus#2]
When I click on the app icon in menubar, there is only "About" and "Quit".
There can be "Preferences" or "List of Browsers" or "Application Folders".

**Comment by will-stone** [comment]
Hi @DeviatedMind, sorry I'm not sure how I missed this issue. Browserosaurus scans the system for browsers and shows those that are installed _and_ on the whitelist (https://github.com/will-stone/browserosaurus/blob/master/src/browsers.js). Which browser would you like added? Please note, if you add a browser after running Browserosaurus, you will need to restart the Browserosaurus app by selecting "Quit" from the menubar menu, then running the app again.

**Comment by DeviatedMind** [comment]
It does not show Iridium browser.
https://alternativeto.net/software/iridium/

**Comment by mliq** [comment]
Does not show Chrome Canary

**Comment by will-stone** [comment]
Canary and Iridium now in v1.0.3 https://github.com/will-stone/browserosaurus/releases/download/v1.0.3/Browserosaurus-darwin-x64-1.0.3.zip

**Comment by DeviatedMind** [comment]
Thanks, why don't you add the ability to add and remove apps manually?

**Comment by DeviatedMind** [comment]
Some people need the "null" option because the apps they use every day open browser against their will.
There can be just a bling in menu bar when .html files are opened. When "null" option is checked in preferences.

**Comment by will-stone** [comment]
Hmmm... you are welcome to give it a go. I spent quite a while trying to figure out how to do it but eventually went with what I felt was the best solution:

- Reads Spotlight's list of all recognised apps
- Reduce the array to the list of browsers (using a white list)

This means finding the registered name and adding logos manually, but eventually we'll cover most people's use cases.

How would you apporach this?

As for "null", just hit escape or click outslide the window. I'll add more documentation to the site in time.

**Comment by DeviatedMind** [comment]
I'm not a programmer yet, but I can tell you good user stories, and this is my first real commit which changes something that works in the real world so I'm really excited.
For manually adding and removing apps maybe you can use "Open With" option in right click menu.
(If I could, I would definitely commit some code for you. Unfortunately I don't have the knowledge 'yet'.)

**Comment by will-stone** [comment]
Maybe in a future version. For the time being, I quite like the simplicity of the current mechanism. Don’t worry about not being able to code; logging issues is a great help, and you can always write and submit docs if you feel inclined.
