### ISSUE TITLE
Hotkeys don't respect keyboard layout

### ISSUE THREAD

**Issue by novemberborn** [will-stone/browserosaurus#202]
**Describe the bug**

I have Chrome set up with the `g` hotkey. However it doesn't open when I press `g`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select the Dvorak keyboard layout
2. Click on a link to trigger Browserosaurus
3. Press the physical `u` key on the keyboard, which maps to `g`
4. Nothing happens
5. Press the physical `g` key on the keyboard (which maps to `i`)
6. Chrome opens the link

**Expected behaviour**
The hotkey should trigger based on the keyboard layout, not the physical key.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Version 10.1.0

**Comment by will-stone** [comment]
Interesting. Could you please press your Dvorak "g" key on this site and paste a screenshot of the result? https://keycode.info/

Thanks.

**Comment by novemberborn** [comment]
Yup, here you go:

<img width="742" alt="Screen Shot 2020-06-05 at 16 15 12" src="https://user-images.githubusercontent.com/33538/83886738-c8b45700-a747-11ea-8c36-9ed2609be1f6.png">

**Comment by will-stone** [comment]
Interesting. Okay, well I've been using the `event.code` (so I didn't have to worry about case) but I'll obviously have to look into `event.key`. Thanks.

**Comment by novemberborn** [comment]
That makes sense. Thanks for your work on Browserosaurus!

**Comment by novemberborn** [comment]
Works great, thanks @will-stone!

**Comment by will-stone** [comment]
Awesome! Thanks for confirming the fix.
