### ISSUE TITLE
Allow rule-based browser selection

### ISSUE THREAD

**Issue by fberzau** [will-stone/browserosaurus#204]
My use-case is actually fairly simple. I use Safari. Except for very few exceptions, where it doesn't work. Like a handful of URLs. Then it's Chrome. And one site needs Firefox. So instead of having to confirm the default browser for each click, it would be great if I could just simply entere a few rules, and Browserosaurus would take me straight to the browser. Rules could be like:
google.com:chrome
gmail.com:chrome
otherurl.com:firefox
*:safari
In terms of wildcard support, similar syntax like for example FoxyProxy for be suitable.

**Comment by will-stone** [comment]
Thanks. Duplicate #203 #183 #113 #53 #32

Firstly, thanks for using Browserosaurus. As you can tell from the amount of closed issues regarding this, I will not be supporting this and it is out of scope for Browserosaurus. I suggest something like [Choosy](https://www.choosyosx.com/). You can even use them in tandem, set Choosy as the default and point its rules at Browserosaurus.
