### ISSUE TITLE
Feature request: Disable history

### ISSUE THREAD

**Issue by eatstorming** [will-stone/browserosaurus#205]
I stumbled upon Browserosaurus today while updating Homebrew and it's an excellent piece of software, thank you.

I'd like to request the option to disable saving history, though. Most if not all browsers can do this, I think it's the only step backwards with Browserosaurus that you'd have a history in it that apparently, so far you cannot disable. I also checked and found that it saves it in store.json, along with other settings.. So the simple hack of turning that file immutable would cause more inconveniences.

Could there be a toggle to disable it, please? Yes, I know there is a button to clear the history but I'd prefer to just disable that altogether instead.

Thank you.

**Comment by will-stone** [comment]
The use case for it was if you closed B and didn't act on the URL (so it wouldn't be in Browser history), and to quickly check on a recent links if you couldn't remember which browser you opened it with. So if it's a privacy thing, does knowing that it will only keep the last 10 URLs in the store help?

I don't think making that file immutable would be wise as I will be using it store all sorts of upcoming features' info. Can you please explain why/how you would do that?

**Comment by eatstorming** [comment]
Yeah, when I saw settings in it I realized making it immutable would be a bad idea. My first thought was to clear the history in B and then chmod 0 store.json to prevent it from being changed. But as I said, that would cause issues.

Knowing that it has a limit helps slightly (I knew already, I played a lot with B today), but it's still not ideal in my opinion. I understand the use case for it, but I think it's not always necessary.

**Comment by will-stone** [comment]
Sorry to pester, but I must know to fully understand, why would you want it immutable? Are you hoping to sync settings with other macs?

**Comment by eatstorming** [comment]
No, I don't want it immutable. That was just an idea I had when I could not find a setting to disable saving history. But when I saw the other settings in the file, I concluded the idea would not work.

**Comment by will-stone** [comment]
Ah, gotcha. So it's just a privacy thing?

**Comment by eatstorming** [comment]
Yeah. My specific case is censorship (I'd rather not go into detail here at least, but I can provide more non-publicly if needed).

**Comment by will-stone** [comment]
Sure, I would certainly like to understand the priority/severity of keeping a history. I mean, the more I think about it, the less I like knowing that it's stored in plain text for anyone to scrape. Send me an email and we can discuss: email@wstone.io

**Comment by will-stone** [comment]
No more history in v10.3.0
