### ISSUE TITLE
Time to remove Cliqz browser from B :(

### ISSUE THREAD

**Issue by mindfulsource** [will-stone/browserosaurus#206]
Hi Will! v10 is fantastic, great job! The launch speed bump is a big improvement!

As the person who lobbied to add [Cliqz](https://cliqz.com/en/desktop) to B, sadly now I am asking it to be removed. Why: [It's shut down.](https://cliqz.com/en/magazine/farewell-from-cliqz)

It's sad, because we need more browsers based on Firefox in the ecosystem. This was the only modern one for Mac (apart from Tor), and now it's gone. :(

However, turns out Cliqz was a spying machine anyway. Oops: https://news.ycombinator.com/item?id=23031520 Good riddance perhaps.

I suggest to remove Cliqz from B mostly because the browser itself is becoming unstable. It suddenly lost all my extensions and browser settings overnight so is clearly fast becoming necroware. (...For lack of a better, erm, term.)

I'll now be using Firefox Developer as my 'other firefox', which is already in B. :)

**Comment by will-stone** [comment]
Ah, okay. Thanks for the heads up; I’ll remove it from the next release.
