### ISSUE TITLE
Help: How do I unlock the url bar when using the menu bar icon

### ISSUE THREAD

**Issue by hobo313** [will-stone/browserosaurus#207]
The feature where yo can paste a link into the url option when clicking on the menu bar icon is locked for me. I do not see any preferences or how I can unlock this. Can anyone please help?

**Comment by will-stone** [comment]
That's not an option but I'm interested that you think it is, from a UX perspective 🤔 Firstly, can you tell me _why_ you want to paste a URL into Browserosaurus?

**Comment by hobo313** [comment]
Oh, sorry. I just assumed that it was since the url bar has a lock icon next to it. And I would like to be able to do this for instances such as if I'm already in a browser, and there is a link that I am attempting to open in another browser, it would make it simpler to just paste that link in the url bar rather than opening the browser than pasting the link. I use safari for mainly all my use, but safari does not support 4k video on YouTube. Which I switch to google chrome for. So I would like to be able to just copy a link in safari, click the menu bar for browserosaurus, paste the link, then chose the browser I would like to open the link in.

P.S:
Absolutely loving the app and the functionality behind it so far. Thank you.

**Comment by will-stone** [comment]
Okay, I see. I don't think Browserosaurus would really provide much benefit here over hitting <kbd>cmd-space</kbd> (for Spotlight), type "chr...", hit <kbd>enter</kbd>, then pasting into the browser directly. Therefore I'm going to close this unless a suitable case can be raised for Browserosaurus to have URLs pasted into it.

Thanks for using B 😄

**Comment by will-stone** [comment]
PS, the lock icon is to denote it is an "httpS" link. If this isn't obvious, which it seems it isn't, please raise a separate issue for this using the feature request template. Thanks.

**Comment by will-stone** [comment]
I've removed the lock icon from the next release; I think keeping the protocol text is easier to scan and just because something is https doesn't necessarily mean it's a trusted website.

<img width="912" alt="image" src="https://user-images.githubusercontent.com/654103/83974108-b28ece00-a8e2-11ea-8011-8bbc7b8afc48.png">
