### ISSUE TITLE
use Browserosaurus as an app launcher

### ISSUE THREAD

**Issue by long-lazuli** [will-stone/browserosaurus#208]
Hi Will !

I'm using several browsers on a daily basis, for testing my work (web related).

I'd like to be able to click on the icon of browserosaurus, or Cmd+Space it to open the main windows, to allow to launch/tab to the browser of my choice.

I think the window would look quite the same, with the url-field empty...

**Comment by will-stone** [comment]
Hi. Thanks for using B. Becoming a full app launcher is out of scope for this project, it's way too much work and Spotlight/Alfred has that covered. I've thought about this before, and I will probably add a button and map backspace ⌫ to remove the URL. However, please keep in mind that if you've already got as far as opening Spotlight/Alfred, you're better off then typing the name of the browser you want. 

1. <kbd>cmd + space</kbd> Open Spotlight
2. Type "Brow..."
3. <kbd>enter</kbd>
4. Select browser with keyboard shortcut / mouse

vs.

1. <kbd>cmd + space</kbd> Open Spotlight
2. Type "Chro..."
3. <kbd>enter</kbd>
