### ISSUE TITLE
Cannot show shortcut letter 

### ISSUE THREAD

**Issue by isyara** [will-stone/browserosaurus#210]
Hi,

I use v9.3.0 and i have Firefox developer Edition but when dialog of app is open to choose browser i can't see letter of Firefox Developer Edition.

<img width="591" alt="Capture d’écran 2020-06-11 à 10 24 57" src="https://user-images.githubusercontent.com/2648791/84363076-bb6ef080-abbd-11ea-952a-6084aaf4f6bb.png">

Thanks for your app , i like it everyday

**Comment by will-stone** [comment]
Thanks for using Browserosaurus, however please consider upgrading to v10 as v9 is no longer supported. With v10 you can set your own hotkeys. In v9, only stable versions of browsers have hotkeys; Firefox dev edition is essentially the nightly/weekly channel.

**Comment by isyara** [comment]
Great  👍🏻
