### ISSUE TITLE
Add OPEN IN BACKGROUND option

### ISSUE THREAD

**Issue by themacguru** [will-stone/browserosaurus#212]
I like to go through emails, rss feeds, etc. and open a bunch of tabs in the background instead of bringing focus to the browser. 

That one missing feature makes Browserosaurus unusable (though needed as some sites don't run on certain browsers).

**Comment by will-stone** [comment]
Thanks for using Browserosaurus.

https://github.com/will-stone/browserosaurus/issues/161
https://github.com/will-stone/browserosaurus/issues/142
https://github.com/will-stone/browserosaurus/issues/54
