### ISSUE TITLE
Option to Turn Browserosaurus Off in menubar

### ISSUE THREAD

**Issue by themacguru** [will-stone/browserosaurus#213]
Following on my other background request - If I could turn the activity off when I'm using emails/rss for now, then that'd be good in the short term. Right now I have to change the default browser back and forth to accomplish this. Maybe that's the toggle in the menu bar item?

**Comment by will-stone** [comment]
Hmmm, Browserosaurus is either set as the default browser or it's not. As I've answered your background request, I think there is no need to find a solution for this.
