### ISSUE TITLE
Add Vivaldi Snapshot

### ISSUE THREAD

**Issue by 16patsle** [will-stone/browserosaurus#214]
**Browser Name**
Vivaldi Snapshot

**Link to browser's webpage**
https://vivaldi.com/blog/snapshots/desktop/side-by-side-installation-of-vivaldi-on-macos-vivaldi-browser-snapshot-1950-3/

Vivaldi now uses separate app names and profile paths for stable, Snapshot and Internal, so only the stable version is detected by Browserosaurus. The Snapshot version (and technically also the Internal version) therefore need whitelisting.

**Comment by 16patsle** [comment]
The other versions have a suffix of .snapshot or .internal on the stable bundle ID.

**Comment by will-stone** [comment]
Thanks. To confirm, the bundle ID for Snapshot is `com.vivaldi.Vivaldi.snapshot`? I cannot find download links for "internal" and the name would suggest this is a browser that is not available to the public.

**Comment by 16patsle** [comment]
That's the correct bundle ID yes. Internal builds are usually not distributed no, so while it could be useful to support those to, its probably best to just do the snapshot.
