### ISSUE TITLE
Browser icons can be dragged off chooser window

### ISSUE THREAD

**Issue by i0ntempest** [will-stone/browserosaurus#216]
**Describe the bug**
In the browser chooser window, icons can be dragged off and saved as a png/svg file if dragged into a Finder window.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click a link
2. In the chooser window drag an icon off the window
3. Drag the icon to a folder, the icon is saved as a file

**Expected behaviour**
Icons shouldn't be "draggable"

**Screenshots**
![Screen Shot 2020-06-19 at 02 29 40](https://user-images.githubusercontent.com/16017904/85103520-d997aa80-b1d4-11ea-8288-9e72dba1c5e5.png)
(Mouse cursor isn't shown)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Version 10.6.0

**Comment by will-stone** [comment]
Thank you. This will be fixed in the next release.

**Comment by i0ntempest** [comment]
@will-stone I just noticed this has reappeared in the newest version, not sure about older versions though.

**Comment by will-stone** [comment]
Ah, thanks. Looks like I removed the CSS that stops this.
