### ISSUE TITLE
Started in v10.9.0...double-prompts and truncated webpage URL

### ISSUE THREAD

**Issue by fsmertz** [will-stone/browserosaurus#218]
I click on the link in my email (Apple Mail Gmail Account), and Browserosaurus prompts for browser choice.
I select Chrome, and Browseorsaurus again prompts for browser choice.
I select Chrome again, and it sends me to Chrome but I get this error: No URL found for this tracker ID
It's truncating the link. Happens no matter what browser I choose.

Link in email:
https://citywinery.us13.list-manage.com/track/click?u=61be74065ff8179e3a90afcc6&id=65dd3bfcda&e=6bcce8086f

Link after it goes through browserosaurus:
https://citywinery.us13.list-manage.com/track/click?u=61be74065ff8179e3a90afcc6

 - OS: 10.15.5
 - Version 10.9.0

**Comment by will-stone** [comment]
Thank you. I’ll try to fix this ASAP.

**Comment by will-stone** [comment]
Nice. You actually found a potential security issue! When you open a browser with B, it runs the `open` command. So in your case it tried to run the following (altered for easier reading):

```bash
open https://example.com?aaa=111&bbb=222&ccc=333 -b com.google.Chrome
```

However, ampersands are special characters in unix and so it was really running:

```bash
open https://example.com?aaa=111 & bbb=222 & ccc=333 # and then it probably crapped out after that
```

I've added a couple of safe guards in and essentially it now quotes the url to _contain_ it:

```bash
open "https://example.com?aaa=111&bbb=222&ccc=333" -b com.google.Chrome
```

**Comment by will-stone** [comment]
This will be released later today.
