### ISSUE TITLE
New Update not working properly

### ISSUE THREAD

**Issue by dmorizz** [will-stone/browserosaurus#220]
I'm not sure what's happened with the new update. When I click on a link I have to do it/use the space bar twice. Then it goes to a page where I need to click the link again to see the page.
https://a.cl.ly/ApuA9QDl

Or a link says, "No URL found for this tracker ID".
https://a.cl.ly/NQugYRow

I love this app as it's fast and convenient, but now it doesn't seem to work.

**Comment by will-stone** [comment]
Which version are you using?

**Comment by will-stone** [comment]
Ah, sorry, hadn't watched the video. It's fixed in 10.9.1 see #218 
Please click the reload button and wait for the new version to download.
