### ISSUE TITLE
Double-encoded URI components

### ISSUE THREAD

**Issue by novemberborn** [will-stone/browserosaurus#226]
https://github.com/will-stone/browserosaurus/commit/6d24de336b79460a381d5a0832a82f5643844b27

This encodes URI components twice:

`https://accounts.google.com/o/oauth2/auth?redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F` becomes:

`https://accounts.google.com/o/oauth2/auth?redirect_uri=http%253A%252F%252Flocalhost%253A8085%252F`

Version 10.9.1.

I think you should just replace quotes with the encoded value.

I haven't looked elsewhere in the code but it seems like you're invoking `open` in a shell? IIRC with Node (not sure about Electron) you can run a program directly and safely pass arguments.

**Comment by will-stone** [comment]
Yeah, I added the `encodeURI` option escape anything nasty but I suppose I could just `.replace('"','')` to ensure nobody is terminating the string to attack.

As for `run a program directly`, can you please give an example command/code? Thanks.

**Comment by novemberborn** [comment]
> As for "run a program directly", can you please give an example command/code? Thanks.

See https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback

I don't know if that's available in Electron.

**Comment by will-stone** [comment]
Ah okay, thanks. I've found the method of using the app bundle id has been very easy to maintain as we don't need to know the path to a browser's app file or know its CLI command (if it has one).

**Comment by novemberborn** [comment]
Yes but you could execute `/usr/bin/open` this way.

**Comment by will-stone** [comment]
I see... kinda. So `child_process.execFile('open', ['http://eample.com', '-b', 'org.mozilla.firefox'])` seems to work when I try it in node's REPL (not tried it in app yet). And this is safer?

**Comment by novemberborn** [comment]
Yes. As long as you don't enable the `shell` option it correctly handles "shell metacharacters".

**Comment by will-stone** [comment]
Okay, thanks! I'll give that a go later; I thought rolling my own sanitisation was a bit weird.
