### ISSUE TITLE
JavaScript error when Internet connection is unavailable

### ISSUE THREAD

**Issue by ArashNrIm** [will-stone/browserosaurus#227]
Hello there!

First off, thanks so much for putting your efforts in the curation of this tool; I found it especially helpful in separating links to open in different browsers (for schoolwork and personal respectively). I've been encountering an issue, albeit minor, that appears.

**Describe the bug**
Most times when starting my Mac, either when there's no WiFi connection or macOS takes a slower time to connect to an internet connection, this error appears:
<img width="420" alt="Screenshot 2020-06-26 at 6 58 38 AM" src="https://user-images.githubusercontent.com/47273556/85803978-ff93f080-b77a-11ea-9116-4bd4e775c4b6.png">

**To Reproduce**
I'm not clear on why the error was caused, but it appears whenever WiFi isn't available. It happens during boot (after signing in, probably it's because macOS takes time to connect to a WiFi connection) or starting it with WiFi off/disconnected.

Steps to reproduce the behaviour:
1. Quit Browserosaurus if open.
2. Turn WiFi off.
3. Open Browserosaurus again.
4. See the error.

**Expected behaviour**
I had expected no error to appear.

**Desktop:**
 - OS: macOS 10.15.5
 - Version 10.9.1

Hope this helps!

**Comment by ArashNrIm** [comment]
I noticed that there was a newer version of Browserosaurus, version 10.9.2. I've updated the app on my end and this error still persists in this update; just to take note!

**Comment by will-stone** [comment]
This again 🙄 This is due to the Electron autoupdater; it’s the only thing that tries to connect to the internet. Thanks for reporting it, I’ll go back through the issues and see what I did to fix this last time, I must have removed the fix in the great rewrite to v10.

**Comment by will-stone** [comment]
Fixed in v10.9.3
