### ISSUE TITLE
Backspace deletes URL bits by bits separated by symbols eg. #, ?, /, &

### ISSUE THREAD

**Issue by i0ntempest** [will-stone/browserosaurus#228]
**Is your feature request related to a problem? Please describe.**
When I get a URL with unneeded/tracking stuff behind it I always need to delete them manually, like those:
https://twitter.com/cbr6w/status/1276790235070738433?s=21 works just fine without "?s=21"
https://trac.macports.org/ticket/60723#comment:8 leads you to the 8th comment of the thread
https://www.youtube.com/watch?v=7dyN-SwP4Gc&list=LL8GOKg9UHbpkGylP5KDggUQ&index=2&t=0s has playlist, index and time info append to it and is not always needed
http://btedn.azv.k7nk3.cn/GXPS8QYX?spss=1&from=timeline random URL copied from WeChat, with tracking

**Describe the solution you'd like**
The idea is an enhancement of the already-implemented feature. Instead of deleting everything after the main website URL when hitting backspace, separate the URL with common separators like #, ?, /, &, and each backspace hit delete one part.

**Comment by will-stone** [comment]
Nice! This shouldn't be too difficult to add to [the helper](https://github.com/will-stone/browserosaurus/blob/622c2b88140037328852a2b48f97bba6735417e5/src/utils/backspaceUrlParse.ts#L8).
