### ISSUE TITLE
Space to copy URL

### ISSUE THREAD

**Issue by overclockedllama** [will-stone/browserosaurus#234]
Hi, 

Firstly, this is an amazing app, thank you so much for developing it.

You used to have it so that I could map space to copy to clipboard, but in the past few releases, you have removed this functionality. Is there a reason for this? Would it be possible to reintroduce this functionality?

**Comment by will-stone** [comment]
Hi. Thanks for using Browserosaurus.

Hmmm 🤔 Some thoughts:

- <kbd>cmd+c</kbd> is the OS/app-agnostic keyboard shortcut for copy-to-clipboard and makes sense to use it here.
- <kbd>cmd+c</kbd> should be muscle memory for everyone by now.
- <kbd>cmd+c</kbd> are very close to the space bar, are you really saving anything?
- The space bar is the favourite key and should be used for your most used action. If copying is the thing you do the most, why? Where do you paste to? Is it into browsers? If so, I know of a great app that can save you the time 😆 

Happy to discuss use cases.

**Comment by overclockedllama** [comment]
firstly, LOOOOOOOOOOOL

secondly, there are many cases in which I want to copy the URL:
 - so I can paste it in an incognito tab of an aforementioned browser. 
 - If I need to paste it into VSCode
 - If I need to  paste it into a word document/note
 - If I need to paste it into a message conversation

I think it is a lot easier than command c because it requires less keystrokes, and I like the ability to have _ALL_ my browsers one keystroke away, and I think it would be cool to have copy one key away as well. I hope it wouldnt be too much trouble to add back the ability to map it to space

**Comment by will-stone** [comment]
Incognito mode is something that has been [discussed before](https://github.com/will-stone/browserosaurus/issues/174) and maybe worth seeing if there's a way to help out there.

Copying is a special case, separate from the apps' config, and would require conditionals to support it. I really don't think adding Copy as favourite, when it already has a dedicated shortcut that is well known, fits well with the UX of the rest of Browserosaurus. Therefore, I'm gonna mark as wont-fix but I happy to see and help out on a PR if you'd like a crack at it.

Thanks for using Browserosaurus, and for a being a fan long enough to remember when Copy used to be at the same level as the browsers 😄
