### ISSUE TITLE
Sortable browsers in preferences

### ISSUE THREAD

**Issue by will-stone** [will-stone/browserosaurus#24]
@Jackymancs4 I've started off the sorting functionality. For some reason I can't get it to save down into the store, or persist in any way. Do you mind taking a look? https://github.com/will-stone/browserosaurus/tree/sortable

**Comment by Jackymancs4** [comment]
The main problem was that installedBrowsers was generated looping through the system_profiler response, that indeed is sorted.

**Comment by will-stone** [comment]
Awesome! Thanks, I'll take a look at that later. Are you happy with how the sorting works? Any suggestions? I'll probably add in handles, as per your mock-up, just so it's obvious the browsers can be dragged.

**Comment by Jackymancs4** [comment]
I love it! Great job. Yeah, the handles may prove useful to make the whole drag&drop more intuitive.
My only note (that took me awhile to figure it out):
The Swap array thing don't seem to be the best for the UI.
[1,2,3,4,5]. I grab 5 and put it in 2, I would expect to just drop it here, keeping the rest in the same order like [1,5,2,3,4], instead I get [1,5,3,4,2]. This way is very complicate to get the order I want.

**Comment by will-stone** [comment]
Ah yes that makes sense. Feel free to change that logic. I simply looked up a swap function. However I only had three browsers installed at the time so didn't notice that bug.

**Comment by will-stone** [comment]
Released in v1.3.0
