### ISSUE TITLE
Add new Safari icon

### ISSUE THREAD

**Issue by gottabeleGIT** [will-stone/browserosaurus#242]
**EDIT:** I just realized that the logos are managed by another project, so I'd best open an issue with them then, yeah?

**EDIT 2:** Looks like it's been taken care of: alrra/browser-logos#184
#
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Could you consider changing the Safari and Safari Technology Preview icons to match the Big Sur redesign?
![Screen Shot 2020-07-08 at 4 56 43 PM](https://user-images.githubusercontent.com/21181118/86974574-333c2680-c13c-11ea-8a27-9b4eca043749.jpg)
![Screen Shot 2020-07-08 at 4 55 48 PM](https://user-images.githubusercontent.com/21181118/86974579-359e8080-c13c-11ea-9804-1fa39ff9248b.jpg)
![Screen Shot 2020-07-08 at 4 56 22 PM](https://user-images.githubusercontent.com/21181118/86974582-37684400-c13c-11ea-8226-efc3cd3c7482.jpg)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by will-stone** [comment]
Thanks, this project uses @alrra's excellent repo of icons, looks like this is being tracked there: https://github.com/alrra/browser-logos/issues/184

**Comment by gottabeleGIT** [comment]
Yep, just realized that,thanks XD

**Comment by alrra** [comment]
@will-stone You can get the new `Safari Technology Preview` logo by [updating the dependency to `v2`](https://github.com/alrra/browser-logos/blob/929c7bcb52f890ea1f5eb8b900dff0b4b4554e10/src/safari-technology-preview/CHANGELOG.md#200-july-8-2020).

**Comment by alrra** [comment]
@will-stone You can get the new `Safari` logo by [updating the dependency to `v2`](https://github.com/alrra/browser-logos/blob/d9261cc98dbdb2c6288a6b0ddfd0ca1a3e65afc1/src/safari/CHANGELOG.md#200-july-31-2020).

**Comment by will-stone** [comment]
Thanks @alrra
