### ISSUE TITLE
Feature request: Custom rules

### ISSUE THREAD

**Issue by jovobe** [will-stone/browserosaurus#247]
Thanks for the great software! Since I'm a user coming from Choosy, it would be great to have a ruleset for certain domains/URLs that should always be opened in a certain browser. For example: I work for a company with the domain my-great-company.com and they host various tools on subdomains of that domain. I would like to create a rule like "open all links containing my-great-company.com in the hostname with Chrome" if Chrome is my browser for work stuff.

**Comment by will-stone** [comment]
Thanks for using Browserosaurus. From the [FAQ](https://browserosaurus.com/#faq):

>  I would like to open a particular browser automatically for specific URLs.

> Browserosaurus does not provide a method for automatically selecting browsers, rather opting for the consistency that the picker window will show every time. If you would like to be able set rules, I highly recommend Finicky by John Sterling which can very easily be used in tandem with Browserosaurus, meaning the best of both worlds: a rules engine and a graphical interface. 

Duplicate issues:

#204 #203 #183 #113 #91 #53 #32
