### ISSUE TITLE
Feature Request: Add Finicky to Whitelist

### ISSUE THREAD

**Issue by anmull** [will-stone/browserosaurus#249]
Having Finicky launch browserosaurus is a great combination, but having the choice to launch Finicky from browserosaurus would be the icing on the cake :) I agree with the many closed issues that browserosaurus doesn't need rules when the two work well together. Here is a use case for bidirectional integration.

Let's say we have Tor, Firefox, and Chrome. Firefox is our default browser, Chrome is only for our authenticated imgur.com account, and we have a finicky rule that sends imgur.com traffic to Tor for those random links we don't know what we are going to be viewing.

With finicky->browserosaurus we can't make the decision to use Chrome instead of Tor, but with browserosaurus->finicky we can make the decision to have finicky make the decision based on the rules or override that with how we feel about the link at that moment.

I really enjoy the power of both tools, this added flexibility would be a nice addition.

**Comment by will-stone** [comment]
This is a good idea, I'll add this in due course.

**Comment by will-stone** [comment]
This will be in the next release
