### ISSUE TITLE
Auto Detect Browsers

### ISSUE THREAD

**Issue by anmull** [will-stone/browserosaurus#250]
> Let's close this out and say that the white-list method works for us. Please reopen if you hear of any Electron/MacOS API that allows B to know of URL-openers.

_Originally posted by @will-stone in https://github.com/will-stone/browserosaurus/issues/51#issuecomment-489443381_

I stumbled onto this issue after I submitted #249. Each application that supports a schema defines that in the Info.plist as key "CFBundleURLSchemes". 

So if you run this find command you can find all browsers.

```
find /Applications -name Info.plist -maxdepth 3 -print0 | xargs -0 grep --files-with-matches "<string>https</string>" | sort
/Applications/Brave Browser Beta.app/Contents/Info.plist
/Applications/Brave Browser.app/Contents/Info.plist
/Applications/Browserosaurus.app/Contents/Info.plist
/Applications/Finicky.app/Contents/Info.plist
/Applications/Firefox.app/Contents/Info.plist
/Applications/Google Chrome.app/Contents/Info.plist
/Applications/Parallels Desktop.app/Contents/Info.plist
/Applications/Safari.app/Contents/Info.plist
/Applications/Tor Browser.app/Contents/Info.plist
/Applications/Vivaldi.app/Contents/Info.plist
/Applications/iTerm.app/Contents/Info.plist
```

It does list iTerm and Parallels, but those are valid "browsers". That was out of 162 apps in /Applications so I'd say it is fairly reliable.

**Comment by will-stone** [comment]
This is great, thanks! If we were to find browsers automatically like this, we'll also need a way to get and display the icons for each. Up for the challenge?

**Comment by anmull** [comment]
Are you able to display .icns or does it need to be converted to png? Do you need a specific size or are you setting the dimensions?

It's pretty easy to get the icons.

```
pcregrep -M "<key>CFBundleIconFile</key>\s[\t]+<string" "/Applications/Brave Browser.app/Contents/Info.plist"
	<key>CFBundleIconFile</key>
	<string>app.icns</string>
```

```
cp "/Applications/Brave Browser.app/Contents/Resources/app.icns" Brave.icns
icns -c iconset Brave.icns
mv Brave.iconset/icon_512x512@2x.png Brave.png
rm -rf Brave.icns Brace.iconset
```

There are two npm packages iconutil and plist that can be combined to do this in a function.

I'll get a PR over to you soon.

**Comment by will-stone** [comment]
Nice! Thanks. Looking forward to seeing the PR. Remember we'll probably need to keep the whitelist for apps like Pocket, which aren't browsers but can be opened with their own protocols.

**Comment by anmull** [comment]
I don't use Font Awesome Pro so that's an issue, but I'll see if I can work around that.

**Comment by will-stone** [comment]
Ah, yes, I thought this would be a problem one day. I'm not really sure the best way to handle that for contributors. I'll look into it.

**Comment by anmull** [comment]
I replaced all references to fa[A-Za-z]+ to one of the free icons and got it to work

**Comment by will-stone** [comment]
I got a reply back from FA support:

> Our pro license does not work for open source projects

Their license says I can embed their Pro icons in apps but as I'm not actually using any, I thought I'd just remove this headache. If you merge master, you'll find all icons are now from the free repo.

**Comment by anmull** [comment]
Thanks. It's a bummer they don't have a solution for open source projects.

**Comment by TheXMan13** [comment]
Can Friendly Streaming be easily added to the whitelisted browsers?

**Comment by will-stone** [comment]
Browserosaurus is now considered _Public Feature Complete_, you can read more here: https://github.com/will-stone/browserosaurus/blob/master/CONTRIBUTING.md

Thank you.
