### ISSUE TITLE
Is there a way to prevent Browserosaurus from launching at startup?

### ISSUE THREAD

**Issue by wattachai** [will-stone/browserosaurus#276]
I did check the Login Items in System Preferences but couldn't find it.

**Comment by will-stone** [comment]
Browserosaurus doesn't set itself to start at login. Have you got something trying to open a link? Make another browser your default and restart.

**Comment by wattachai** [comment]
I was trying to find a way to temporarily disable Browserosaurus. 

You've just totally nailed it! Thanks!
