### ISSUE TITLE
Add Friendly Streaming browser

### ISSUE THREAD

**Issue by will-stone** [will-stone/browserosaurus#284]
Can Friendly Streaming be easily added to the whitelisted browsers?

_Originally posted by @TheXMan13 in https://github.com/will-stone/browserosaurus/issues/250#issuecomment-681153771_

**Comment by tolgaerdonmez** [comment]
I can probably add that.

**Comment by will-stone** [comment]
Browserosaurus is now considered _Public Feature Complete_, you can read more here: https://github.com/will-stone/browserosaurus/blob/master/CONTRIBUTING.md

Thank you.
