### ISSUE TITLE
Open in Firefox Containers

### ISSUE THREAD

**Issue by VandrerenDeveloper** [will-stone/browserosaurus#290]
In Firefox I rely a lot upon the use of [containers](https://addons.mozilla.org/en-GB/firefox/addon/multi-account-containers/), I think it would be great to decide from within Browserosaurus in which container to open the links.

Also, I've been thinking about starting to collaborate with this project to create a fork for Linux. Am I welcome to do that?

**Comment by will-stone** [comment]
Hi. This is similar to the Chrome Profiles request #56. I'm a Firefox user too, but I haven't really got that into containers yet. The Facebook one is good, as it does it all for you, I just haven't had the inclination to set-up any others yet. How can you detect Firefox's containers? What's the command? Alternatively, maybe you could develop a Firefox addon that listens for incoming URLs and prompts you within Firefox? That, I reckon would be welcomed in the Firefox community.

As for a Linux fork, go for it. You will probably only need to change the `doesAppExist` function: https://github.com/will-stone/browserosaurus/blob/master/src/utils/doesAppExist.ts Oh, and the update the command that launches the app: https://github.com/will-stone/browserosaurus/blob/master/src/main/main.ts#L179

Please bear in mind that I love a refactor, so keeping up with upstream may not be fun 😅

**Comment by will-stone** [comment]
One thing to note, if you do release an app, please rename it. I'm happy with anything that's a riff on Browserosaurus (Browseratops etc.), but I'd like to keep the name tied to this project. Thanks.

**Comment by will-stone** [comment]
Looks like this is being tracked here: https://github.com/mozilla/multi-account-containers/issues/706 and the only way to choose a container externally would require the user to install an addon: https://github.com/mozilla/multi-account-containers/issues/365#issuecomment-526965740 I don't think adding a feature that relies on an external solution _is_ a solution, therefore I'm going to close this.
