### ISSUE TITLE
Big Sur error 

### ISSUE THREAD

**Issue by macdaddy1944** [will-stone/browserosaurus#291]
<img width="326" alt="Screen Shot 2020-09-03 at 11 54 53 AM" src="https://user-images.githubusercontent.com/49851150/92155525-64537300-eddc-11ea-8b12-ce41d6ff564e.png">

**Comment by will-stone** [comment]
Ah the dangers of using beta software 😜 Hopefully this won't be an issue when Big Sur makes stable. Thanks for reporting though. I'll check when I upgrade. If you wanna get ahead of the game, check other Electron based apps and see if they are getting similar issues.

**Comment by macdaddy1944** [comment]
I’m not sure I’ve moved any electron-based apps over but I do have some that I fiddle with so I will try

**Comment by will-stone** [comment]
I've just upgraded to Big Sur and I'm not seeing this error. Are you still getting it?
