### ISSUE TITLE
Prevent icon from displaying in macOS dock

### ISSUE THREAD

**Issue by houndtt** [will-stone/browserosaurus#295]
This is a repeat of issue #166 which was previously resolved but seems to have reoccured in the recent release.

**Comment by will-stone** [comment]
Which version are you using?

**Comment by houndtt** [comment]
> Which version are you using?

I'm using v12.0.0 currently but this seems to have started somewhere in the v11 builds

**Comment by will-stone** [comment]
Hmmm 🤔 how strange, this doesn't happen for me. Which version of macOS are you using? And (I know this is annoying) have you restarted your machine?

**Comment by houndtt** [comment]
Very strange indeed. I've rebooted as well as reinstalled the app from a fresh download but it does not seem to change the behaviour. I'm running macOS Catalina 10.15.6. I'm also including an EtreCheckPro report from today in case you need to get any other details on my setup... https://pastebin.com/75GH101L

**Comment by houndtt** [comment]
> Is B in the `cmd-tab` list?

No it does not show up in the app switcher list

**Comment by will-stone** [comment]
ah, in which case I think it might just be saved me in your dock or be in the recent apps list. Can you please try dragging it out of the dock to see if that solves the problem.

**Comment by houndtt** [comment]
> ah, in which case I think it might just be saved me in your dock or be in the recent apps list. Can you please try dragging it out of the dock to see if that solves the problem.

Yes, the icon rotates into my recent apps section of the dock. Removing it only re-introduces it when next I reboot. This is the specific problem that you previously fixed in issue #166. Can you perhaps refer to that once more to see if it can be fixed again?

**Comment by will-stone** [comment]
Well, I've not changed any of the code that originally fixed this issue: https://github.com/will-stone/browserosaurus/commit/a1a87c913bf99808132357fb260e47bfb0994ff7# which is annoying. Therefore this is either an Electron or Electron Forge issue. I'll see if anyone is reporting anything on their repos. Thanks.

**Comment by will-stone** [comment]
From reading the Electron docs, it looks like this `electron.app.setActivationPolicy('accessory')` is the answer but I've tried it in various places of the main process but nothing seems to work. I'm guessing, it's a macOS problem (or maybe they'd call it a feature). I personally don't use the Recent Applications feature of the dock, for the this exact reason; I like to be in control of my dock. I'm not really sure what else I can do, other than hope someone that's fixed this issue stumbles across this thread and helps me out 🤞

**Comment by houndtt** [comment]
Thanks for looking into this. This feature in electron seems to have been added as part of https://github.com/electron/electron/pull/21983/commits/95fb80a8d8c11f47990490f7deb1e2acf7a1003c. Looking at the details, it seems straightforward and results in a call to `NSApplicationActivationPolicyAccessory`.

In checking with Apple's developer site, this corresponds to https://developer.apple.com/documentation/appkit/nsapplicationactivationpolicy/nsapplicationactivationpolicyaccessory. Reading the notes the result would be the `LSUIElement` key in the application’s `Info.plist` being 1. Checking within your app this appears to be set correctly:

```
    <key>LSUIElement</key>
    <true/>

```

This is the exact same setup I see in Microsoft's OneDrive File Launcher so you may be right in that there may have been something changed in the way that Electron and macOS Catalina interact. Hopefully someone more knowledgeable in this can help figure this out.

**Comment by will-stone** [comment]
Thanks @houndtt, I really appreciate the in-depth analysis.

**Comment by houndtt** [comment]
Maybe as an alternative you could explore a configuration like the one that "Network Utility" uses where the app launches but the icon isn't retained when it quits. Don't know if that will fix the problem since the app is still technically running in the menu bar. Here's a video which shows the scenario...

https://vimeo.com/462232431

**Comment by will-stone** [comment]
Maybe... it'd mean the window being recreated on each open, this might affect performance. Some experimentation required.

**Comment by houndtt** [comment]
Hey @will-stone, I was revisiting this and tried to track down the change in behaviour. Based on my reviews of your earlier builds I was able to confirm that the last version where the icon was not displayed in the dock was [v11.0.1](https://github.com/will-stone/browserosaurus/releases/tag/v11.0.1). Downloading the next version [v11.1.0](https://github.com/will-stone/browserosaurus/releases/tag/v11.1.0) the app icon shows persistently in the dock. This was amended in [v11.1.1](https://github.com/will-stone/browserosaurus/releases/tag/v11.1.1) where we see the current behaviour with the app showing briefly on launch in the dock.

Comparing the first a last versions in the v11 releases we see the following: https://github.com/will-stone/browserosaurus/compare/v11.0.1...v11.1.1. I'm not sure I'm able to see a specific thing that may cause the issue but one way to test your theory if it's an electron issue is to try to v11.1.1 build and use the electron components from the v11.0.1 build. The difference seems to be 6.0.0-beta.52 changed to 6.0.0-beta.53 of electron. I don't know how to do this personally but thought this may be something you could try if you have some time to further diagnose the issue.

**Comment by will-stone** [comment]
Thanks for the thorough testing! 😄 They did seem to change a few things in Electron v10. The new version I'm working on at the moment (branch `big-sur-design`), uses Electron v11. And I've just done a quick test and this looks to be fixed... I'm hoping to release soon (maybe even today, so you can double check and let me know 🙂).

**Comment by houndtt** [comment]
Excellent! I've upgraded to [v13.0.1](https://github.com/will-stone/browserosaurus/releases/tag/v13.0.1) and everything seems to be working perfectly. I believe this issue can now be closed.

**Comment by will-stone** [comment]
Thanks @houndtt 😊
