### ISSUE TITLE
Browserosaurus fails to fetch installed browsers

### ISSUE THREAD

**Issue by arashnrim** [will-stone/browserosaurus#309]
Hello!

I've encountered this issue where Browserosaurus is unable to fetch and display the list of installed browsers. For me, this notably happens around start-up; after a while, though its behaviour reverts back to usual with the browsers listed.

Here's a screenshot of this issue happening on my end:
<img width="1000" alt="Screenshot 2020-09-19 at 9 03 04 PM" src="https://user-images.githubusercontent.com/47273556/93668021-7d3a7480-fabc-11ea-9331-13f82ed0ed36.png">

I'm running Catalina (10.15.6). I only noticed this happening around start-up, but I'll continue to monitor Browserosaurus' behaviour and report again if I notice it sometime else!

**Comment by will-stone** [comment]
Thanks for reporting. I've also had someone email me with this issue. Unfortunately I don't know what's causing this yet. Can I ask, are you using a VPN? Not sure why this would be problem but the other user has a VPN and I'm just seeing if there's any correlation between you two.

**Comment by arashnrim** [comment]
Hey! Thanks for the response.

I'm not using a VPN on my end. I guess that adds on to the issue (slightly) since to say that a VPN is or isn't causing it is both equally uncertain.

**Comment by will-stone** [comment]
Do you know your way around `Console.app`? I personally find it incredibly confusing, but maybe there's something in there to indicate an error from B?

**Comment by arashnrim** [comment]
Sure! I'll try to keep an eye out for stuff in the Console.

**Comment by arashnrim** [comment]
I couldn't find any significant error, but I'll attach the logs anyway if I'm mistaken.

[Browserosaurus.txt](https://github.com/will-stone/browserosaurus/files/5258543/Browserosaurus.txt)
[Browserosaurus2.txt](https://github.com/will-stone/browserosaurus/files/5258545/Browserosaurus2.txt)

I separated the logs (with two empty lines) in both cases since I've triggered Browserosaurus three times in both logs:
- For the first attempt, I tried to open a link with Browserosaurus; the browsers list wasn't available.
- For the second attempt, I quit and opened Browserosaurus again; the browsers list still wasn't available.
- For the third attempt, I went into Browserosaurus' settings and reloaded Browserosaurus (that little sync icon thing); after the reload, the browsers list loaded fine.

I guess through this I've found a little workaround for now!

**Comment by will-stone** [comment]
Okay thanks. So it sounds like I have a race condition at startup 🤔 I'll try to see what that could be. I did change the state management on the renderer from Redux to Zustand. Maybe Zustand doesn't like quick updates 🤷‍♂️ I'll do some digging. Thanks 😊

**Comment by will-stone** [comment]
Well, I'm stumped. It doesn't help that I don't see this issue at all on either my machine nor my work laptop. At least we seem to have nailed it down to only startup and the reload button fixes it. I may try to fix this by simply going back to Redux but that would be a fair amount of work, and it would be super annoying if it was still broken after all that. I'll have a think about it.

**Comment by houndtt** [comment]
hey @will-stone, glad to see you were already alerted to this. If you are in need of any specific diagnostic assistance I am happy to try out a few things for you on my machine to better understand the issue. you already have my machine details and video of the issue. ready and willing to assist as much as I can

**Comment by will-stone** [comment]
Thanks @houndtt.

From what I can tell it's to do with this: https://github.com/electron/electron/issues/25253 Which states that the issue effects people intermittently. That explains why I don't see it.

A workaround had been stated and I'll give that a go.

**Comment by will-stone** [comment]
Okay, can you all please check 12.2.1 and see if the issue is fixed? In particular, please completely quit and restart B, as it seems this only affected B on app launch (not the reload button). Thanks.

**Comment by houndtt** [comment]
> Okay, can you all please check 12.2.1 and see if the issue is fixed? In particular, please completely quit and restart B, as it seems this only affected B on app launch (not the reload button). Thanks.

This seems to have fixed things on my end. Did multiple tests from different external apps on first launch and all showed the issue to be resolved. Will await further corroboration from the community.

**Comment by arashnrim** [comment]
> Okay, can you all please check 12.2.1 and see if the issue is fixed? In particular, please completely quit and restart B, as it seems this only affected B on app launch (not the reload button). Thanks.

I can attest to @houndtt's comment; it's working again on my end, too. Thanks a bunch for your prompt response! 🎉

**Comment by will-stone** [comment]
Thanks @arashnrim & @houndtt

**Comment by skorp** [comment]
Hi, 

i'm having the same issue on 12.3.1.

**Comment by will-stone** [comment]
@skorp Does the version show in the bottom left of the settings menu? If it _does_ show, then it's not the same problem and you can probably fix it by re-running a Spotlight index and restarting B.

**Comment by skorp** [comment]
@will-stone thanks for your fast reply, but the case is i'm not using the spotlight index, i would say the index was also empty when i installed the B.
In the spotlight settings no checkbox is selected.
i tried it again, the shortcuts are working correct, only the images are not shown.

ps. i'm using alfred instead of spotlight

**Comment by will-stone** [comment]
@skorp Now worries, all Browserosaurus does at startup is _ping_ each of the whitelisted apps to see if they exist on your system using a command. The command uses Spotlight's indexing system (as far as I know).

To see if it's all working, run this:

```
mdfind 'kMDItemContentType == "com.apple.application-bundle" && kMDItemCFBundleIdentifier == "com.apple.Safari"'
```

If it doesn't return `/Applications/Safari.app` or something very similar then you will need to fix Spotlight's index. This is the safest way to check if a user has an app installed as bundle identifiers are unique.

**Comment by skorp** [comment]
@will-stone it returned nothing, 
but now i enabled spotlight indexing only for applications again. 
now it works

**Comment by will-stone** [comment]
At least we now know for sure that Spotlight's Applications index is a requirement. It should probably be added to the "I have a browser that's not shown in the picker window, even after reloading Browserosaurus" section of the FAQ. Would you like to make a PR? If not, please add an issue and either myself or another volunteer can add this later. Thanks.
