### ISSUE TITLE
Opens a new blank window

### ISSUE THREAD

**Issue by w3code** [will-stone/browserosaurus#31]
Hi!

Since today it opens only a new blank window.

### Version 1.3.1
* electron: 1.7.9
* chrome: 58.0.3029.110
* node: 7.9.0
* v8: 5.9.283.38

**Comment by will-stone** [comment]
Is this the compiled binary or are you running it from source? I'm in the process of quite a big rewrite so maybe it'll be solved in that.

**Comment by will-stone** [comment]
Strange. It's working ok on my computer (I opened the link from my mail with it to get here). Which version of macOS are you using?

**Comment by w3code** [comment]
It worked great until I started my Mac today. I'm using macOS V10.13.2

**Comment by will-stone** [comment]
Hmmm, have you tried restarting Browserosaurus and/or your computer? I know that's not the greatest answer, but there may be issues with dependencies (like Electron) that are out of my control.

**Comment by w3code** [comment]
Yes, I have tried it. :D 

Well, because that's not a fundamental problem for me now, I'll wait for your update after you've rewritten it. ;-)

**Comment by w3code** [comment]
Hmm... today it's working again. Strange. So I close the issue. ;)

**Comment by will-stone** [comment]
Ok, that is odd. v2 should be released sometime this weekend, so hopefully that'll fix any weirdness like this 🤞

**Comment by w3code** [comment]
The same problem again. I've deinstalled the app and installed new (with yarn). Problem still there.

**Comment by will-stone** [comment]
Hi. Why are you installing with yarn? I thought you were using the compiled version.

**Comment by will-stone** [comment]
I'm going to close this as I've not heard back from you. v3 has now been released, please download and install from the `dmg` file found on the [releases](https://github.com/will-stone/browserosaurus/releases) page.
