### ISSUE TITLE
Browserosaurus only shows black URL bar when clicking on a link, and I cannot work out how to do anything with it; the selection of browsers only shows after much aimless clicking.  Advice please.

### ISSUE THREAD

**Issue by anguka** [will-stone/browserosaurus#316]
<img width="1009" alt="view order" src="https://user-images.githubusercontent.com/44961616/93870067-d6e4ae00-fd0b-11ea-91da-c6368dde389b.png">
<img width="984" alt="kill B" src="https://user-images.githubusercontent.com/44961616/93870097-dfd57f80-fd0b-11ea-9130-4d10b3adc507.png">

**Comment by houndtt** [comment]
Hi, I seem to have the same problem with the most recent version as well. I've included a video which shows the behaviour on first launch and how I usually get it to work.

https://vimeo.com/460539280

**Comment by will-stone** [comment]
Please follow progress here: https://github.com/will-stone/browserosaurus/issues/309

**Comment by anguka** [comment]
Clicking on “#309” just produced the lone black address bar, with its options to delete, copy or quit.  I then started to send this email and checked the link again, and it opened properly and has done on three or four tries ever since.  I hope this helps.

Angus
