### ISSUE TITLE
Big Sur: B isn't in the "Default web browser" dropdown list in System Preferences

### ISSUE THREAD

**Issue by i0ntempest** [will-stone/browserosaurus#317]
Since we are closing in to the release of the next major macOS version I thought I should bring this up.
Browserosaurus is not selectable as the default browser because it's not in the list. Some other apps that were in this list before are: Evernote, FDM, iTerm2, WWDC (unofficial app).
Meanwhile there's a workaround: install the CLI utility `defaultbrowser` from homebrew or macports, which allows B to be chosen as the default browser; also if you have B selected in Catalina then upgrade to Big Sur, it will still be selected. Note that even after you've selected B, Safari will still be shown as selected in System Preference.

**Comment by will-stone** [comment]
Thanks 😊 I'm guessing this is an Electron issue. I'll have a look on their repo to see if anyone else has experienced this.

**Comment by will-stone** [comment]
I've now upgraded to Big Sur and everything (apart from a few visual artefacts) is working fine with B. I even uninstalled it, rebooted, and reinstalled it and it still receives links. Now, granted, it doesn't show in the list of default browsers, but this doesn't seem to be a problem and I'm guessing this is an Electron issue. If you unset B as your default browser, you can just reset using the button in B's settings menu. Hopefully a fix for the Default Browser list will come from Electron in the near future. If you find any issues on their repo related to this, I'd appreciate you linking them here so I can keep an eye on the status of the fix.

**Comment by johnste** [comment]
I'm also seeing this [issue in Finicky](https://github.com/johnste/finicky/issues/146) so might not be related to Electron. Just thought I'd let you know.
