### ISSUE TITLE
Use external wrapper for choosing right Browser

### ISSUE THREAD

**Issue by hackruu** [will-stone/browserosaurus#32]
Is it possible to add some external script execution with parameters before showing browser chooser window?
I want to implement my own logic so no need to choose browser in menu on every click and do some url rewrites if needed. For example, i want to open links with domain.tld belonging to my work in one browser, other links — in another. Or i want to remove some tracking links from url with my code and return cleaned url.

Wrapper script should have input parameters(json?):
- url
- ??

and return:
- new url
- browser_name or default

Not sure if it's hard to implement. I think it should be nearly easy task. Thanks in advance.

**Comment by will-stone** [comment]
Hi. Sounds like you're describing features of [Choosy](https://www.choosyosx.com/). That's currently out-of-scope for this project but you're not the first to ask so I may consider it in the future. Feel free to send pull-requests, just hold off until v2 is released as I'm in the process of reformatting the code (v2's currently a little messy, so it really is best to wait until its released).

**Comment by hackruu** [comment]
Thanks for an answer. Not exactly, as far as i can see Choosy don't allow to modify url or choose browser with help of external script. It have some automator-like rules, but it won't help me.

**Comment by will-stone** [comment]
I see. Well, it should be fairly easy to pull out the functions you need from `main.js` and make something similar to Browserosaurus but tailored to your needs. However, like I said, if you figure out a way to nicely integrate your requirements then please send a pull-request for consideration. And if you go down the fork route, please let me know how you get on.

**Comment by hackruu** [comment]
actually i'm not js programmer, so i replaced sendUrlToPicker(url) function with hardcoded script spawn and i'm good with this. thanks for you time.

**Comment by will-stone** [comment]
Awesome! That's great to here. Maybe you could share the project so others can see what you did? No pressure, but it'll help if others are looking for a similar solution.

**Comment by hackruu** [comment]
such a shame, just reused your code for executing external binary.

```diff --git a/src/main.js b/src/main.js
index f929ad5..f29ca4d 100644
--- a/src/main.js
+++ b/src/main.js
@@ -196,8 +196,12 @@ function createTrayIcon() {
  * @param {String} url clicked link.
  */
 function sendUrlToPicker(url) {
-  pickerWindow.center() // moves window to current screen
-  pickerWindow.webContents.send('incomingURL', url)
+    return new Promise((fulfill, reject) => {
+    const sp = spawn('/Users/hackru/bin/cleanlink.sh', [url])
+    sp.stdout.on('end', () => {
+          return false
+    })
+  })
 }

 /**```

**Comment by will-stone** [comment]
Sorry, I must know, what exactly is "such a shame"? Looks like you've achieved what you wanted.

**Comment by hackruu** [comment]
yes, i achieved. but copy-pasting-modifying code without any idea will it will work or not is a shame. let's not continue this dialogue, thanks.
now i have two browseraurus instances, first one is mine edited that applies rules and opens second vanilla browseraurus to choose browser if no rules were applied. pretty happy with this.
