### ISSUE TITLE
Add Responsively App

### ISSUE THREAD

**Issue by abbydigital** [will-stone/browserosaurus#338]
Responsively App

https://github.com/responsively-org

**Comment by will-stone** [comment]
Oooo, not sure how I feel about this one... t'is in direct competition with @Kilian's Polypane who has PR'd their own addition to Browserosaurus, updated the icon when required, _and_ added a [link back](https://polypane.app/docs/switching-to-polypane/#browserosaurus-macos) to B on their docs 😆 

Could you please run `mdls -name kMDItemCFBundleIdentifier -r /Applications/[NAME OF APP]` and let me know the bundle identifier?

For example:

```sh
> mdls -name kMDItemCFBundleIdentifier -r /Applications/Safari.app/
com.apple.Safari
```

**Comment by Kilian** [comment]
Speaking of which, I should update that screenshot ;)

**Comment by abbydigital** [comment]
I hadn’t heard of Polypane until now, but the significant difference is Responsively being free, so, is there not room for both in Browerosaurus?

**Comment by will-stone** [comment]
Don't worry, I was joking 😄 I am just impressed that @Kilian has kept his part of Browserosaurus up-to-date. And remember, free doesn't = better....

So... @Kilian when do I get my referral fee? 😆 

Right, jokes and mumbling aside, @abbydigital run the command and I'll add it to the backlog of the todo list.

**Comment by abbydigital** [comment]
I don’t know about PolyPane’s features, but responsively certainly has a ways to go.  Version is currently at 0.12.0

It’s not my app, but I’d gladly run the command.  It’s just above my skillset, and I don’t wanna screw things up.  Will try.

I don’t think it worked the way it was supposed to.  This is supposed to happen in Terminal?  The response was:

/Applications/ResponsivelyApp/: could not find /Applications/ResponsivelyApp/.

You may be able to tell that I don’t really know what I’m doing here…

- Abby

**Comment by will-stone** [comment]
Hi Abby, don't worry about it. Terminal can be scary, certainly when some bloke off the internet is telling you to copy-paste in commands! 😆 I'll check out Responsively when I get time. Just to set expectations: it won't be for a little while, as I am moving house and who knows how long it'll take to move the internet 🙄

**Comment by abbydigital** [comment]
How hard could it be to move the Internet?  It’s so small!

https://www.etsy.com/listing/117109422/the-internet-from-the-it-crowd?show_sold_out_detail=1&source=aw&utm_source=affiliate_window&utm_medium=affiliate&utm_campaign=us_location_buyer&utm_term=301043&utm_content=141392&awc=6220_1603979395_bf549f4ed7cdc3699e788035d18c168c <https://www.etsy.com/listing/117109422/the-internet-from-the-it-crowd?show_sold_out_detail=1&source=aw&utm_source=affiliate_window&utm_medium=affiliate&utm_campaign=us_location_buyer&utm_term=301043&utm_content=141392&awc=6220_1603979395_bf549f4ed7cdc3699e788035d18c168c>

**Comment by will-stone** [comment]
Browserosaurus is now considered _Public Feature Complete_, you can read more here: https://github.com/will-stone/browserosaurus/blob/master/CONTRIBUTING.md

Thank you.
