### ISSUE TITLE
Add Stack Browser

### ISSUE THREAD

**Issue by ademik** [will-stone/browserosaurus#339]
https://getstack.app

**Comment by will-stone** [comment]
As per this comment, could you please run the command to find the bundle identifier:

https://github.com/will-stone/browserosaurus/issues/338#issuecomment-718479146

It is then just a case of finding a reasonably-sized logo, if you’d like to raise a PR?

**Comment by will-stone** [comment]
Browserosaurus is now considered _Public Feature Complete_, you can read more here: https://github.com/will-stone/browserosaurus/blob/master/CONTRIBUTING.md

Thank you.
