### ISSUE TITLE
Doesn't open the right browser

### ISSUE THREAD

**Issue by DeeGeeMan** [will-stone/browserosaurus#340]
I have Firefox and Firefox Developer Edition installed and both show up in the list, but when I click on Firefox Developer, it always launches standard Firefox.

<img width="529" alt="Browsers" src="https://user-images.githubusercontent.com/21670040/99919356-da37ee00-2cea-11eb-9e4f-6a38ee108f4f.png">

**Comment by will-stone** [comment]
Hi.

Does this happen with other similar browsers? e.g. Chrome and Chromium, or Brave and Brave Dev?

Also, which version of macOS are you using?

Thanks.

**Comment by DeeGeeMan** [comment]
I am not using any of the other browsers.

OS: Big Sur

-Devin

**Comment by will-stone** [comment]
Thanks. Could you please test them?

**Comment by DeeGeeMan** [comment]
Works fine with Chromium & Chrome browser and Brave & Brave Dev.  However, I noticed this problem when Firefox is already running when selecting Firefox Developer.  This workflow is not an issue for both Chrome and Brave browsers.

**Comment by will-stone** [comment]
Thanks 😊 That’s great info, but also very strange. The browser is launched using an ID and therefore should be unique. I’ll do some digging. No ETA at the mo as I’m pretty busy.

**Comment by will-stone** [comment]
I think this is a Firefox thing. Have you tried opening both browsers at the same time? Without B, I mean. I’m pretty sure Mozilla don’t let you run both at the same time.

**Comment by will-stone** [comment]
Closing for now. Please re-open if you find this is a bug with B and not an issue with Firefox.
