### ISSUE TITLE
Add Sidekick browser

### ISSUE THREAD

**Issue by Rpsl** [will-stone/browserosaurus#342]
https://www.meetsidekick.com/

```
$ mdls -name kMDItemCFBundleIdentifier -r /Applications/Sidekick.app
com.pushplaylabs.sidekick
```

**Comment by Rpsl** [comment]
how to do it

https://github.com/will-stone/browserosaurus/issues/170#issuecomment-576193982

**Comment by will-stone** [comment]
> how to do it
> 
> [#170 (comment)](https://github.com/will-stone/browserosaurus/issues/170#issuecomment-576193982)

Huh? You plan on submitting a PR?

**Comment by Rpsl** [comment]
if no one does that i make PR

**Comment by Rpsl** [comment]
browser logos https://github.com/alrra/browser-logos/pull/192

**Comment by Rpsl** [comment]
haha, [fantastic open source and where to find them](https://github.com/alrra/browser-logos/pull/192). I will use Choosy

**Comment by will-stone** [comment]
Sure. For what it's worth, I have a lot of respect for @alrra for pushing back on things he doesn't want to support. More OS devs should do this so that people aren't surprised when it happens.
