### ISSUE TITLE
Google Chrome no longer appearing

### ISSUE THREAD

**Issue by randymedd** [will-stone/browserosaurus#343]
MacOS 10.14.6 (18G6042). Chrome appeared previously, so I suspect a recent Google update managed to break things. Checked the app id, and it's still showing as "com.google.Chrome". Chrome version: 87.0.4280.67 (Official Build) (x86_64).

**Comment by will-stone** [comment]
Try reindexing Spotlight

**Comment by randymedd** [comment]
As suggested, rebuilding the Spotlight index did the trick. This can be closed.

**Comment by will-stone** [comment]
Nice 👍
