### ISSUE TITLE
Prevent focusing Finder when browserosaurus opens

### ISSUE THREAD

**Issue by puresick** [will-stone/browserosaurus#349]
When opening Browserosaurus, Finder gets focused. This can be witnesses on the top left i.e. in the macos application bar.
This can be annoying when working with multiple windows and expecting a particular window to be on a specific position in the macos app switcher.

In my case for example, I am using Browserosaurus while developing web apps. I have an alacritty terminal open, in which I am using different tools like my code editor. When I am starting my development server, I use a feature that automatically opens an URL when my web app is ready to start. This starts Browserosaurus and lets me choose the browser I want to use. After that, I often want to change back to my terminal, which I expect to be the last app I used. In this case, I am focusing Finder instead.

**Comment by puresick** [comment]
I just tested around a bit and it seems that this issue only happens when Browserosaurus gets opened by any terminal application (I tested it with Alacritty, iTerm and the official macos Terminal.app).
It does not make any difference if it is an URL a user clicked on inside the terminal or if it is an URL automatically being opened by a terminal application (e.g. in my case, this was webpack-dev-server).

**Comment by will-stone** [comment]
Weird. That doesn't happen to me:

- Terminal: `open "http://wstone.io"`.
- B opens and I select Firefox.
- Firefox is focused and opens new tab.
- <kbd>cmd+tab</kbd> once -> Terminal is focused.

1. Which version of B are you using? I'm on v12.3.1, it can found in the bottom-left of the Settings menu.
2. Which version of MacOS are you using? I'm on 11.0.1 (on my work machine where I just tested this).
3. Could you screen video record the issue?

**Comment by will-stone** [comment]
Are you suffering from this? https://superuser.com/questions/1547580/finder-keeps-stealing-focus-mac-os-x-catalina-10-15-4

**Comment by puresick** [comment]
Your steps above also work for me as expected.

1. I am also using v12.3.1
2. Also my macos version matches yours (11.0.1)

I also tested the behaviour on a fresh web project created with `create-react-app`. On that fresh boilerplate, the behaviour does not occur. With that in mind, I strongly believe this is cause by some specific project configuration on my side.

3. Sadly, due to the fact that this seems to be project specific, I cannot screen record you the behavior because I am not allowed to share anything related to this project.

It does not look like I am suffering from the issue written in the post you linked. There is no such error in the Console.app while the issue occurs.

I am going to investigate further where the problem comes from and - hopefully - can deliver some solution for this on the way. Either way, this does not seem to be a problem on this projects side. :)

Thank you for your help and (really fast) answers!

**Comment by will-stone** [comment]
> Sadly, due to the fact that this seems to be project specific, I cannot screen record you the behavior because I am not allowed to share anything related to this project.

Fair enough 👍 

I had a quick look on CRA's issue board but can't seen anything like you described. Certainly sounds project specific. Good luck and please post the solution here when you find it, in case others have a similar problem.

**Comment by puresick** [comment]
Okay so I did a bit further research and it seems my assumption regarding the project misconfiguration is wrong.

I can reproduce my initial behaviour with the steps you provided by appending a `/` at the end of the URL, so e.g.

`open "http://wstone.io"` works as expected, but
`open "http://wstone.io/"` switches the focus to Finder.

This does not happen if I try to open URLs posted in the Slack app, Telegram or Apple Notes for example.
(Weirdly enough, in Telegram shows a confirmation dialog for the first URL but not for the second - which definetly is something on Telegrams side).
It can be reproduced in all terminal apps I mentioned above.

**Comment by will-stone** [comment]
How strange. I can reproduce the same as you with a trailing slash. I set Firefox as my default browser, and it does quickly focus Finder. Which means it's something that affects all terminal apps. Well, at least it's not a Browserosaurus thing I suppose 🤷
