### ISSUE TITLE
No browsers shown to select from

### ISSUE THREAD

**Issue by NawalJAhmed** [will-stone/browserosaurus#353]
<p align="center">
  <img src="https://user-images.githubusercontent.com/11577850/103161698-b832ff00-47b3-11eb-80a9-6c4547fc0b54.png">
  <br>
  <em> Browserosaurus not showing any browsers</em>
</p>

Problem: Browserosaurus does not show any browsers to select from. The only thing shown is the link and a small rounded square at the bottom. The spacebar keyboard shortcut works. The browsers it should be showing are: Firefox, Chrome, Safari, Edge, Brave.

Version: v12.3.1

macOS: Mojave 10.14.6

Attempted Solutions: Uninstalling and reinstalling application, changing default browser, restarting system.

This did not used to happen. It used to work fine until one day it just stopped working correctly.

Thank you.

**Comment by will-stone** [comment]
Hi. Please try re-indexing Spotlight. There have been other issues reported where this solves the problem.

**Comment by will-stone** [comment]
https://github.com/will-stone/browserosaurus/issues?q=is%3Aissue+spotlight+is%3Aclosed
