### ISSUE TITLE
arm64/x86_64 universal binary?

### ISSUE THREAD

**Issue by i0ntempest** [will-stone/browserosaurus#357]
What's the reason for releasing two builds for to archs instead of just one universal build? A universal build would make maintaining B on homebrew cask easier too.

**Comment by will-stone** [comment]
Hi @i0ntempest, unfortunately it’s a limitation with Electron. You can read more here: https://www.electronjs.org/blog/apple-silicon#what-do-i-need-to-do

**Comment by i0ntempest** [comment]
Thanks for the info. Someone will have to make a new cask then.

**Comment by will-stone** [comment]
Hi @i0ntempest I've found that VSCode have solved the issue with which binary to download based on CPU architecture: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/visual-studio-code.rb I'm no Brew expert, but thought it might help if you are looking to update the cask?

**Comment by i0ntempest** [comment]
They actually have had this for a while now, but I didn't bother since I'm on x86. I'll open a PR soon adding arm64 builds to brew.

**Comment by will-stone** [comment]
Thank you 😘

**Comment by i0ntempest** [comment]
https://github.com/Homebrew/homebrew-cask/pull/100724

**Comment by will-stone** [comment]
Awesome 🥳
