### ISSUE TITLE
New upgrade really messed up

### ISSUE THREAD

**Issue by danielporto** [will-stone/browserosaurus#358]
No browser installed ins shown in the list.
Almost every button pushes to buy the partened browser or force a contribution.
Worse, the link provided to the new browser doesn't even open (as no installed browser is identified anymore).

**Comment by will-stone** [comment]
The answer to your problem is in the FAQ.

**Comment by danielporto** [comment]
Nothing in FAQ worked.
Still get an empty list of my browsers despite spotlight sees them.
It was working before, nothing changed but the app upgrade than it broke. 
Is there a way to install the previous version? 
It is also not very good to upgrade without consent or option to allow automatic upgrades.

**Comment by danielporto** [comment]
Never mind it.
I've switched to Multibrowser https://www.macupdate.com/app/mac/33861/multibrowser
It works as before.
