### ISSUE TITLE
Browserosaurus not "seeing" Waterfox

### ISSUE THREAD

**Issue by kiilliik** [will-stone/browserosaurus#359]
I am trying to use Browserosaurus v13.0.1 and cannot get it to recognize that Waterfox (version G3.0.2 (64-bit)  based on Gecko 78.6.0) is installed on my Mac.
It does know that Safari, Lion and Brave are available (among other unimportant browsers) on my Mac.

**Comment by will-stone** [comment]
Hi. Could you please post a screenshot of your browser picker? I'm curious as to what "Lion" is.

As for Waterfox, please run `mdls -name kMDItemCFBundleIdentifier -r /Applications/Waterfox.app` and see if it brings back the bundle identifier? You can see the value [here](https://github.com/will-stone/browserosaurus/blob/master/src/config/apps.ts#L145) that Browserosaurus is looking for.

**Comment by kiilliik** [comment]
I apologize, I meant Brave instead of Lion. Here is list of browsers shown: Safari, (Affiliate), Brave and last Vivaldi.

Running mdls -name kMDItemCFBundleIdentifier -r /Applications/Waterfox.app leaves net.waterfox.waterfox as a result.

**Comment by will-stone** [comment]
That's great, thanks! As you can see the bundle identifier looks to have changed from the one B uses:

```
net.waterfox.waterfoxcurrent
```

to

```
net.waterfox.waterfox
```

I'll update this in an upcoming release.

**Comment by kiilliik** [comment]
Great, looking forward to it! Thanks a lot and by the way Happy New Year.

**Comment by will-stone** [comment]
And to you too ☺️
