### ISSUE TITLE
Can you add SIdekick as new browser?

### ISSUE THREAD

**Issue by dmorizz** [will-stone/browserosaurus#360]
Hi there,

Can you add Sidekick - a relatively new browser to your list - as this is now my main browser to work from.
https://www.meetsidekick.com/

Thanks

**Comment by will-stone** [comment]
Hi, thanks for using Browserosaurus. I'm not currently accepting new feature requests. Please see the [contributing guidelines](https://github.com/will-stone/browserosaurus/blob/master/CONTRIBUTING.md).

**Comment by dmorizz** [comment]
OK no problem. Thanks for getting back to me so quickly.
