### ISSUE TITLE
[Feature Request] Add Chrome beta to the list of browsers detected

### ISSUE THREAD

**Issue by singhkays** [will-stone/browserosaurus#361]
I looked at the list of current detected browsers and found Chrome canary but not beta - https://www.google.com/chrome/beta/

https://github.com/will-stone/browserosaurus/blob/master/src/config/apps.ts 

Can this be added to the list?

**Comment by will-stone** [comment]
Hi. Thanks for using Browserosaurus. As per the [contributing guidelines](https://github.com/will-stone/browserosaurus/blob/ff39ac8091a867f58c761c790f9d816e2b2ef45f/CONTRIBUTING.md) I’m not accepting any more feature or browser requests. However, Chrome Beta is quite a biggie 😐 So could you please run the command from the readme (I would paste it but I’m writhing this on my phone) that allows you to find the bundle identifier and then paste the result here? Thanks.

**Comment by will-stone** [comment]
Ah, just seen the PR. Thanks 😊
