### ISSUE TITLE
Version error with Catalina

### ISSUE THREAD

**Issue by alastairhm** [will-stone/browserosaurus#363]
Getting the following version error message when using Mac Os Catalina.

![Screenshot 2021-01-14 at 16 17 01](https://user-images.githubusercontent.com/214005/104618045-2288e200-5684-11eb-9608-fa6932fc1636.png)

**Comment by will-stone** [comment]
Yep:

<img width="930" alt="image" src="https://user-images.githubusercontent.com/654103/104619158-75af6480-5685-11eb-95c8-b4102caed90f.png">

Although I was unaware that it completely crapped-out on lower versions 😢 

Please understand I can only support the version of macOS that I use; I am but one man. And I tend to keep up-to-date with latest macOS.

However, I'd love know a bit more context: did you update Browserosaurus and get this message, or was it after first install?

**Comment by will-stone** [comment]
I found this old bug, but it is still open and so I'm not sure what the answer is: https://github.com/electron/electron/issues/21257

**Comment by alastairhm** [comment]
Had it previously on Mojave, got a new laptop from work with Catalina on it (it department are a bit behind on their images).
So fresh install on the new machine.

**Comment by will-stone** [comment]
Just to make sure, did you install the Intel (x64) version?

**Comment by alastairhm** [comment]
I'll have a play about more tomorrow, pretty sure though, might have been an old link to the download though.

**Comment by alastairhm** [comment]
Maybe that's is something I can help out with, testing etc on previous version of the OS.

**Comment by alastairhm** [comment]
Not sure where downloaded it from when I raised the issue, but pulling the latest version from Github directly loads okay.

**Comment by will-stone** [comment]
That’s great news! And thanks for persevering 🙂
