### ISSUE TITLE
Default browser for a given domain

### ISSUE THREAD

**Issue by hungryphilomath** [will-stone/browserosaurus#364]
I use [Browser Select](https://github.com/zumoshi/BrowserSelect) on Windows (only because Browserosaurus is not available for it) and that app has an option to effectively link a domain to a browser.

For example when I click on a `google.com` link I have the option to click **Always** under Firefox in the Browser Select pop-up, and then all `google.com` links from that point on will always open in Firefox without prompting me. I also have all `localhost` links opening in Chrome as I prefer its DevTools.

A feature like this would be greatly appreciated!

**Comment by will-stone** [comment]
Hi @hungryphilomath Thank you for the suggestion. This is a common request. Browserosaurus does not provide a method for automatically selecting browsers, rather opting for the consistency that the picker window will show every time. If you would like to be able set rules, I highly recommend [Finicky](https://github.com/johnste/finicky) by John Sterling which can very easily be used in tandem with Browserosaurus, meaning the best of both worlds: a rules engine and a graphical interface.

**Comment by hungryphilomath** [comment]
Thanks for letting me know about Finicky! will give it a go!
