### ISSUE TITLE
Add Chrome user profiles to browser options

### ISSUE THREAD

**Issue by hungryphilomath** [will-stone/browserosaurus#365]
I use [Browser Select](https://github.com/zumoshi/BrowserSelect) on Windows (only because Browserosaurus is not available for it) and that app shows my Chrome user profiles as browser options, allowing me to open a link as a given user.

A feature like this would be greatly appreciated!

**Comment by will-stone** [comment]
Thanks @hungryphilomath. You can find more conversation about this request on this issue: https://github.com/will-stone/browserosaurus/issues/56 In summary: this is currently out-of-scope for this project.
