### ISSUE TITLE
Opening link in background does not close the Browserosaurus window for some browsers

### ISSUE THREAD

**Issue by adrian-travelbytes** [will-stone/browserosaurus#367]
Not sure when this started occurring but this is happening across two different machines for Safari.
When opening the link in the background (clicking the safari browser with Option key pressed) the webpage does open in Safari but the Browserosaurus window does not close/hide and remains onscreen.
Appears to only happen for Safari, tried the same using Brave browser and that does work as expected (the Browserosaurus window closes).

Safari 14.0.2
Mac Big Sur 11.1

**Comment by will-stone** [comment]
Hi. Thanks for reporting. Looks like Firefox is affected by this bug too. I think I've fixed this, release incoming...

**Comment by will-stone** [comment]
Okay, it should be fixed in v13.1.1
