### ISSUE TITLE
No longer working with High Sierra 10.13.6

### ISSUE THREAD

**Issue by rpsketch** [will-stone/browserosaurus#369]
I think this issue started with Browserosaurus version 13. Browserosaurus will install just fine, but will silently (no error message) crash on launch. The system log has the message: 
> com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000000f.Browserosaurus[2002]): Service exited due to signal: Illegal instruction: 4 sent by exc handler[0]

every time one of these crashes occur. Apologies if this is simply due to High Sierra no longer being supported, I couldn't find what the oldest supported OS version was.

edit: I have confirmed that this issue started with Browserosaurus version 13.0.1, version 12.3.1 still runs on High Sierra. However, due to the auto-update feature, I'm pretty sure it will start crashing again once I reboot or quit and it tries to apply the update.

**Comment by will-stone** [comment]
Hi @rpsketch. Thanks for using Browserosaurus. I only ever officially support the version of macOS that I use, which is usually the latest version as I like to keep up with current stable. High Sierra is pretty old on terms of macOS releases and I think Apple will soon announce its end-of-life, if it hasn't done so already. I'm not sure what you are using but up until recently, I had a 2015 MacBook and it ran Big Sur really well.
