### ISSUE TITLE
Links opens hangs when 'Low Power Mode' is ON with Endurance app

### ISSUE THREAD

**Issue by saneef** [will-stone/browserosaurus#370]
I regularly use [Endurance app](https://enduranceapp.com) when Macbook to extend usage time on while on battery. The links opened through Browserosaurus hangs (especially with Safari) when 'Low Power Mode' is ON. 

While this is happening if I switches OFF 'Low Power Mode', everything works normal. 

I'm not sure if this is problem with Browserosaurus or Safari itself.

**Comment by will-stone** [comment]
Hi @saneef. Thanks for using Browserosaurus. I can imagine it does hang. I've never used Endurance before but from a quick scan of the homepage, things like "Slow Down Your Processor" and "Put Background Apps to Sleep" sounds like it's setting up B for a fall. Please check other Electron-based apps and see if they struggle with Endurance as I'm not really sure whether there's anything explicit in Browserosaurus that would cause it to hang 🤷‍♂️ If you find there's a setting I can change to mitigate low-power apps, please feel free to submit a PR 😊

**Comment by saneef** [comment]
Hey @will-stone. Sorry for the false alarm. I found the culprit. There is a settings in Endurance app with which we can put the browsers to sleep while in background. 

<img width="668" alt="Screenshot 2021-02-04 at 1 50 31 PM" src="https://user-images.githubusercontent.com/81863/106867488-ac602400-66f3-11eb-914b-178b76680a6b.png">

Once it is disabled Safari works fine!

**Comment by will-stone** [comment]
🥳 Wooo! No worries. And thank-you for updating the issue thread as it'll help others who may be experiencing the same issues.
