### ISSUE TITLE
browsersaurus appearing in Mac searches

### ISSUE THREAD

**Issue by eranbeard** [will-stone/browserosaurus#371]
Whenever I launch a search on my Mac (Big Sur) using Command + Space, the first result is always a Browsersaurus one (presumably to launch a browser to search for the result). Is there any way to turn this off? i.e. I want my files and folders to appear first if they exist.

**Comment by will-stone** [comment]
Hi. Thanks for using Browserosaurus. This sounds like an issue with Spotlight (or whichever launcher you’re using). As for wanting to open web searches with B, yes I can imagine it does show B for this as it is technically your default browser. I’m no Spotlight expert, I prefer Alfred which I think uses a leading space to search for files, so please post back here if you find the answer to your problem, in case others have a similar question.
