### ISSUE TITLE
App Icon to fit macOS Big Sur (icon guidelines)

### ISSUE THREAD

**Issue by fabifabulousity** [will-stone/browserosaurus#372]
Hey there,
just a minor request...
Current app icon seems a bit large compared to the app icons that come with macOS Big Sur. Would be nice if you could consider "adjusted" app icon. Thanks :)

**Comment by will-stone** [comment]
Hi 👋 In theory you shouldn't really see the app icon other than in launchpad. If it's displaying in your dock, this was a bug that I hoped was fixed in a recent Electron update: https://github.com/will-stone/browserosaurus/issues/295
Please add a screenshot of where it doesn't look great, thanks 😄

**Comment by fabifabulousity** [comment]
Hello, I added a screenshot with some other app icons and Apple's own app (Time Machine) for reference. 
Browserosaurus's icon seems a little bit too large, imo. Additionally, please see this article by Apple: https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

![Bildschirmfoto 2021-02-23 um 17 34 24](https://user-images.githubusercontent.com/72652159/108875596-a5934580-75fd-11eb-8434-1f39f767e126.jpg)

**Comment by will-stone** [comment]
Thanks. I’ll take a look 🙂

**Comment by i0ntempest** [comment]
I made one for ya
![B_Big_Sur](https://user-images.githubusercontent.com/16017904/114275759-517ddc80-9a56-11eb-8332-316f62766bb5.png)
![Screen Shot 2021-04-10 at 23 41 04](https://user-images.githubusercontent.com/16017904/114275787-68243380-9a56-11eb-9007-f8dd083005f8.png)
[B_Big_Sur.icns.zip](https://github.com/will-stone/browserosaurus/files/6290192/B_Big_Sur.icns.zip)
Actually all I did was use a template and added a border stroke. The color of the new border is not exactly the same as the original icon but it's close enough.
Figma link in case u want to edit: https://www.figma.com/file/41KekQdnC2OQyH49pWdE8M/Browserosaurus-Big-Sur

**Comment by will-stone** [comment]
Thanks @i0ntempest! However, I do like to do all of my icon work in Affinity Designer.

I've been having a play with an updated icon using the template from https://macosicons.com/resources/macos-big-sur-app-icon

This is what I'm thinking for B v14:

<img src="https://user-images.githubusercontent.com/654103/114295404-f28f8600-9a9c-11eb-894b-f7e582a1f0ff.png" alt="" width="100"/>

<img src="https://user-images.githubusercontent.com/654103/114295404-f28f8600-9a9c-11eb-894b-f7e582a1f0ff.png" alt="" width="200"/>

<img src="https://user-images.githubusercontent.com/654103/114295404-f28f8600-9a9c-11eb-894b-f7e582a1f0ff.png" alt="" width="500"/>

**Comment by will-stone** [comment]
^ you can find the files for this in the [v14](https://github.com/will-stone/browserosaurus/tree/v14) branch.

**Comment by i0ntempest** [comment]
That's much better looking than my stuff. What's the expected release date of v14 if I may ask?

**Comment by will-stone** [comment]
Nah, I liked yours as it kept the old style, I just thought I'd have a refresh 😄 

Imminently. I'm just seeing if any dependencies can be upgraded.

**Comment by will-stone** [comment]
v14.0.1 released with updated icon.
