### ISSUE TITLE
Not available in 11.2 Default Browser menu

### ISSUE THREAD

**Issue by jjcaful** [will-stone/browserosaurus#373]
This issue is at least present in macOS version 11.2.2 with this post.
The Browserosaurus app is not showing up as an option to be selected in the Settings menu, under general, for the default browser. Upon first launch, it still shows the "choose default - switch to browserosaurus or keep x" prompt, but aside from that the user has no way to re-set the default browser if they somehow select another by mistake. 
Currently, it shows Safari as the default despite routing to browserosaurus if "chosen" as the default on the first launch. 

<img width="666" alt="Screen Shot 2021-02-25 at 7 12 38 PM" src="https://user-images.githubusercontent.com/56008378/109236346-6f8cc780-779d-11eb-9765-2d3433d20d06.png">

**Comment by will-stone** [comment]
Thanks @jjcaful, this looks to be an issue with macOS: https://github.com/will-stone/browserosaurus/issues/317

**Comment by stgarf** [comment]
/sub. Is this still a dupe? Everything was great on Big Sure until the `11.2.2 (20D80)` update from 2-3 days ago. From that point `B` disappeared from the `Default web browser` menu.

**Comment by kopach** [comment]
Same issue in my case. Browserosaurus isn't in list of default browsers in system preferences. But still was able to make it default using a [solution from above](https://github.com/will-stone/browserosaurus/issues/373#issuecomment-790865619). Basically, if Browserosaurus isn't set as default browser - there will appear "Set as default browser" button in the setting's menu of Browserosaurus
<img width="302" alt="image" src="https://user-images.githubusercontent.com/8749624/115368958-e657a700-a1c7-11eb-87a4-ff4f4ba03c8c.png">

**Comment by will-stone** [comment]
Yeah, I'll reopen this. It looks Like John from Finicky found a solution. I had a play with it yesterday but I couldn't get the `plist` items to work with Electron Forge/Packager. Any tips welcomed 👍

**Comment by will-stone** [comment]
Fixed in upcoming release.
