### ISSUE TITLE
Not showing Safari

### ISSUE THREAD

**Issue by bnaman50** [will-stone/browserosaurus#374]
It does not show the Safari browser when I click on a link. Could you please fix this?

<img width="912" alt="image" src="https://user-images.githubusercontent.com/5251592/109440167-db1da180-79f6-11eb-80b3-3985fc90a8bc.png">

Thanks, 
Naman

**Comment by will-stone** [comment]
Interesting 🤔 I obviously need to make this more obvious: the window is resize-able. Can you see the very faint scroll bar on the right? Safari is there it’s just below everything else. You can resize the window so all your browsers are visible or keep it small and use scroll.

Browserosaurus used to resize to the size required to show all browsers, but the code required to do this was just a pain to maintain whenever new features were added. Hence why I went for the manual approach, but it’s really a set and forget operation (B saves and restores its dimensions). 

Thanks for using Browserosaurus.

**Comment by bnaman50** [comment]
Thanks for your quick response, @will-stone . There is a scrollbar over there with was not apparent to me. It is working properly now. 

<img width="623" alt="image" src="https://user-images.githubusercontent.com/5251592/109464899-07541500-7a2d-11eb-9483-09554295313e.png">

P.S. - Love this application. 

Thanks again, 
Naman
