### ISSUE TITLE
Window corners not rounded

### ISSUE THREAD

**Issue by maharjanaman** [will-stone/browserosaurus#375]
There is the presence of white corners when browserosaurus pops up over white background.
<img width="499" alt="Screen Shot 2021-03-18 at 13 02 37" src="https://user-images.githubusercontent.com/14164484/111587790-c6108300-87ea-11eb-8b2f-aad13f103be1.png">

**Comment by will-stone** [comment]
Thanks. They're actually transparent. It's a known bug on Electron. Hopefully it'll be fixed upstream soon: https://github.com/electron/electron/issues/27080

**Comment by will-stone** [comment]
Looks like the fix for this is coming soon: https://github.com/electron/electron/pull/28655

😄

**Comment by will-stone** [comment]
Fixed in v14.1.0
