### ISSUE TITLE
Broken icon for Waterfox 

### ISSUE THREAD

**Issue by boldlion** [will-stone/browserosaurus#376]
I've been using browserosaurus for a while, it all works as expected, but there's this tiny bug with an icon. It's the only icon that's not being displayed properly for whatever reason.

<img width="460" alt="Screenshot 2021-03-21 at 12 08 14 PM" src="https://user-images.githubusercontent.com/43475912/111901006-36631280-8a3e-11eb-83f2-710632f0beb1.png">

**Comment by will-stone** [comment]
Hi. Thanks for reporting. That's strange, maybe the logo repo updated the location. I'll take a look.

**Comment by WorkInProgress-Development** [comment]
Firstly, can confirm that this is occurring for me as well.
Secondly, the icon is one of those manually installed/defined by logos.ts to be in a local file, as opposed to the browser-logos repo. Other apps, such as Finicky, which are also defined as a local file, work fine.
