### ISSUE TITLE
[bug or feature] browserosaurus does not queue URL open requests

### ISSUE THREAD

**Issue by slippycheeze** [will-stone/browserosaurus#377]
## the problem
- I opened multiple URLs that went to browserosaurus to open using a command line tool.
- I saw a prompt, but it changed a couple times, and only the last item sent persisted.

## what I expected
- browsersosaurus would queue the URLs
- I could make a choice for each of them, and it'd be applied
- the UI would pop up again like it did the first time after each decision
  - or the UI would not activate the target browser
- I'd expect FIFO choices, but LIFO would also make sense I guess.

## how to reproduce
```shell
brew home libatomic_ops libxshmfence talloc tarantool tmux-mem-cpu-load volatility
```

...or anything like that.  you could use a for loop and open(1) to trigger it just as well.  simply open multiple URLs one after another.

**Comment by will-stone** [comment]
As you can probably guess from [my answer](https://github.com/will-stone/browserosaurus/issues/378#issuecomment-806546415) to your other issue, this isn't going to make the cut either. However there's probably quite an interesting additional reason why for this one...

Once upon a time, B did keep a history of clicked links. This would have worked nicely for you as all your opened links would have fired into the history. However, it was pointed out to me that this could be a security issue. Anyone wanting to keep there clicked links private (in case their machine was seized, for example) would need to remember to clear B's history too. Which meant deleting or altering the config file. As a compromise, B now remembers only the last link clicked, which is only stored in local memory and can be cleared by either clicking something else, hitting delete key when B is open, or by simply closing B.

Thanks again for using Browserosaurus 🙂
