### ISSUE TITLE
[wishlist] an option to prompt in a fixed position on screen, not at mouse cursor

### ISSUE THREAD

**Issue by slippycheeze** [will-stone/browserosaurus#378]
## the problem I want to solve
I use the finicky & browsersaurus combination to automatically route most URLs that I open outside the browser, and then to prompt interactively if the system can't figure it out.

Probably 95 percent of the time I open an "ambiguous" URL I *don't* use the mouse.  I use keyboard shortcuts, keyboard navigation to the clickable "link" item in an app, or tools like `brew home` that automatically open a URL.

I'd really like the browserosaurus prompt to show up in the middle of the screen, centred at 50%/50%, or better yet, 33%/50%, so that I know where it'll be showing up for me to make the decision.

I believe that the current behaviour—at mouse cursor—is the best choice for many people.  I'm not one of them, though, so while I normally consider a "preference" to be the worst curse an application can have, sometimes there are fundamentals where it is worth it.

I'm pretty sure that it used to do exactly that, but recently it has started showing the popup where my mouse cursor is.  That leads to it being way out of my point of focus most of the time—I'm looking where the text cursor is, not at the mouse.

(In fact, most of the time the cursor isn't just shoved away into (normally) the bottom-left corner, it is also hidden by the system and/or the tool I'm using, so I can't even have that as a cue to where it'll show up.)

**Comment by will-stone** [comment]
Hi! Thanks for using Browserosaurus. As per the [contributing guidelines](https://github.com/will-stone/browserosaurus/blob/master/CONTRIBUTING.md), B is now considered _Public Feature Complete_. What this essentially means is that I'm not accepting anything other than bug reports, but Browserosaurus may still gain features that I find useful. Unfortunately, this is not something I found worked well. As you say, B did indeed go through a time where it appeared in the middle of the screen, but I found the mouse travel irritating and so once I figured out a fairly easy/maintainable method of keeping it near the mouse again, I returned the original behaviour of following the mouse. 

I like this:

> "preference" to be the worst curse an application can have

This sums-up nicely where I got to in this project; I no longer wanted to maintain options for others that I do not use.

Thanks again, and please don't feel like you cannot suggest features as you never know: it may be something I didn't realise I wanted 😄 If you'd like to continue any conversation privately, there are contact details on [my website](https://wstone.io/).
