### ISSUE TITLE
Request: Choose to open in new window

### ISSUE THREAD

**Issue by qeisar** [will-stone/browserosaurus#379]
It would a nice feature if there is a way to choose whether to open the link as a new window in the selected browser. Currently, if the selected browser is open, then the new link will be opened as a new tab in the same window.

Case scenario of usefulness:
This is will be practically useful for people working on multiple screens. E.g. I want to open a link from an application on screen1, and the browser is already opened on screen2. Open in a new window will make the link open in screen1, which is a friendly behavior in such a case.

Thanks

**Comment by will-stone** [comment]
Hi! Thanks for using Browserosaurus. As per the [contributing guidelines](https://github.com/will-stone/browserosaurus/blob/master/CONTRIBUTING.md), B is now considered _Public Feature Complete_. What this essentially means is that I'm not accepting anything other than bug reports, but Browserosaurus may still gain features that I find useful.

This feature is not something I’m looking to add right now, but thanks again, and please don’t feel like you cannot suggest features, as you never know: it may be something I didn’t realise I wanted 😄 If you’d like to continue any conversation privately, there are contact details on  [my website](https://wstone.io/) .
