### ISSUE TITLE
It hangs up 

### ISSUE THREAD

**Issue by Knvgpt** [will-stone/browserosaurus#380]
hey it's an amazing app, but whenever the contribute thing pops up the things just hangs for a minute or two. and during which I can't open any links. it happened to me in the middle of the quiz. which wasn't good. could you please look into it. thanks.

**Comment by will-stone** [comment]
Hi. Hmmm, could you please elaborate on "the contribute thing pops up"? Screenshots or videos would help. Thanks.

**Comment by Knvgpt** [comment]
Sure next time it happens I will make sure to do that, thanks for the reply.

**Comment by will-stone** [comment]
Closing. Please reopen when you can provide more details.
