### ISSUE TITLE
I have bought carrot, how can I avoid this link (https://www.buymeacoffee.com/wstone) from opening now?

### ISSUE THREAD

**Issue by ageetey** [will-stone/browserosaurus#381]

**Comment by ageetey** [comment]
Transaction ID: 3D106428DF093080S
Date: February 28, 2021

**Comment by will-stone** [comment]
Hi. Thanks for buying a carrot. How is it the link opening? You shouldn't see the link in general use.

**Comment by will-stone** [comment]
Closing. Please reopen when you can provide more details.
