### ISSUE TITLE
Please add a link unshorten function/preview like https://linkunshorten.com/

### ISSUE THREAD

**Issue by cocoonkid** [will-stone/browserosaurus#382]
Please add a link unshorten function/preview
 like https://linkunshorten.com/

preview like :https://apps.apple.com/us/app/link-unshortener/id1506953658?mt=12

This would be very neat to have. Worth many many carrots :-)

**Comment by will-stone** [comment]
Hi @cocoonkid, it's a great suggestion but it would unfortunately require a call to an external service which I don't think I am comfortable with, as it presents security and privacy concerns. Thanks 😄

**Comment by cocoonkid** [comment]
Fully understand but I thought it could be handled internally like in the app from the second link.

This would be so helpful and add a lot of security and privacy.

**Comment by will-stone** [comment]
I’m not quite sure how this would work without sending a request. I’m happy to see a PR if you know how this is done, or a more detailed step by step I can follow. Otherwise maybe it’s possible you could combine B with one of these apps...?
