### ISSUE TITLE
Can you add support for Yandex browser please?

### ISSUE THREAD

**Issue by netpastor** [will-stone/browserosaurus#383]
https://browser.yandex.com/

**Comment by will-stone** [comment]
Hi. Yandex should already be supported: https://github.com/will-stone/browserosaurus/blob/master/src/config/apps.ts#L153

Please can you find the bundle identifier to see if it's changed? https://github.com/will-stone/browserosaurus#finding-bundle-identifier-for-an-app

**Comment by netpastor** [comment]
ru.yandex.desktop.yandex-browser
But I still can't add it 
Settings - Reload didn't help

**Comment by will-stone** [comment]
Strange. Which version of macOS are you using?

**Comment by netpastor** [comment]
Macos Catalina 10.15.7

**Comment by will-stone** [comment]
Okay, well I'm not sure if that's the issue but I can only support the version of macOS that I currently use. I generally stay on latest macOS. Let me know if it's still an issue when you upgrade to Big Sur.
