### ISSUE TITLE
Spotify logo is visible in Browserosaurus menu and link pop ups ( screenshot link in desc )

### ISSUE THREAD

**Issue by harshit97** [will-stone/browserosaurus#384]
What can I do the remove the spotify logo ?
I do have the app installed on my mac.
https://ibb.co/0rWFQnx

**Comment by will-stone** [comment]
Thanks for using Browserosaurus. Please open the setting menu (bottom-right icon) and click the visibility toggle "eye" button.

**Comment by harshit97** [comment]
Don't see it. See screenshot - [https://ibb.co/zP8vWNY](url)

**Comment by will-stone** [comment]
Scroll down

**Comment by harshit97** [comment]
Ohhhhh ! 🤦🏽‍♂️
Thank you soo much !

**Comment by will-stone** [comment]
No worries. I might be able to force the scroller to show which will make it more obvious. I’ll reopen the issue to remind me 😊

**Comment by will-stone** [comment]
v14.0.1 released with more visible scrollbar.

**Comment by harshit97** [comment]
I see it ! Thank you soo much Will !
