### ISSUE TITLE
Only one Chrome-branched browser is detected

### ISSUE THREAD

**Issue by korniux** [will-stone/browserosaurus#387]
I have two Chrome browsers - latest Chrome and Chrome Dev, and only latest Chrome is detected.

**Comment by will-stone** [comment]
Hi. Here's the versions B supports: https://github.com/will-stone/browserosaurus/blob/85ebba418d493fde515f744387a4786d1c130b06/src/config/apps.ts#L49

If the one you're using is missing, can you please find it's bundle identifier? https://github.com/will-stone/browserosaurus#finding-bundle-identifier-for-an-app

**Comment by korniux** [comment]
```
$ mdls -name kMDItemCFBundleIdentifier /Applications/Google\ Chrome\ Dev.app

kMDItemCFBundleIdentifier = "com.google.Chrome.dev"
```

**Comment by will-stone** [comment]
Nice, thanks. Well, as per the [contriubuting guidelines](https://github.com/will-stone/browserosaurus/blob/85ebba418d493fde515f744387a4786d1c130b06/CONTRIBUTING.md), I'm not accepting any browser requests. However, I can imagine Chrome Dev is a fairly common one, and we may as well support the full plethora of Chrome channels. Please feel free to submit a PR, this is a good example of a recent one: https://github.com/will-stone/browserosaurus/pull/362/files
