### ISSUE TITLE
Support for opening video call meeting links directly in the corresponding app

### ISSUE THREAD

**Issue by harshit97** [will-stone/browserosaurus#389]
With remote work being the future, it'd be great if I could click on a meeting link in my calendar and mail app and be redirected directly to the desktop version of that app.
For example -  I get an invite on my outlook email app for a teams meeting, I click the meeting link and I choose the Teams logo to directly open the Teams desktop app and jump into the meeting.

**Comment by will-stone** [comment]
Hi! Thanks for using Browserosaurus. As per the [contributing guidelines](https://github.com/will-stone/browserosaurus/blob/master/CONTRIBUTING.md), B is now considered _Public Feature Complete_. What this essentially means is that I'm not accepting anything other than bug reports, but Browserosaurus may still gain features that I find useful.

This feature is not something I’m looking to add right now, but thanks again, and please do not feel like you cannot suggest features, as you never know: it may be something I didn’t realise I wanted 😄 If you’d like to continue any conversation privately, there are contact details on  [my website](https://wstone.io/) .
