### ISSUE TITLE
Edge browser got lost

### ISSUE THREAD

**Issue by albenik** [will-stone/browserosaurus#392]
Edge Version 90.0.818.51 (Official build) (64-bit)
MacOS BigSur 11.3

After Edge updated and my MacBook restarted the Edge browser went off from my Browserosaurus.
App refresh browsers list/restart/reinstall did not help.

**Comment by albenik** [comment]
```
mdls /Applications/Microsoft\ Edge.app
kMDItemFSContentChangeDate = (null)
kMDItemFSCreationDate      = (null)
kMDItemFSCreatorCode       = ""
kMDItemFSFinderFlags       = (null)
kMDItemFSHasCustomIcon     = (null)
kMDItemFSInvisible         = 0
kMDItemFSIsExtensionHidden = (null)
kMDItemFSIsStationery      = (null)
kMDItemFSLabel             = (null)
kMDItemFSName              = (null)
kMDItemFSNodeCount         = (null)
kMDItemFSOwnerGroupID      = (null)
kMDItemFSOwnerUserID       = (null)
kMDItemFSSize              = (null)
kMDItemFSTypeCode          = ""
```

**Comment by will-stone** [comment]
Thanks. Can you please find the bundle id? The command is in the readme.

**Comment by albenik** [comment]
@will-stone I think 

Here is the result of the command from the README

```
> mdls -name kMDItemCFBundleIdentifier -r "/Applications/Microsoft Edge.app"
(null)
```

But in my previous message I already provided the full output of `mdls` command without arguments.
There are no meta returned at all.
For the example other browsers have the meta and especially `kMDItemContentType` key.

I think that the problem is the missing package meta in the latest Edge version :(

However, Edge still visible for MacOS itself as a browser in the "Default browser" dropdown in the system config.

**Comment by will-stone** [comment]
I couldn’t see bundle ID in your output, which is why I asked.

How odd. Have you reported it to MS? It was my understanding that every app needs a bundle ID 🤷‍♂️

**Comment by albenik** [comment]
> I couldn’t see bundle ID in your output, which is why I asked.

This is because `(null)` returned instead of actual ID.

> One thing you may want to try: re-index your Spotlight by deselecting apps and reselecting it.

Magic! This helped! Thanks a lot!

Now `mdls` show proper ID and Edge got returned to the Browserosaurus list.

```
> mdls -name kMDItemCFBundleIdentifier -r "/Applications/Microsoft Edge.app"
com.microsoft.edgemac
```
