### ISSUE TITLE
Lists browsers that are uninstalled in the past

### ISSUE THREAD

**Issue by saneef** [will-stone/browserosaurus#395]
_The problem occurs only when time machine backup hard disks are connected._

The bug is with the package `app-exists`, and I have made a PR with the solution, sindresorhus/app-exists#4.

**Comment by will-stone** [comment]
Thanks 🙂

**Comment by saneef** [comment]
Got it fixed in [app-exists v2.1.0](https://github.com/sindresorhus/app-exists/releases/tag/v2.1.0).

**Comment by will-stone** [comment]
Awesome, I'll include it in the next release. Thanks!

**Comment by will-stone** [comment]
Fixed in v14.1.2
