### ISSUE TITLE
High cpu usage when opening for the first time / delay opening

### ISSUE THREAD

**Issue by dylan-chong** [will-stone/browserosaurus#397]
Mac os 11.3
Browserosaurus 14.0.2

When opening Browserosaurus (when it is completely closed), it will use 99% CPU for about 15 seconds.
This is a problem because clicking on a link when browserosaurus is closed, will do nothing for 15 seconds

**Comment by will-stone** [comment]
Probably an issue with Electron. I’m going to close this as the FAQ does state that B needs to be running in the background for the best performance. And this will probably improve with Electron updates.
