### ISSUE TITLE
Some browsers not showing

### ISSUE THREAD

**Issue by will-stone** [will-stone/browserosaurus#400]
Hello @will-stone 🙂  I'm using Browserosaurus for months and one of these last updates made most of the browsers disappeared. I already updated to the latest version, refreshed the Browserosaurus, and restarted it. 🤔

_Originally posted by @Tragio in https://github.com/will-stone/browserosaurus/issues/399#issuecomment-845730645_

**Comment by will-stone** [comment]
@Tragio can you please send a screenshot and let me know which browsers are missing?

Also, which version of macOS and B are you using?
For Browserosaurus, you can hover over the "Buy me a carrot" button in the settings pane.

Thanks 🙂

**Comment by Tragio** [comment]
@will-stone thank you! I'm using macOS 11.3.1 and Browserosaurus 14.1.4. The browsers that I'm noticing are Brave and Chromium.

![Screenshot 2021-05-21 at 08 51 04](https://user-images.githubusercontent.com/5109593/119102600-1b972500-ba12-11eb-8f38-0a9c2e04e55f.jpg)

**Comment by will-stone** [comment]
Odd, have you tried resetting your Spotlight index?

- Go to System Preferences > Spotlight.
- Untick Applications and tick it again.
- Wait an arbitrary amount of time, say a couple of minutes.
- Restart Browserosaurus (possibly restart machine).

---

Where is Brave.app installed?

---

Is it the stable (non beta/canary/dev) version?

---

What do these commands produce?

```sh
mdfind "kMDItemContentType == 'com.apple.application-bundle' && kMDItemCFBundleIdentifier == 'com.brave.Browser'"
```

```sh
mdls -name kMDItemCFBundleIdentifier -r /Applications/Brave.app # <- update to your location of installed Brave browser
```

**Comment by Tragio** [comment]
@will-stone 

I did the Spotlight Reindex but appears to be all the same. Also restarted the machine.

The Brave is installed here: /Applications/Brave\ Browser.app 

The first command didn't return anything.
The second one I got this:
`mdls -name kMDItemCFBundleIdentifier -r /Applications/Brave\ Browser.app 

(null)%`

**Comment by will-stone** [comment]
Okay, well I'm not sure what to say: Browserosaurus uses `mdls` to determine the existence of browsers, if it's not working on your machine there's not much we can do. I'd say it suggests Spotlight issues, but that's just a guess.

**Comment by Tragio** [comment]
@will-stone not sure what we did but now it's working. Really thank you for your support and amazing work 🙂

**Comment by will-stone** [comment]
Nice. Probably a slow or corrupt Spotlight index.
