### ISSUE TITLE
Browser icons are not visible

### ISSUE THREAD

**Issue by isyara** [will-stone/browserosaurus#402]
Hi,

I'm on MacOs BigSur 11.4 with the latest version of Browserosaurus app.
When i would like open link,  Browserosaurus purpose only "Contribute"  icon but not browsers icons (cf screenshot).

<img width="541" alt="Browserosaurus" src="https://user-images.githubusercontent.com/2648791/120443314-cdc1db80-c386-11eb-9a95-5b91344ff41d.png">

If i press letter C Browserosaurus open to Chrome

**Comment by will-stone** [comment]
Hi, have you tried resetting your Spotlight index?

- Go to System Preferences > Spotlight.
- Untick Applications and tick it again.
- Wait an arbitrary amount of time, say a couple of minutes.
- Restart Browserosaurus (possibly restart machine).

**Comment by isyara** [comment]
I finally found it.  This was due to a Spotlight indexing problem.

**Comment by will-stone** [comment]
Awesome 😄
