### ISSUE TITLE
Request for enhancement: editable URL text field in the UI

### ISSUE THREAD

**Issue by mlavi** [will-stone/browserosaurus#407]
Hi Will, thanks for Browserosaurus!

I find myself often wishing I could paste and/or edit the URL in UI before choosing which browser to open it with, would it be possible to make the URL field an editable text box?

I realize URLs can be very long, so a flexible text box would be an involved request, but even a static sized text box would be helpful!

**Comment by will-stone** [comment]
Hi @mlavi thanks for posting this here as I like to keep all bug and feature request discussions public, and thanks for supporting my Open Source work.

Browserosaurus is currently considered [_public feature complete_](https://github.com/will-stone/browserosaurus/blob/6da4623a8b43177b5bc62ff8fb431038b186872b/CONTRIBUTING.md) which is basically a way of me saying that I am continuing to develop the project but feature requests must align with my ideas for the app.

This is not to say this isn't something I'd like to add, I just need to understand the value first.

I'll just get pasting URLs out of the way first. Pasting URLs into Browserosaurus I believe to be a moot point: if you're pasting, you might as well open the browser using Spotlight/Alfred/Launchpad/Dock and paste as would have done normally. Pasting URLs is exactly what Browserosaurus was designed to mitigate.

However, editing a clicked URL may be reasonable but what is it you'd like to edit? Can you please give me a bulleted example workflow of when this would be useful? Describe the interactions as if I were blind: e.g.

- I open Slack.
- I click a URL that someone has sent me.
- Browserosaurus opens as it is set as the default browser.
- I edit the URL <- explain why, what is a common scenario for doing this?
- I select Chrome to continue opening the edited URL

This information will greatly help me understand how people are using Browserosaurus.

Thanks 🙂

**Comment by will-stone** [comment]
I'm going to close this but please reopen if you'd still like to discuss.
