### ISSUE TITLE
Where is the Quit button for Browserosaurus?

### ISSUE THREAD

**Issue by strafer** [will-stone/browserosaurus#410]
I feel stupid for asking this but I can't find any way to quit browsersaurus while it's running. There doesn't seem to be a Quit button in the user interface. I have to force quit it in Activity Monitor.

Is this by design or is it not functioning properly on my Mac running Mojave?

**Comment by will-stone** [comment]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/654103/121591539-8811ac80-ca31-11eb-9406-75dd68053d2d.png">

<img width="536" alt="image" src="https://user-images.githubusercontent.com/654103/121591614-9e1f6d00-ca31-11eb-8e90-e489e9c00c36.png">

You can also use the universal macOS shortcut of <kbd>Command + Q</kbd> whilst the picker has focus.

**Comment by strafer** [comment]
Thank you! 

I do think that Quit UI is maybe a little too subtle since it's dependent on pressing a gear icon and then having to notice a very minor icon change. Perhaps it could be made more obvious in a future version.

**Comment by will-stone** [comment]
No worries. It will be more obvious in an upcoming release, it's part of the v15 plans (which are just in my head at the moment 🙂).

Please bear in mind that Browserosaurus is designed to be kept running in the background. Quitting it will mean that it will take significantly longer to display when a URL is sent to it.
