### ISSUE TITLE
Feature request : ability to reorganize icons

### ISSUE THREAD

**Issue by sushione** [will-stone/browserosaurus#411]
Would be great if we were able to freely reorganize browser's icons
(like default first, firefox second, brave third...)

**Comment by will-stone** [comment]
Thank you for your email, and posting here. This is something that will be easier to add in the upcoming Preferences window. However, it may not be something that I require, so therefore I'll leave it as "considering" for now. Please note that the order is currently determined by the hotkeys.

**Comment by will-stone** [comment]
As this will require a lot of work with drag and drop, I think the effort to value-added is just too high for this to be something worth working on. Thank you for the suggestion though, and I'm always happy to consider any more ideas.
