### ISSUE TITLE
Small browser's icons

### ISSUE THREAD

**Issue by sushione** [will-stone/browserosaurus#412]
Can you make it possible to change browser's icons to smaller size ?

**Comment by will-stone** [comment]
Thank you for your email, and posting here. This is something that is unlikely to come to fruition for a couple of reasons:

- Configuration is the bane of the developer, especially visual stuff like sizing. It means when changes happen, many more variations have to be tested.
- Whilst it may seem sensible to add this to option, Browserosaurus is not a commercial app and I'm likely to find a size of tile that I like and stick with it.
