### ISSUE TITLE
Support for Safari Tab Groups (macOS 12)

### ISSUE THREAD

**Issue by rafael-at** [will-stone/browserosaurus#417]
Let me choose in which Tab Group to open a link in Safari

**Comment by will-stone** [comment]
Hi! Thanks for using Browserosaurus. As per the [contributing guidelines](https://github.com/will-stone/browserosaurus/blob/master/CONTRIBUTING.md), B is now considered _Public Feature Complete_. What this essentially means is that I'm not accepting anything other than bug reports, but Browserosaurus may still gain features that I find useful.

This feature is not something I’m looking to add right now, but thanks again, and please feel free to suggest more features, as you never know: it may be something I didn’t realise I wanted 😄 If you’d like to continue any conversation privately, there are contact details on  [my website](https://wstone.io/).

---

Browserosaurus will only ever officially support the version of macOS that I am currently using (for obvious reasons 😆). I generally keep up-to-date with current stable versions of macOS. Once I upgrade to macOS 12, I will see what's involved in adding this, but I don't use Safari and if it's anything like Chrome Profiles, I won't be including it.

Oh and welcome to GitHub! I can see that this is the first ever issue you have opened. Remember, politeness is king. If you're asking someone to do something for you, for free (which is essentially what Open Source boils down to), always remember that _please_ and _thank you_ goes a long way 😇
