### ISSUE TITLE
Librewolf

### ISSUE THREAD

**Issue by ph00lt0** [will-stone/browserosaurus#418]
Could you please add Librewolf (https://librewolf-community.gitlab.io/) browser to Browserosaurus. 

Librewolf is a hardened version of Firefox providing better security and privacy settings, actively maintained, and always up to date unlike other forks.

**Comment by will-stone** [comment]
Hi. I’ve had a couple of requests for this now, happy to accept a PR.

**Comment by ph00lt0** [comment]
@will-stone will have a go at this later this week. Would be happy to help.
