### ISSUE TITLE
Browsers are not detected on macOS 11.5.1 (20G80)

### ISSUE THREAD

**Issue by kondratyev-nv** [will-stone/browserosaurus#421]
Hi! Thanks for the tool!

I was using Browserosaurus for some time, but since recently, it does not detect any browsers installed.
<img width="403" alt="image" src="https://user-images.githubusercontent.com/4085884/127649138-31e95bf6-1336-4292-816f-f1cc045b4bb3.png">
(The only one detected is Finicky)
However, I can see a bunch of them in system preferences
<img width="325" alt="image" src="https://user-images.githubusercontent.com/4085884/127649239-c2942d16-eb7e-4f8a-84b3-556bc0b5cecc.png">

I believe this became an issue after an update to the latest macOS 11.5.1 (20G80).

Thank you in advance!

**Comment by will-stone** [comment]
Please try this: https://github.com/will-stone/browserosaurus/issues/402#issuecomment-852820131

**Comment by kondratyev-nv** [comment]
Thank you for the suggestions. Hmm, it kind of helped... Right now, Browserosaurus discovers 2 browsers (Finicky and Edge), but all others are still missing. I've tried to check the Applications checkbox a couple of times, waited for a couple of mins each time, and tried to restart multiple times. Still no luck ☹️ (I can see suggestions in Spotlight for all browsers though). Additionally, I've tried to re-install Browserosaurus.

**Comment by will-stone** [comment]
Okay. Browserosaurus checks for the presence of browsers by seeing if there's a response by looking-up its bundle identifier. For example, this:

```
mdls -name kMDItemCFBundleIdentifier -r /Applications/Firefox.app
```

should return this:

```
org.mozilla.firefox
```

**Comment by will-stone** [comment]
And this:

```sh
mdfind "kMDItemContentType == 'com.apple.application-bundle' && kMDItemCFBundleIdentifier == 'org.mozilla.firefox'"
```

should return this:

```zh
/Applications/Firefox.app
```

**Comment by kondratyev-nv** [comment]
Ok, I see this becomes weirder 😅 Both commands seem to work fine
```
[15:18:53] ~
 > mdls -name kMDItemCFBundleIdentifier -r /Applications/Firefox.app
org.mozilla.firefox%

[15:19:02] ~
 > mdfind "kMDItemContentType == 'com.apple.application-bundle' && kMDItemCFBundleIdentifier == 'org.mozilla.firefox'"
/Applications/Firefox.app
```

**Comment by will-stone** [comment]
Just to confirm, the browsers you'd like to show are set to "visible" in the Preferences?

<img width="712" alt="image" src="https://user-images.githubusercontent.com/654103/127668766-08465b8a-b1aa-44b6-a87f-aa702a658453.png">

**Comment by kondratyev-nv** [comment]
I mean I don't even see those in the list
<img width="391" alt="image" src="https://user-images.githubusercontent.com/4085884/127668962-5b6d64fc-1da9-4cf3-859b-8755268d59f4.png">

<img width="592" alt="image" src="https://user-images.githubusercontent.com/4085884/127669050-e8a0a073-45aa-4b78-91a6-d71b27e27f49.png">

**Comment by kondratyev-nv** [comment]
Is there any way to maybe see logs or something? So I can share something more specific?...

**Comment by will-stone** [comment]
Sorry, no logs. Which version of B are you using? You can find this in the About section of the Preferences window.

**Comment by kondratyev-nv** [comment]
<img width="281" alt="image" src="https://user-images.githubusercontent.com/4085884/127680728-fc58e2ea-316b-482d-a73b-978265073bcb.png">

15.1.2, seems to be the latest

**Comment by will-stone** [comment]
To be honest, I’ve no idea, sorry. If you find something that fixes it, please report back here in case others have the same issue.
