### ISSUE TITLE
"0 compatible apps" shown even after rescan

### ISSUE THREAD

**Issue by rahulghanate** [will-stone/browserosaurus#422]
Recently I started facing this issue, when browserosaurus doesn't show browser apps installed on my mac.
I have Chrome, Safari and Edge installed on mac, but none of them are shown in the popup window whenever I click a link.
I see browserosaurus has Files access(I have added Accessibility permissions) to it in Privacy settings.

I tried uninstalling and reinstalling latest version of browserosaurus, but still it shows no apps.

I tried rescan multiple times, but still doesn't show any apps.

Attached screenshots to help.
<img width="668" alt="Screenshot 2021-07-30 at 5 50 52 PM" src="https://user-images.githubusercontent.com/16386706/127738439-f13dbf4f-ac68-4c06-866b-ab69e04af4ca.png">
<img width="604" alt="Screenshot 2021-07-31 at 4 31 53 PM" src="https://user-images.githubusercontent.com/16386706/127738442-f977e132-47eb-455f-877d-a32874601676.png">
<img width="426" alt="Screenshot 2021-07-31 at 4 42 07 PM" src="https://user-images.githubusercontent.com/16386706/127738444-2830c39b-1ed9-4ab2-ac3c-1e134d0f8161.png">
<img width="368" alt="Screenshot 2021-07-31 at 4 44 16 PM" src="https://user-images.githubusercontent.com/16386706/127738445-1cf396d4-e4e1-42c0-9aad-0eafc31556ab.png">
<img width="671" alt="Screenshot 2021-07-31 at 4 50 34 PM" src="https://user-images.githubusercontent.com/16386706/127738447-be494ac0-4790-45cf-98f4-3c195d730193.png">

**Comment by rahulghanate** [comment]
Seems duplicate of https://github.com/will-stone/browserosaurus/issues/421

**Comment by rahulghanate** [comment]
Found issue from https://github.com/will-stone/browserosaurus/issues/402
I had disabled spotlight indexing as it was heating and consuming cpu on my mac with command,
sudo mdutil -a -i off
And the below command was showing null result, 
$ mdls -name kMDItemCFBundleIdentifier -r /Applications/Google\ Chrome.app
(null)%

After enabling it with, sudo mdutil -a -i on, it now shows correct name,
$ mdls -name kMDItemCFBundleIdentifier -r /Applications/Google\ Chrome.app
com.google.Chrome%

**Comment by rahulghanate** [comment]
Closing the issue.

**Comment by will-stone** [comment]
Ooo, well thanks for finding and posting your solution 🙂
