### ISSUE TITLE
Follow symbolic links when detecting browser apps installed in system.

### ISSUE THREAD

**Issue by vgorloff** [will-stone/browserosaurus#426]
I have a dedicated volume `/Volumes/Apps` which is shared between OSes in a multi-boot setup (Catalina, BigSur, etc.).

The browser apps, such as "Firefox.app", "Firefox Developer Edition.app", "Google Chrome.app", "Yandex.app", "Vivaldi.app", "Opera.app" reside inside a `/Volumes/Apps/Internet` folder. 

Even if I have a symbolic link from `/Volumes/Apps/Internet/Google Chrome.app` to `/Applications/Google Chrome.app` it is still not shown in a "Browserosaurus.app" after rescan.

**Comment by will-stone** [comment]
Browserosaurus uses the [app-exists](https://github.com/sindresorhus/app-exists) package to find out apps. Please open an issue on that repo. Thanks.
