### ISSUE TITLE
icon for settings is missing (macOS 11.5.2)

### ISSUE THREAD

**Issue by Chibiberu** [will-stone/browserosaurus#427]
Hi,
I just stared using browerosaurus and I noticed that the setting icon is missing. So, no way to access the app settings.
Is this bug already referenced?
Best regards,
Bertrand
<img width="611" alt="Screenshot 2021-08-17 at 10 22 43 405" src="https://user-images.githubusercontent.com/71894294/129649408-cca3f688-1c7f-4923-9e62-a6f006e644e4.png">

**Comment by will-stone** [comment]
Hi Bertrand,

Preferences has moved to the menu bar, and is now a separate window. 

Thanks,

Will.
