### ISSUE TITLE
Copy URL to clipboard

### ISSUE THREAD

**Issue by will-stone** [will-stone/browserosaurus#44]
Current thinking: another entry in the list (at bottom?) that can be clicked and has a keyboard shortcut to copy clicked URL to keyboard.

**Comment by long-lazuli** [comment]
for reference, I put that here : https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript

My idea was just to click on the url.

**Comment by will-stone** [comment]
Feature will be in v4
