### ISSUE TITLE
Safari links are not opening (MacOS 11.6 & Safari 15.0 & Browerosaurus v15.1.3)

### ISSUE THREAD

**Issue by igembitsky** [will-stone/browserosaurus#444]
When I click a link and select Safari as my browser, the browser opens, but there is no action. No tab opens, no address is navigated to. It just switches focus to my safari browser. It works as expected with all other browsers. This is something which started happening rather recently, but I can't pinpoint exactly when. Perhaps a few weeks?

**Comment by will-stone** [comment]
Hi. Please open a [bug report and follow the template](https://github.com/will-stone/browserosaurus/issues/new?assignees=&labels=bug&template=bug_report.md&title=). Thank you

**Comment by will-stone** [comment]
PS I've updated the template to make this easier 🙂 Thanks.
