### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by will-stone** [will-stone/browserosaurus#45]
Following on from #44, maybe there could be some sort of rudimentary plugin system. Thoughts:

- pipes the clicked URL to the plugin
- plugin can show entry/entries in the list.
- plugin can add click events to its entries.
- plugin can add default keyboard shortcut to its entries.

Other than for copy-to-clipboard, what else could be a plugin? Maybe each browser entry could be a plugin to start this off?

**Comment by long-lazuli** [comment]
- open the Url in Iphone Simulator (from xCode package).
- open with mpv / youtube-dl
- shift/alt would open the link in private window.

**Comment by will-stone** [comment]
Nice. If you can figure out the commands to do those things, I'll start looking into making the code a little more modular so we can easily add new items. Remember, I have a fulltime job, do not expect quick turn-arounds; I work in bursts on projects.

**Comment by long-lazuli** [comment]
Don't worry, I got a fulltime job too.
I write everything, and usually come back on a week-end, or some evening when my day-work goes well and I feel like coding.

**Comment by will-stone** [comment]
Awesome, thanks.

**Comment by will-stone** [comment]
Not quite a plugin system but it is now easier to add apps/browsers/activities (now to be known as activities). Activities are defined in `src/config/activities.js`. If an activity has an `appId` (I might rename this to something like `requiredAppName` or just `appName`) then it will only appear if the app is found on the user's system. `cmd` is the command run when clicked/hot-key is selected. Where `{URL}` is replaced with the clicked URL. Activity icon matches the name of the activity and is stored in `src/images/activity-icons`.

This will be in v4 release.
