### ISSUE TITLE
Newly found apps being set as favourite

### ISSUE THREAD

**Issue by anguka** [will-stone/browserosaurus#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behaviour

Browserosaurus introduced Zoom.us as a new tile, which frequently displaced the ones I set and shows on its own, preventing me selecting my favourite or any other.
I have managed to hide it as instructed and re-allocate the favourite star, but cannot remove it altogether from my list to clean it up and hopefully stop it doing this again.    Attached are
1.  my original setting
2. behaviour after the Zoom intrusion; often the zoom tile by itself is all that is offered in the selection window.
3. The new enlarged list.
5. addresses and files on an email (trusted regular source) in case they influence this being one which causes the problem as most others do not.

### Expected Behaviour

To keep working in same way each time and retaining my settings, and allowing me to cleat unwanted tiles from the settings altogether.

### Steps To Reproduce

1. Click on Browser link . . It happens.

### Browserosaurus version

15.2.1

### macOS version

15.2.1

### CPU Architecture

Intel

### Anything else?

![5  addresses](https://user-images.githubusercontent.com/44961616/137054229-e2f73dae-796b-4060-bec1-e7b89d3e36f5.jpg)
![2  self change](https://user-images.githubusercontent.com/44961616/137054238-e9f08303-e121-42fc-ab23-2b0a4ac59609.jpg)
![1  normal](https://user-images.githubusercontent.com/44961616/137054243-7c27d309-e7df-4dca-8580-4bc0e09afec0.jpg)
![3  Self entered list](https://user-images.githubusercontent.com/44961616/137054255-87f2a96c-0820-443b-8e5b-e1f9ef808942.jpg)

**Comment by will-stone** [comment]
I'll close this for now. Please reopen if you have more information. Thank you.
