### ISSUE TITLE
Restore recently closed URL (always present)

### ISSUE THREAD

**Issue by johnrm9** [will-stone/browserosaurus#454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behaviour

Restore recently close URL menu always appears and not the window to launch browsers

### Expected Behaviour

Window to launch browsers should appear instead of the Restore recently closed

### Steps To Reproduce

click on menu icon in menu bar

### Browserosaurus version

15.39

### macOS version

11.6

### CPU Architecture

Intel

### Anything else?

no

**Comment by will-stone** [comment]
Hi @johnrm9, did this answer your query?

**Comment by johnrm9** [comment]
Yes.
