### ISSUE TITLE
Mighty browser not getting scanned

### ISSUE THREAD

**Issue by dsteinbock** [will-stone/browserosaurus#457]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have checked the [FAQ](https://github.com/will-stone/browserosaurus/blob/master/docs/faq.md)

### Current Behaviour

When I re-scan apps, it doesn't identify Mighty as a compatible browser.

### Expected Behaviour

Mighty should appear as an identified browser.

### Steps To Reproduce

1. Install Mighty (https://mightyapp.com/)
2. General tab - re-scan
3. Mighty does not appear in Tiles.

### Browserosaurus version

15.1.3

### macOS version

10.14.6

### CPU Architecture

Intel

### Anything else?

FYI: Mighty runs Google Chrome on a virtual machine in the cloud. It can be set as MacOS default browser so I would guess it is compatible with Browserosaurus.

**Comment by will-stone** [comment]
Here’s the doc you need: https://github.com/will-stone/browserosaurus/blob/master/docs/supporting-a-browser-or-app.md

Apologies if that wasn’t more obvious from the FAQ, maybe you could send a PR to improve that too? Thanks.
