### ISSUE TITLE
UI broken in 16.0.6

### ISSUE THREAD

**Issue by i0ntempest** [will-stone/browserosaurus#460]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have checked the [FAQ](https://github.com/will-stone/browserosaurus/blob/master/docs/faq.md)
- [X] I understand this form is not for requesting support for new browsers or apps

### Current Behaviour

Browser names are shown outside of selection box and go over by picker window border with hotkeys assigned, and the window width is not adjustable. Also there's a white blank spot to the right of the horizontal scroll bar.
See the screenshot:
![Screen Shot 2021-11-28 at 17 38 18](https://user-images.githubusercontent.com/16017904/143763082-9e013050-f191-456e-9c7c-248a96a454b8.png)

### Expected Behaviour

The window should automatically adjust to a proper width, or at least allow manual adjustments.

### Steps To Reproduce

1. set hotkeys for browsers that are not marked as favorite
2. click a link to open the picker, observe the broken UI

### Browserosaurus version

16.0.6

### macOS version

12.0.1

### CPU Architecture

Intel

**Comment by will-stone** [comment]
Thanks @i0ntempest Looks like we just need to limit the width of the favourite app to make the long name wrap onto multiple lines. Should be a straightforward fix and I’ll put it in the next release.

**Comment by will-stone** [comment]
Released in 16.07. Thanks again @i0ntempest
