### ISSUE TITLE
Saved browsers and shortcut keys lost

### ISSUE THREAD

**Issue by mreid-tt** [will-stone/browserosaurus#462]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have checked the [FAQ](https://github.com/will-stone/browserosaurus/blob/master/docs/faq.md)
- [X] I understand this form is not for requesting support for new browsers or apps

### Current Behaviour

I have browserosaurus set to load on startup and every so often it would not detect all my browsers. I would usually just go into the preferences and click rescan when this happens. In the new version 16.0.7 however when this happens, my previously set favourite browser as well as the shortcut keys for detected browsers are lost and I have to set them again

### Expected Behaviour

It should not lose the previously configured settings as earlier versions did not do this. Ideally it should not miss out browser detection on launch but that is probably a different issue

### Steps To Reproduce

1. Restart mac
2. Click on link in Mail or Notes
3. Browser selection is different than previously configured

### Browserosaurus version

16.0.7

### macOS version

12.0.1

### CPU Architecture

ARM

**Comment by will-stone** [comment]
Hi @mreid-tt 
Unfortunately this is a side effect of the latest update: https://github.com/will-stone/browserosaurus/discussions/459#discussioncomment-1711368

**Comment by mreid-tt** [comment]
Umm, your comment suggests that this is as a result of a version change which implies only happening once. The problem is that every time a browser is not detected it looses its order and keyboard key as shown below:

<img width="369" alt="Screenshot 2021-12-06 at 9 04 50 PM" src="https://user-images.githubusercontent.com/943378/144947282-614ba1fa-8a82-43ba-8a6f-5229cdc41c8f.png">

This is very annoying. Can you clarify if this is what you meant?

**Comment by will-stone** [comment]
Hmmm, okay that does seem like a bug. Have you had a look at the code? Happy to review a PR if you have solved the issue.

**Comment by mreid-tt** [comment]
Hey, thanks for reopening this issue. I am really out of my depth in looking at the code but I came across this line: https://github.com/will-stone/browserosaurus/blob/958af27d26581bdde158737284a903f49b2ccedb/src/main/storage.ts#L44

This seems related to removing keys from the database. I wonder if this works by comparing browsers which are not currently detected. If so, perhaps a 'rescan' can be triggered after some start-up delay so that the list of browsers can be more accurately known?

**Comment by will-stone** [comment]
Thanks. That looks like a good place to start. I’ll look into it and get back to you 🙂

**Comment by will-stone** [comment]
Okay so I've tracked down the [line causing the problem](https://github.com/will-stone/browserosaurus/blob/master/src/shared/state/reducer.storage.ts#L46), however this logic is perfectly sensible (I think) if the returned installed apps were always correct. This is not something I think I can fix, as B relies on the `app-exists` package which as you can see by the [source code](https://github.com/sindresorhus/app-exists/blob/main/index.js) isn't really doing a lot. In other words it's an Apple bug, probably because the Spotlight index (which the package essentially inspects) is not ready in time.

For now, I suggest removing B from your login items, and just have it start when you first click a link, whilst I try to figure out a solution.

**Comment by mreid-tt** [comment]
Hmm, that's interesting and makes sense (though I can't make heads or tails of the code). If Spotlight is not ready with results while macOS is starting up then perhaps we can check on the state of Spotlight and wait until it is ready to prune the browser list. Dunno if this is possible but it's a thought or some other way of deferring taking pruning action until some sort of longer timeout for Spotlight to catch up.

I've removed Browserosaurus from the launch list as suggested and will check to see if this resolves the issue.

**Comment by will-stone** [comment]
> I've removed Browserosaurus from the launch list as suggested and will check to see if this resolves the issue.

Thanks, please let me know, this will be really useful information for debugging.

**Comment by will-stone** [comment]
This should be fixed in [16.1.0](https://github.com/will-stone/browserosaurus/releases/tag/v16.1.0)

**Comment by mreid-tt** [comment]
Great to hear! Just to let you know that in the week since I've removed Browserosaurus from the launch list, I have not come across any missing browsers or key shortcuts. Just takes a bit longer to launch

**Comment by will-stone** [comment]
Good to hear. You should now be able to add it back to login items.

The scan is now done when you open the picker or preferences window for the first time. In other words, you can have B loaded in the menubar, and then the scan is deferred; a spinner is shown whilst the scan for installed apps is taking place. This means that your computer has had plenty of time to load the Spotlight index.

I've also changed how installed apps are stored and so your hotkey configuration is now never deleted.

**Comment by mreid-tt** [comment]
Nice! So far so good after one reboot but will let you know after some more testing...

**Comment by mreid-tt** [comment]
Things so far have been working flawlessly with the delayed scan. No browsers or shortcuts have been lost to the mix so far. The one observation I have is that when it does load for the first time, the default action with the spacebar does not work. Minor issue and it does not reoccur for subsequent popups.

**Comment by will-stone** [comment]
> the default action with the spacebar does not work
Ah yes, this is because the spacebar and enter keys now activate the focused button (you can tab through the browsers now), and when the first scan is complete it doesn't focus on the first app. Let me see if I can fix that...

**Comment by will-stone** [comment]
Fixed in [this commit](https://github.com/will-stone/browserosaurus/commit/c33358d141adb564d427bcc2e26c36dfe6aaf496) 🙂 Will be in next release.

**Comment by mreid-tt** [comment]
yay! :-) looking forward to it... do have a restful weekend...

**Comment by mreid-tt** [comment]
hey @will-stone, this bug seems to have re-appeared in version 19. can you look into this again?

**Comment by will-stone** [comment]
Hi @mreid-tt there’s two bugs mentioned in this thread so please clarify. In fact, could you please fill out a new issue as so much has changed in B’s logic that it’s very likely not related to anything in this thread. Thanks 😊
