### ISSUE TITLE
Open Links in the Background

### ISSUE THREAD

**Issue by faxotherapy** [will-stone/browserosaurus#468]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have checked the [FAQ](https://github.com/will-stone/browserosaurus/blob/master/docs/faq.md)
- [X] I understand this form is not for requesting support for new browsers or apps

### Current Behaviour

Pressing the cmd or alt key does not tell the app to open the link in the background.

### Expected Behaviour

Pressing either key should allow the app to open any link in the background instead.

### Steps To Reproduce

In my case, e.g.:
1. I click a link in my RSS reader app.
2. I'm asked to select a browser. I choose Safari aka clicking while pressing alt or cmd key
3. Safari is brought foreground instead of remaining background.

### Browserosaurus version

16.0.7

### macOS version

10.14.6

### CPU Architecture

Intel

**Comment by will-stone** [comment]
Hi @faxotherapy Is Safari open when you try this? If not can you please test again with it already running. Thanks.

**Comment by faxotherapy** [comment]
Safari wa open, but the issue resulted from the fact that my Option key were not pressed enough on my aging laptop… Thanks for your prompt reply.
