### ISSUE TITLE
Beep on escape

### ISSUE THREAD

**Issue by will-stone** [will-stone/browserosaurus#47]
I thought I'd fixed this but obviously not. Last time I just put a setTimeout around this: https://github.com/will-stone/browserosaurus/blob/master/src/renderers/utils/UrlListener.js#L28. I'll try that again.

**Comment by long-lazuli** [comment]
I'm not sure your comment relates to "Beep on escape".
The centering works for me, on master.

Beep on escape could be a nice addition, but would certainly benefit from option to disable it.

**Comment by will-stone** [comment]
I use issues as my todo list. I know what the fix is.
