### ISSUE TITLE
Cannot identify the browsers that I installed after restoring from Time machine 

### ISSUE THREAD

**Issue by YohannTung** [will-stone/browserosaurus#490]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/docs/supporting-a-browser-or-app.md).

### Current Behaviour

1. Try to clean reinstall the browserosaurus, rescan browsers. Only show up the Safari. 
2. Try to factory reset the browserosaurus, rescan browsers. Only show up the Safari. 

### Expected Behaviour

Correctly listed all the browsers that I installed. 

### Steps To Reproduce

1. Backup up your Mac in time machine. 
2. Reinstall macOS and restore from time machine. 
3. Open the browserosaurus
4. Only showed the safari
5. Reinstall the browserosaurus, try rescan again. 
6. Factory reset the browserosaurus, try rescan again. 

### Browserosaurus version

17.0.0

### macOS version

12.1

### CPU Architecture

Intel

**Comment by will-stone** [comment]
Hi @YohannTung, can you please try rebuilding your Spotlight index for your Applications: https://support.apple.com/en-us/HT201716
