### ISSUE TITLE
Popup window no longer resizable in 17.2.0

### ISSUE THREAD

**Issue by i0ntempest** [will-stone/browserosaurus#496]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/docs/supporting-a-browser-or-app.md).

### Current Behaviour

Mostly caused by the change that fixed draggable icons, the popup picker window is no longer resizable and stuck at only showing 3 apps at the right.

### Expected Behaviour

Popup window should be resizable

### Steps To Reproduce

Launch B 17.2.0, open a link and try to resize the popup at the bottom or top edge

### Browserosaurus version

17.2.0

### macOS version

12.2

### CPU Architecture

Intel

**Comment by will-stone** [comment]
This is probably caused by the upgrade to Electron 17, I'll take a look.

**Comment by will-stone** [comment]
Hi @i0ntempest I have [logged a bug](https://github.com/electron/electron/issues/32995) with electron. Thanks for finding it! 🙂

**Comment by will-stone** [comment]
I've downgraded to Electron 16 in Browserosaurus v17.3.0, which solves the issue for now. I'll keep this open to track the Electron bug.

**Comment by will-stone** [comment]
Latest Electron fixed this issue: https://github.com/electron/electron/releases/tag/v17.1.2
