### ISSUE TITLE
Other ways to find apps which can open URLs

### ISSUE THREAD

**Issue by long-lazuli** [will-stone/browserosaurus#51]
Hello,
I'm thinking an other way to find browsers on the machine...

Checking apps which are registered to handle protocols (http/https/sockets), we should find the same apps as this :
<img width="399" alt="image" src="https://user-images.githubusercontent.com/1178625/37557959-af459136-2a0c-11e8-9086-4b3a1f71a27c.png">

I'm thinking about doing an external repo.
As browserosaurus use `opn` for opening, it could use an external lib to find appsByProtocols.
For the moment, I don't really now how to do it on osx, but I know it is possible, as other software did the same : http://www.rubicode.com/Software/RCDefaultApp/

Bonus is that it could extend browserosaurus compatibility to windows & linux.

Tell me your thoughts, I'll probably investigate more next week for the OSX part.

**Comment by will-stone** [comment]
If you can find an OS-agnostic way of finding installed browsers, that'd be great. However I do not own a Windows machine and so will not be able to test on it. I do not particularly want to say that an app supports an OS if I can't personally test it.

Remember, if you'd like to continue investigating how to dynamically grab URL handlers from the system, you'll also need to investigate how to get the logos/icons too.

I'm currently happy with the white-list system, as it forces me to explicitly test each addition, but I'm happy to hear about alternative methods.

**Comment by tborychowski** [comment]
The easiest way would be to allow users to browse for an app that can handle links (like Choosy does).
(yes, I'm looking for alternatives, as choosy stopped working in mojave beta).

**Comment by tborychowski** [comment]
sorry bad wording 😀
I meant most flexible/functional, as this would allow to use any app they wish (without white/black listing or scanning or updating when an OS changes it's categorisation methods).

As for the PR - unfortunately I don't have time recently to do any development.
And, if you're switching to TS, I'd stay away 😀

**Comment by will-stone** [comment]
We use TS at work and I use my personal projects to practice what I need to know in my job (hence why I love a refactor).

I don't think this will be a particularly easy thing to code and I can imagine will be fraught with _what if the user does this_ type user journeys. I quite like the current simplicity of the app, and whitelisting helps us test integrations one at a time.

**Comment by will-stone** [comment]
Let's close this out and say that the white-list method works for us. Please reopen if you hear of any Electron/MacOS API that allows B to know of URL-openers.
