### ISSUE TITLE
Add options for monochrome and white icon in menu bar

### ISSUE THREAD

**Issue by ph00lt0** [will-stone/browserosaurus#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/docs/supporting-a-browser-or-app.md).

### Current Behaviour

Currently only a blue icon is visible in the menu bar. This clashes with my blue background and generally doesn't look good as only colored icon.

### Expected Behaviour

Add a monochrome and white icon as option for icons in the menu bar. 

### Browserosaurus version

17.2.0

### macOS version

12.2

### CPU Architecture

Intel

**Comment by will-stone** [comment]
Hi @ph00lt0 

Th blue icon indicates there's an update available. Go to Preferences and select Download Update.

**Comment by ph00lt0** [comment]
@will-stone ah who would have thought. I really missed that haha. cheers.

**Comment by will-stone** [comment]
Yeah it's not the most obvious solution, but one I thought best whilst I was refactoring the Picker window. I may explore alternatives in the future.
