### ISSUE TITLE
B. doesn't find all installed browsers

### ISSUE THREAD

**Issue by alexaulbach** [will-stone/browserosaurus#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/docs/supporting-a-browser-or-app.md).

### Current Behaviour

Finds firefox, safari, zoom, miro - which is nice - but not google-chrome.

### Expected Behaviour

Finds also google-chrome. :) 

### Steps To Reproduce

Of course I tried to rescan. I played also around with making google-chrome the default browser.
I installed everything (but safari of course) via homebrew. Have no idea how to reproduce it. 

### Browserosaurus version

17.4.0

### macOS version

12.3

### CPU Architecture

ARM

### Anything else?

Is there a limit of browsers that can be found? I have no idea what's going wrong. The machine is a completely new installation.

**Comment by will-stone** [comment]
Hi. Have you tried reindexing your Spotlight? On my mobile at the moment so can’t easily look around but you’ll find it mentioned in previous issues.

**Comment by alexaulbach** [comment]
I tried and Chrome is still not found, even if the spotlight immediatelly find chrome. On my old mac everything worked perfectly. Perhaps something went wrong with the installation. So currently I think it has nothing to do with Browserosaurus, but if you have an idea how to look what's wrong with my installation I would be thankful.

**Comment by will-stone** [comment]
I’m sorry I don’t know. Maybe try installing Chrome from Google’s website?

**Comment by alexaulbach** [comment]
Just want to say the solution was too simple: I just rebooted the system and with the next rescan Browserosaurus found it.
Maybe helpful for others?!
