### ISSUE TITLE
checkbox in settings to remove icon from menu bar

### ISSUE THREAD

**Issue by sonalder-darlene** [will-stone/browserosaurus#515]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/docs/supporting-a-browser-or-app.md).

### Current Behaviour

There is no way to disable the icon in the menu bar. I know Browserausaurus is my default browser and don't want another icon in my menu bar.

### Expected Behaviour

In Preferences... > General I want to found a checkbox to enable/disable the icon in menu bar !

### Steps To Reproduce

You know

### Browserosaurus version

17.4.0

### macOS version

12.0.1

### CPU Architecture

ARM

**Comment by will-stone** [comment]
Thanks but not a bug. Please use discussions for feature requests. Here's one someone posted earlier: https://github.com/will-stone/browserosaurus/discussions/463
