### ISSUE TITLE
App is frozen

### ISSUE THREAD

**Issue by pizzaeater** [will-stone/browserosaurus#516]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/docs/supporting-a-browser-or-app.md).

### Current Behaviour

After macOS update to 12.3 (or just restart a computer?), the app is frozen and cannot find any browsers.

It eats full CPU:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/2511553/160325874-ac255895-aeae-4bdd-9f77-2a1196839f05.png">

There are no browsers found:
<img width="712" alt="image" src="https://user-images.githubusercontent.com/2511553/160326156-79b60297-9d1e-47d3-950c-c7a8ce8d6921.png">
<img width="712" alt="image" src="https://user-images.githubusercontent.com/2511553/160327052-6498f867-c0cd-49dc-b236-af52f3c1036f.png">

### Expected Behaviour

The app doesn't load the CPU and found all browsers.

### Steps To Reproduce

1. Update to macOS 12.3
2. Check the app

### Browserosaurus version

17.4.0

### macOS version

12.3

### CPU Architecture

Intel

**Comment by will-stone** [comment]
Hi, after searching the issues, can you please tell which solutions you've tried? e.g. restarting Spotlight index?

**Comment by pizzaeater** [comment]
> Hi, after searching the issues, can you please tell which solutions you've tried? e.g. restarting Spotlight index?

I haven't tried any solutions, just restarting the app. Where can I see possible solutions?

**Comment by will-stone** [comment]
Ah, see you ticked the box to say that you'd searched previous issues and the discussions forum, so I was wondering what you'd tried. It greatly helps when you do this as it means new bugs need less triage.

Try [this one](https://github.com/will-stone/browserosaurus/issues/402#issuecomment-852820131).

**Comment by pizzaeater** [comment]
> Ah, see you ticked the box to say that you'd searched previous issues and the discussions forum

Sorry, I ticket it because it was just one another opened bug. I will try it later and post it here.

**Comment by pizzaeater** [comment]
> Try [this one](https://github.com/will-stone/browserosaurus/issues/402#issuecomment-852820131).

It doesn't help. The app is frozen completely — I cannot click on any buttons, I can just kill it from the Activity Monitor, it's not about 0 browsers, it's more about 100% CPU.

Maybe I could check error logs somewhere?

**Comment by will-stone** [comment]
It needs to scan for available browsers which can take some time on Intel machines. Have you tried waiting for a little while? What computer are you using? Which version of macOS?

**Comment by pizzaeater** [comment]
The version of macOS is mentioned 3 times in the original message: 12.3
I have i7 Intel processor.
It takes forever, the app hangs.

**Comment by will-stone** [comment]
Ah yes, it's mentioned 3 times: a little rude so support stops now. Sorry it doesn't work for you: the perils of free and open source software. Feel free to post if you find the error.

**Comment by pizzaeater** [comment]
> Ah yes, it's mentioned 3 times: a little rude so support stops now. Sorry it doesn't work for you: the perils of free and open source software. Feel free to post if you find the error.

Sorry for being rude, Will. I really didn't mean it :(
