### ISSUE TITLE
Browserosaurus opens two windows of Firefox when we open any link for the first time 

### ISSUE THREAD

**Issue by debjitpal5040** [will-stone/browserosaurus#520]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

Suppose firefox is not runnning (No little dot below it's icon in dock), in that case whenever I am clicking a link and choosing firefox to open that via Browserosaurus, it actually opening two separate windows in Firefox. One window opens the link but the another one just the homepage of Firefox. 
But if suppose firefox is running and then i do the same; in that case the problem doesn't occur. I tried this with other browsers like chrome, edge, safari too but they don't seem to have this issue.

### Expected Behaviour

It should just open only one window containing the link I have clicked.

### Steps To Reproduce

1. Make sure that firefox is not running. ( Quit firefox )
2. Click on any link and choose firefox from browserosaurus popup.
3. Swipe up using four fingers on trackpad or just close the window containingthat link you have clicked.
4. You can see an extra window (Firefox Homepage) also opened.

### Browserosaurus version

17.4.0

### macOS version

12.3.1

### CPU Architecture

ARM

### Anything else?

https://user-images.githubusercontent.com/76846542/162409302-fe641c73-c0e2-45b4-9c73-d4c147f22b8e.mp4

**Comment by will-stone** [comment]
Hi @debjitpal5040 Could you please do the same test but set Firefox as your default browser in the System Preferences, and see if two Firefox windows open? I've just done it and found that it does. Therefore this is a bug with Firefox and not an issue isolated to Browserosaurus. What's happening is Firefox opens your default window, be that last opened tabs or a new tab, whatever you have it set to, and then the link is being opened in a new window.

**Comment by debjitpal5040** [comment]
> Hi @debjitpal5040 Could you please do the same test but set Firefox as your default browser in the System Preferences, and see if two Firefox windows open? I've just done it and found that it does. Therefore this is a bug with Firefox and not an issue isolated to Browserosaurus. What's happening is Firefox opens your default window, be that last opened tabs or a new tab, whatever you have it set to, and then the link is being opened in a new window.

So what should I do now to prevent firefox opening two windows ? Any suggestions?

**Comment by will-stone** [comment]
I found [this](https://support.mozilla.org/en-US/questions/1322619); searched "firefox new window on link". Hope this helps.
