### ISSUE TITLE
Selected browser fill does not respect scrollbar toggle.

### ISSUE THREAD

**Issue by WorkInProgress-Development** [will-stone/browserosaurus#526]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

<img width="362" alt="Screenshot" src="https://user-images.githubusercontent.com/38821590/165000727-97206d9e-c794-4e6e-9aad-76463edf8846.png">
The fill for the selected browser does not fill all the way until the right. This appears to be a result of a design made for either scrollbars always on; or with more browsers than will fit.

### Expected Behaviour

Fill would fill completely when scrollbars are hidden.

### Steps To Reproduce

1) Disabled enough browsers (if necessary) so that the scrollbar won't appear.
1) Open any URL

### Browserosaurus version

18.0.0

### macOS version

12.3.1

### CPU Architecture

ARM

**Comment by will-stone** [comment]
Thanks, yeah there's some padding in there for the scrollbar, I'll look into it 🙂 Or I'm happy to accept a PR if you'd like?

**Comment by WorkInProgress-Development** [comment]
I'm not able to do any UI work at the moment, so I won't be sending a PR for the moment.
When you've got time, look into it.

Thank you for a great tool and easy response.

**Comment by will-stone** [comment]
No worries. I've realised that the solution is a little more involved than just removing the padding, anyway, but I'll hopefully have this fixed in next release.
