### ISSUE TITLE
Long URLs are truncated

### ISSUE THREAD

**Issue by WorkInProgress-Development** [will-stone/browserosaurus#528]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

Long URLs are truncated, and thus need to be copied elsewhere to be previewed completely. 
<img width="319" src="https://user-images.githubusercontent.com/38821590/165001518-3ef74093-298c-4b1d-86de-2d5179dec0ec.png">

Whilst this did happen previously, the new UI introduced in 18.0.0 has significantly less space for the url, and I am hitting the truncation length frequently, whereas I rarely had to deal with it in earlier versions - which had 2 lines and much more horizontal space.

### Expected Behaviour

More of the URL is visible, as in previous versions.

Alternatively, but not ideally, the hover tooltip on the url could change to being the full URL, rather than "Click to copy"

### Steps To Reproduce

1. Open a longer URL in Browserosaurus (e.g.  https://www.verylongurlimadeup.com/thisisnotareallink/ihope/thisisjustanexample/thiscanbereallylongetcetc)
1. Verify that the link is truncated.

### Browserosaurus version

18.0.0

### macOS version

12.3.1

### CPU Architecture

ARM

### Anything else?

Previous version below:

<img width="487" src="https://user-images.githubusercontent.com/38821590/165001670-28e39231-1d37-4588-ba2e-e35c2f955f82.png">
<img width="487"  src="https://user-images.githubusercontent.com/38821590/165001673-fe8da8ee-40e4-4269-a3b8-60f1163bd889.png">

**Comment by will-stone** [comment]
Thanks for reporting. I found that I just don't really look at the URL because I've usually already figured out the URL before I click it, by hovering over the link in whichever app I'm currently using. I agree that a hover tooltip could be useful though, I'll look into it 😊

**Comment by will-stone** [comment]
Also looks like the minimum height could be reduced now, as you don't have many browsers. If you log a bug or PR for this, then I'll get to it when I can. Thanks.

**Comment by WorkInProgress-Development** [comment]
> I found that I just don't really look at the URL because I've usually already figured out the URL before I click it, by hovering over the link in whichever app I'm currently using.

For my use case I relatively often have apps which open URLs without previewing - to use an Apple example, Keynote's help menu has a Service and Support option which opens the URL in the browser - and I would normally rely on B to choose which browser.

**Comment by will-stone** [comment]
Sure. Horses for courses; we just use B in different ways.
