### ISSUE TITLE
Minimum height is too large for 4 browsers or less.

### ISSUE THREAD

**Issue by WorkInProgress-Development** [will-stone/browserosaurus#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

As discussed in https://github.com/will-stone/browserosaurus/issues/528#issuecomment-1108120927

The browser selection window can only be adjusted until a certain amount (200 pixels minus the url bar - [src/main/windows.ts](https://github.com/will-stone/browserosaurus/blob/main/src/main/windows.ts)) 

### Expected Behaviour

The window can be adjusted to the size of the amount of browsers installed.

### Steps To Reproduce

1) Installed up to 4 browsers.

### Browserosaurus version

18.0.0

### macOS version

12.3.1

### CPU Architecture

ARM

**Comment by will-stone** [comment]
Brilliant, thanks 😄 Hopefully, this will be fixed in next release. I'll set the minimum height to two browsers, as any less than that and B is pretty much useless 😆
