### ISSUE TITLE
Firefox nightly not detected

### ISSUE THREAD

**Issue by bendem** [will-stone/browserosaurus#55]
Thanks for this project, it's an awesome idea.

I'm not quite sure what the process is to detect browsers, but Firefox nightly is not detected by Browserosaurus, even though it's detected by macos.

![screen shot 2018-05-03 at 09 12 10](https://user-images.githubusercontent.com/2681677/39563905-4af1ee76-4eb2-11e8-8465-1e8db31f972c.png)
![screen shot 2018-05-03 at 09 13 08](https://user-images.githubusercontent.com/2681677/39563916-4c09b654-4eb2-11e8-8a62-02c1d2c0c873.png)

**Comment by sgdesmet** [comment]
I have the same issue with Firefix Beta, version 60.0

**Comment by will-stone** [comment]
Thanks for reporting. This is because Firefox changed the name of the app to now include a space. This will be fixed in the upcoming v4 version. I'll release a beta soon for you to test.
