### ISSUE TITLE
Links that point to local resources are invalid when opening with browserosaurus

### ISSUE THREAD

**Issue by justin-guan** [will-stone/browserosaurus#552]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

When opening a link that points to a local HTML file, browserosaurus will open the browser selector, but upon selecting any option, no browser will be launched, and no navigation to the link will occur. This seems to be because the link that is parsed by browserosaurus is incorrect for local files. If you hover over any browser in the browser selector, you can see that the link always begins with "null". 
![Screen Shot 2022-07-12 at 11 40 46 AM](https://user-images.githubusercontent.com/6827708/178532966-784f6a27-c9c2-4774-828c-b92ba345c2ac.png)
This seems to be because [browserosaurus is using TidyURL to clean links](https://github.com/will-stone/browserosaurus/blob/c0f5f9d0aa61fbc612c643c7d2adfc14b29b9026/src/main/main.ts#L21) before opening them. When `TidyURL.clean` is called, a new link is returned, but [it seems to be incorrectly building links that point to local resources](https://github.com/DrKain/tidy-url/pull/19). 

### Expected Behaviour

The expectation is that when clicking on a link that points to a local HTML file, browserosaurus will open the browser selector with the correct link, and then be able to open the HTML file with the browser that is selected.

This was actually the behavior in a previous version of browserosaurus up until fairly recently. I don't know exactly which version, as I updated my browserosaurus version, and never checked what version I was on previously. But, I suspect it was the introduction of TidyURL that caused this issue.

### Steps To Reproduce

1. Set browserosaurus as the default browser
2. Open terminal
3. Run `touch test.html` (if a local HTML file already exists, then you can skip this)
4. Run `open test.html`
5. Observe that the browserosaurus browser selector will show up, but the link it is trying to navigate to is incorrect, and selecting any browser will fail to open the link.

### Browserosaurus version

18.4.2

### macOS version

12.4

### CPU Architecture

ARM

### Anything else?

A fix for TidyURL incorrectly building the URLs when cleaning was merged in this [PR](https://github.com/DrKain/tidy-url/pull/19). It should be available in version 1.5.0 and onwards, so bumping this dependency should fix the issue.

I had some trouble testing a fix for this locally. For whatever reason, my local build of browserosaurus would not show the browser picker even on a clean build of `main`, so I wasn't able to verify what the behavior would be like after a version bump, but I'm fairly confident that this would fix the issue.

**Comment by will-stone** [comment]
Thanks @justin-guan 🙂 I’m not currently with my computer (I’m on honeymoon 🥳) but it certainly sounds like upgrading the package would help, and I’ll do that when I get back.

Interesting that you couldn’t get `main` up and running. Which version of node are you using? Browserosaurus currently needs v16 (I don’t think v18 works).

**Comment by justin-guan** [comment]
Congrats! 🎉  Definitely not a super urgent issue.

It's not that I couldn't get `main` up and running, but rather the browser picker doesn't seem to show up for me when opening links that point to local resources with a local build. Running `main`, everything seems to work as expected when I click a link that points to a web resource (ie. https://example.com), but if I repeat the repro steps from above using the local build as the default browser, the browser picker just doesn't show up at all (but the browser picker does show up on production/release builds). I've tried on both node 16.16.0 and 18.5.0.

I'd be happy to create a PR bumping tidy-url if you'd like, but I just wasn't able to verify whether or not it actually fixed the issue when using a local build. Seemingly, this feature of opening local HTML files seems to only work on production/release builds for me.

**Comment by will-stone** [comment]
Are you setting Electron as your default browser? In the preferences click Make Default in the General pane.

**Comment by will-stone** [comment]
The next release will use the latest tidy-url version. Thank you for submitting the patch to their project.
