### ISSUE TITLE
"missing h/t and H/T" displays in browser

### ISSUE THREAD

**Issue by paulhetzel** [will-stone/browserosaurus#555]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

Daily, I receive an email from CNN. Whenever I click on a link, choose a browser via Browsersaurus, I get the following message in the browser: "missing h/t and H/T". This issue occurs with all browsers chosen in Browsersaurus (Chome, Firefox, Safari, etc.) - both in non-incognito and in incognito. When I copy & paste the link into a browser, it works fine. When I make any browser the default (rather than Browsersaurus), it works fine.

Here's an example link from the https://e.newsletters.cnn.com/click?EcGF1bC5oZXR6ZWxAZ21haWwuY29t/CeyJtaWQiOiIxNjU3NzA5MDUzOTU5ODMzOGNiOGU0Y2E2IiwiY3QiOiJjbm4tYWExNmNkODJiMWViOTY3M2M2ZTYwOTNkZTYyOGE0MGEtMSIsInJkIjoiZ21haWwuY29tIn0/HWkhfQ05OX2lfTmV3c19OREJBTjA3MTMyMDIyNjQ4NTExMSxjbjEsaHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/qP3Y9YlRJY1FNd1lDMW8/stfbfa11358

### Expected Behaviour

Should be able to open the actual link

### Steps To Reproduce

Open the following link in Browsersaurus: https://e.newsletters.cnn.com/click?EcGF1bC5oZXR6ZWxAZ21haWwuY29t/CeyJtaWQiOiIxNjU3NzA5MDUzOTU5ODMzOGNiOGU0Y2E2IiwiY3QiOiJjbm4tYWExNmNkODJiMWViOTY3M2M2ZTYwOTNkZTYyOGE0MGEtMSIsInJkIjoiZ21haWwuY29tIn0/HWkhfQ05OX2lfTmV3c19OREJBTjA3MTMyMDIyNjQ4NTExMSxjbjEsaHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/qP3Y9YlRJY1FNd1lDMW8/stfbfa11358

### Browserosaurus version

18.4.2

### macOS version

12.4

### CPU Architecture

ARM

### Anything else?

It APPEARS that some of the forward slashes (/) from the URL are being replaced by Browsersaurus as %2F

**Comment by will-stone** [comment]
Thanks @paulhetzel, this has now been logged with the package that cleans the URLs of trackers.

**Comment by will-stone** [comment]
Will be fixed in next release 👍 Thanks to @DrKain for updating their tidy-url package.

**Comment by paulhetzel** [comment]
Very much appreciated!
