### ISSUE TITLE
Scroll position is not reset

### ISSUE THREAD

**Issue by rohit-gohri** [will-stone/browserosaurus#561]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

The scroll position is not reset to the top always and so my most frequent browser is not shown where I expect it to be.

### Expected Behaviour

Everytime Browserosaurus opens, the list of browsers should be in a predictable position to quickly open links. 

### Steps To Reproduce

1. Click on a link
2. Scroll down the list of apps
3. Click outside Browserosaurus
4. Click on a link again, scroll position is remembered

### Browserosaurus version

18.5.0

### macOS version

12

### CPU Architecture

ARM

**Comment by will-stone** [comment]
Thanks @rohit-gohri. This will be fixed in the next release 👍
