### ISSUE TITLE
Chrome & Brave stopped being detected in v 19.0.0

### ISSUE THREAD

**Issue by janwiktor** [will-stone/browserosaurus#563]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

Browserosaurus stopped detecting Chrome, Brave & Spotify app after upgrading recently, out of 5 apps detected previously (Safari and Zoom). Initially, it stopped displaying them as options but the key shortcuts still worked (that is: when the browserosaurus popup showed, and I hit the key `1` which corresponded to Brave in my setup, it still opened the brave browser). After reinstalling and rerunning the scan, it stopped detecting anything aside from Safari and Zoom altogether. They are not showing in the popup, and in the `Apps` tab in the preferences.

### Expected Behaviour

See all browsers as available options.
The `rescan` button doesn't show any progress as well – not sure what should be the expected behavior here.

### Steps To Reproduce

No specific reproduction steps as it doesn't show error codes or any other abnormal behavior. Rescan, Reset, Reinstall via app package give the same result.

### Browserosaurus version

19.0.0

### macOS version

12.5

### CPU Architecture

Intel

**Comment by will-stone** [comment]
Hi @janwiktor Can you please try unticking Applications in Spotlight settings and then ticking it again? Once it's on, you may need to reboot.

<img width="667" alt="image" src="https://user-images.githubusercontent.com/654103/182639176-ac1bf203-cc96-48dc-88ff-ab41b07ab07f.png">

**Comment by janwiktor** [comment]
Hi again! Thanks for responding – so it did help partially. Brave appeared back after reindexing in Spotlight, Chrome however still remains undetected (it does show in Spotlight suggestions though) 😲 I rerun the indexing and factory reset Browserosaurus to double-check, but it's still not showing. Anything else I could inspect or try?

**Comment by will-stone** [comment]
Hmmm, not sure. Where’s Chrome installed? Then run: `mdls -name kMDItemCFBundleIdentifier -r /PATH/TO/APP.app` This is all B does, it should come back with: `com.google.Chrome`

**Comment by janwiktor** [comment]
`/Applications/` Ran the command, it returned `com.google.Chrome` as expected, and also Chrome appeared back in B's preferences when I checked recently. Maybe the identifiers took longer to index? Weird, but solved. Thanks!

**Comment by will-stone** [comment]
It can run a little slow on intel machines. I need to figure out some nice UX to show that it’s still scanning 🤔

**Comment by frankvx97** [comment]
@janwiktor @will-stone can you explain how to "run" the `mdls -name kMDItemCFBundleIdentifier -r /PATH/TO/APP.app` command? I open the terminal and replace "/PATH/TO/APP.app" with the path to my browser (In this case Chrome and Braver are not showing), but I get an error saying that it couldn't find it.

**Comment by frankvx97** [comment]
Update... It seems like Brave and Chrome were installed in a different folder within my Hard Drive structure `/Volumes/Macintosh HD - Data - Datos/Applications/Brave Browser.app` so I drag and drop it the Applications folder (right click on the Finder sidebar shortcut "Show in container folder" and it seems it created a copy. 

When clicked on "rescan" on Browserosaurus it detected Chrome and Brave 🙏
