### ISSUE TITLE
Duckduck browser not detected

### ISSUE THREAD

**Issue by Drallas** [will-stone/browserosaurus#577]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

Browserosaurus is not detecting the [Duckduckgo browser](https://duckduckgo.com/mac) also not when i do a rescan. I guess it might be because it's using safari / webkit for rendering?

### Expected Behaviour

detecting the Duckduckgo browser

### Steps To Reproduce

rescan

### Browserosaurus version

15.1.3

### macOS version

12.6

### CPU Architecture

ARM

**Comment by will-stone** [comment]
Hi @Drallas could you please [follow the instructions for finding the bundle identifier](https://github.com/will-stone/browserosaurus/blob/main/guide/supporting-a-browser-or-app.md#finding-bundle-identifier-for-an-app)? DDG recently released a new major version of their browser and they may have changed the identifier. Thanks 🙂

**Comment by Drallas** [comment]
> Hi @Drallas could you please [follow the instructions for finding the bundle identifier](https://github.com/will-stone/browserosaurus/blob/main/guide/supporting-a-browser-or-app.md#finding-bundle-identifier-for-an-app)? DDG recently released a new major version of their browser and they may have changed the identifier. Thanks 🙂

Sure it's com.duckduckgo.macos.browser

**Comment by will-stone** [comment]
Oh! You're on a very old version of Browserosaurus 😱 Latest version can be found here: https://github.com/will-stone/browserosaurus/releases

**Comment by Drallas** [comment]
> Oh! You're on a very old version of Browserosaurus 😱 Latest version can be found here: https://github.com/will-stone/browserosaurus/releases

Seems brew upgrade missed browserosaurus, fixed now!
