### ISSUE TITLE
open error

### ISSUE THREAD

**Issue by cddehsy** [will-stone/browserosaurus#578]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

An error is reported when opening the software, and it cannot be opened
![Uploading iShot_2022-10-22_15.53.48.png…]()

### Expected Behaviour

An error is reported when opening the software, and it cannot be opened
![Uploading iShot_2022-10-22_15.53.48.png…]()

### Steps To Reproduce

An error is reported when opening the software, and it cannot be opened
![Uploading iShot_2022-10-22_15.53.48.png…]()

### Browserosaurus version

19.1.0

### macOS version

12.6

### CPU Architecture

Intel

**Comment by will-stone** [comment]
Hi @cddehsy Those images didn't upload correctly, please can reupload the screenshot? Thanks.

**Comment by will-stone** [comment]
Closing for now. Please reopen if you are able to provide the screenshot. Thanks 😊
