### ISSUE TITLE
Chrome opening in most recently used window (incognito or "regular") 

### ISSUE THREAD

**Issue by paulhetzel** [will-stone/browserosaurus#579]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

Since 19.1, while opening a link within Chrome, the link will open in either incognito mode or in "regular" mode - whichever has been used last.

For example, if I have just used Chrome in Incognito mode and I open a link via Browsersaurus, the window will open up in the Incognito window. On the other hand, if I have just used Chrome in "regular" / non-Incognito mode and I open a link via Browsersaurus, the window will open up in the "regular" / non-Incognito window

This is unique to Chrome and doesn't happen in other tested browsers (mostly Firefox)

### Expected Behaviour

In the past, whenever I opened a link and requested the Chrome browser, it would open in the "regular" / non-incognito window

### Steps To Reproduce

1. Open Chrome and then create an incognito window
2. Open a link utilizing Browsersaurus
3. Browsersaurus SHOULD open a "regular" / non-incognito window

### Browserosaurus version

19.1.0

### macOS version

12.x and 13.0

### CPU Architecture

ARM

**Comment by will-stone** [comment]
Hi, does this happen when you set Chrome as your default browser? Or just when using Browserosaurus to select Chrome?

**Comment by will-stone** [comment]
I've just checked and this is standard Chrome behaviour.
