### ISSUE TITLE
Missing browsers and app since upgrade to MacOS Ventura

### ISSUE THREAD

**Issue by Fouedsassi** [will-stone/browserosaurus#580]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

Since I upgraded to MacOs Ventura, some apps disappeared, mainly Safari and Firefox. Tried resetting the app and rescanning it, but not luck. 

### Expected Behaviour

I should continue seeing Safari and other installed apps. 

### Steps To Reproduce

1. Upgrade to MacOS Ventura
2. Launch the app
3. Click a link and see Safari and Firefox are missing
4. Go to the app settings and rescan apps. 
5. Reset the app and try again. 

### Browserosaurus version

19.1.0

### macOS version

13.0 

### CPU Architecture

Intel

**Comment by will-stone** [comment]
Hi 👋 I can see all my browsers after upgrading. You may need to reindex Spotlight. This can be done by unchecking Apps and rechecking it again in Spotlight preferences.

**Comment by Fouedsassi** [comment]
Hi!! That did it thank you!! Didn’t work at first after indexing but
restarting the Mac solved it.

Cheers

**Comment by will-stone** [comment]
Awesome. Glad to hear it 🙂

**Comment by Fouedsassi** [comment]
Hello Will,

I hope all is well. Looks like something happened with the latest release.
I'm unable to use the app entirely. I updated the spotlight index,
restarted my computer, deleted and installed the app but no luck. I just
see a spinning gif but not apps are displayed. Please see screenshots
below. Any thoughts?

**Comment by will-stone** [comment]
@Fouedsassi Spotlight index is no longer used. Please read the release notes for v20: https://github.com/will-stone/browserosaurus/releases Are your apps stored in `/Applications` and you haven't renamed them?

**Comment by Fouedsassi** [comment]
Hey Will,

Yes, I read the release note before updating. That's correct, all my apps
are in the Application folder and I haven't renamed them since.

Thanks for your help.

**Comment by dpangier** [comment]
Installed for the first time yesterday. Ventura 13.1 and BrowserSaurus 20.0.1 installed using the Brew method.

"0 compatible apps found". 

Digging and have tested using:

 ```❯ find /Applications -iname "*.app" -prune -not -path "*/.*" | while read -d $'\n' file; do printf "%s\n" $(mdls -name kMDItemCFBundleIdentifier -raw "$file"); done | grep Safari
find: /Applications/ARM/.fseventsd: Permission denied
com.apple.Safari```

Wondering if the error on one of lines of `find` output is breaking the scan.

**Comment by will-stone** [comment]
Thanks @dpangier 
That’s some great debugging work ☺️ I’ll reopen this; we need a way to deal with the permission error, or only scan as deep as so not to trigger it 🤷‍♂️

**Comment by hybras** [comment]
I believe this can be achieved with find's depth/maxdepth flags. Note that there seems to be a `/Applications/Utilities` folder, so scanning should be one/two levels deep based on whether we want to include the utils folder.

**Comment by mreid-tt** [comment]
> Thanks @dpangier That’s some great debugging work ☺️ I’ll reopen this; we need a way to deal with the permission error, or only scan as deep so as not to trigger it 🤷‍♂️

You can add `-print 2>/dev/null` to the end of the command to strip out the error messages so you don't get them in the output. So the full command looks like this:

```
find /Applications -iname "*.app" -prune -not -path "*/.*" -print 2>/dev/null
```

**Comment by will-stone** [comment]
Should be fixed in latest release, thanks @mreid-tt 😄
