### ISSUE TITLE
MacOS ventura upgrade Browsersaurus not finding Safari any longer on startup/reboot

### ISSUE THREAD

**Issue by W608** [will-stone/browserosaurus#581]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

When starting mac or reboot, have to always rescan to find safari again to open links.

### Expected Behaviour

After rescanning once following MacOS ventura upgrade not requiring rescan and now rescan after every startup.

### Steps To Reproduce

1. Start Mac
2. Try clicking a link, no safari recognized
3. Open Browsersaurus 
4. Rescan
5. Now Safari found once again

### Browserosaurus version

15.1.3

### macOS version

13.0

### CPU Architecture

Intel

### Anything else?

Issue after every reboot or shut down and startup.

**Comment by will-stone** [comment]
Hey 👋 You are on a very old version of Browserosaurus, please retry with latest version which, at time of writing is 19.1.0. Thank you 🙂
