### ISSUE TITLE
Assign on all Desktops possible?

### ISSUE THREAD

**Issue by christoph-werker** [will-stone/browserosaurus#585]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

When i click a Link in a app that is not in first Workspace/Desktop, the windows switches to the first desktop and not showing the icon. 

https://user-images.githubusercontent.com/9929788/202910213-a8f598f2-d0ae-4cd0-be8a-bd7438a74a3c.mov

I think i would be a possible fix when the apps assigns to all desktops. But i cannot set it manually cuz there is no docs icon.
![image](https://user-images.githubusercontent.com/9929788/202909718-e810706b-759c-4b19-b706-de001f64ebfd.png)

### Expected Behaviour

the window near to the link should show up and now desktop switch.

### Steps To Reproduce

1. Create new Workspace fn + F3
2. Switch to the new desktop
3. Click a link in that desktop

### Browserosaurus version

19.2.0

### macOS version

13.0.1 

### CPU Architecture

ARM

### Anything else?

![image](https://user-images.githubusercontent.com/9929788/202909718-e810706b-759c-4b19-b706-de001f64ebfd.png)

**Comment by will-stone** [comment]
Duplicate #582
