### ISSUE TITLE
v 19.3.2 missing safari and brave from list

### ISSUE THREAD

**Issue by porcherie** [will-stone/browserosaurus#586]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

with last update 19.3.2 safari and brave browser are not visible anymore

### Expected Behaviour

safari and brave where correctly shown on menu

### Steps To Reproduce

update to 19.3.2 

### Browserosaurus version

19.3.2

### macOS version

13.0.1

### CPU Architecture

ARM

**Comment by henocookie** [comment]
+1 my install isn't finding Chrome or Safari but is finding Slack, Zoom, Discord and Firefox.

Performing a rescan, reset or quitting and reopening the app haven't resolved the bug.
 
<img width="712" alt="Screenshot 2022-11-21 at 11 28 59 am" src="https://user-images.githubusercontent.com/52792328/203039959-471d456e-f8ac-4d16-9ec1-1f32e9a472eb.png">

**Comment by will-stone** [comment]
Dupe if #572
