### ISSUE TITLE
Browsers missing in 19.3.2 making it a no-go update

### ISSUE THREAD

**Issue by tilama** [will-stone/browserosaurus#589]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

Previous to Version 19.3.2 I had 5 browsers listed: Safari, Chrome, Brave, Firefox, Slack. 

After updating to 19.3.2 I initially had 3 browsers listed; I tried a Reset and now I only have 2 browsers listed: Slack and Firefox.

### Expected Behaviour

I should have all installed browsers listed as was the case prior to Version 19.3.2. 

On my system, browsers that I need listed are: Safari, Chrome, Brave, Firefox.

### Steps To Reproduce

Update to 19.3.2.

### Browserosaurus version

19.3.2

### macOS version

12.6.1

### CPU Architecture

ARM

### Anything else?

I've reverted to 19.3.0 to restore functionality.

**Comment by will-stone** [comment]
Dupe #572
