### ISSUE TITLE
v20: missing browsers: Tor Browser and Safari Technology Preview

### ISSUE THREAD

**Issue by i0ntempest** [will-stone/browserosaurus#599]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

Tor Browser and Safari Technology Preview are not found. I've tried restarting the app multiple times.

### Expected Behaviour

It should find those

### Steps To Reproduce

Upgrade to v20, open the app, observe the browser list

### Browserosaurus version

20.0

### macOS version

13.0.1

### CPU Architecture

Intel

### Anything else?

Also unrelated, I think the list is getting kinda bloated with all those non-browser apps. A way to hide those apps would be great.

**Comment by i0ntempest** [comment]
Just took a look at the code. Seeme like you're using the shortened names to search those apps (e.g. Safari TP), so it won't find it.

**Comment by will-stone** [comment]
Thanks. There will be some of these issues; have you seen the release notes? https://github.com/will-stone/browserosaurus/releases/tag/v20.0.0

Would you like to PR those fixes in?

**Comment by i0ntempest** [comment]
> Thanks. There will be some of these issues; have you seen the release notes? https://github.com/will-stone/browserosaurus/releases/tag/v20.0.0
> 
> Would you like to PR those fixes in?

Sure, shouldn’t be hard to do. I’ll shoot you a PR when I’m back in macOS.
