### ISSUE TITLE
Firefox Developer Edition not being picked / discovered in v20.0.0

### ISSUE THREAD

**Issue by sankalp-khare** [will-stone/browserosaurus#602]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

Despite re-scanning Firefox Developer Edition does not show up in the list of browsers.

### Expected Behaviour

Firefox Developer Edition should be discovered and listed.

### Steps To Reproduce

Check the list of browsers pop-up, or in the preferences.

Issue re-scan and re-confirm that Firefox Developer Edition does not appear.

### Browserosaurus version

20.0.0

### macOS version

13.0.1

### CPU Architecture

ARM

**Comment by sankalp-khare** [comment]
I looked at https://github.com/will-stone/browserosaurus/blob/e86c60c5c576f20d62856eff371a964945bbf74d/src/config/apps.ts and the name of the folder under `/Applications` matches:
```
❯ ls -1d /Applications/Firefox*
/Applications/Firefox Developer Edition.app/
```

**Comment by will-stone** [comment]
Fixed in this PR https://github.com/will-stone/browserosaurus/pull/600 it’s merged so will be in next release.

**Comment by sankalp-khare** [comment]
@will-stone I confirm this is fixed. Thanks a lot!
