### ISSUE TITLE
Rescan does not update found app count on browser removal

### ISSUE THREAD

**Issue by mreid-tt** [will-stone/browserosaurus#606]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

I installed Microsoft Teams and then based on the app performance I decided to remove it. In B I clicked refresh and noted that the app was removed from the browser list . Unfortunately the count of browsers on the main window didn't decrement back to the original value.

### Expected Behaviour

Browser count should match detected list after refresh and certainly after app quit and re-launch.

### Steps To Reproduce

1. Install new browser
2. Within B click refresh and assign key to it
3. Use browser and then uninstall browser
4. Within B click refresh and observe list and count

### Browserosaurus version

20.0.0

### macOS version

13.1

### CPU Architecture

ARM

### Anything else?

This is a minor cosmetic issue so not a high priority since I'm sure a reset would workaround the issue.

**Comment by will-stone** [comment]
Ah yes, I've seen this too. It's because [this line](https://github.com/will-stone/browserosaurus/blob/main/src/renderers/prefs/components/organisms/pane-general.tsx#L48) doesn't take into account which apps have `isInstalled` boolean on them. I'll fix this in due course. Thanks! 🙂
