### ISSUE TITLE
Update button does not working

### ISSUE THREAD

**Issue by Derrin616** [will-stone/browserosaurus#608]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

When i click the update button it simply does nothing

### Expected Behaviour

It will download the update and install it

### Steps To Reproduce

1. Go to the settings.
2. Click general
3. Click Download Update

### Browserosaurus version

19.1.0

### macOS version

Ventura 13.1

### CPU Architecture

ARM

**Comment by will-stone** [comment]
Sorry, I’m not sure I can help with this one. Please download the latest release from GitHub 🙂
