### ISSUE TITLE
Using a lot of CPU cycles

### ISSUE THREAD

**Issue by mggithub1** [will-stone/browserosaurus#610]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

After running for a few minutes, fans went into overdrive. Looked at Activity Monitor and saw Browersaurus at the top of CPU usage.

![Screen Shot 2022-12-23 at 9 59 16 AM](https://user-images.githubusercontent.com/121307840/209367849-6e1aeaac-d1ae-4ae0-be71-f73359203e3d.png)

### Expected Behaviour

Didn't expect it to use so much CPU.

### Steps To Reproduce

Launched Browsersaurus, let run in background.

### Browserosaurus version

20.0.1

### macOS version

12.6.2

### CPU Architecture

Intel

**Comment by will-stone** [comment]
Hmmm, strange. Unfortunately I no longer own an Intel Mac (home or work) so I can’t really see if it’s architecture specific. Does it work okay otherwise? Find all your apps? Picker/preferences open and seem to behave okay?

**Comment by mggithub1** [comment]
Browsersaurus found all my apps, yes. 

Since this issue first occurred, it has happened since. Browsersaurus has been playing nicely.

**Comment by will-stone** [comment]
Hey @mggithub1 Are you saying Browserosaurus is now _not_ using a lot of CPU? Are you happy to close the issue?

**Comment by mggithub1** [comment]
Yes—please close the issue. Everything appears to be working well now.
