### ISSUE TITLE
Browsersaurus popup menu vanishes when using multiple desktops since MacOS 13.

### ISSUE THREAD

**Issue by roland-muc** [will-stone/browserosaurus#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

I use Browsersaurus for quite some time and the problem started on MacOS 13. Before updating it worked like a charm. I use several desktops on MacOS and if you click on a link in another desktop than the first / main one, the context menu does not appear in the current desktop view but moves directly to the "main / first" desktop view, then the context menu appears shortly and vanishes. After quitting Browsersaurus and start it again, the behavior is normal as it was - the expected behavior. I did not figure out when the wrong behavior start yet. I assume after the system goes to sleep. I try to figure that out and update the this report.

### Expected Behaviour

Expected is that the context menu selecting the app pops up in the active desktop view and I can select the app directly after clicking the link

### Steps To Reproduce

I have a video demonstrating the behavior and can send it.
1. After some time or system went to sleep
2. Click a link in the non  main / first desktop
result is the the desktop is changed and the pop up appears a very short time in the main desktop. No change to click something before it vanishes. 

This problem was starting after switching to MacOS 13.0 and with some older browsersaurus versions as well.

### Browserosaurus version

latest, 20.0.2

### macOS version

13.1

### CPU Architecture

Intel

### Anything else?

Video recording available on request, prefer to send via private message.

**Comment by will-stone** [comment]
Thanks, being tracked on https://github.com/will-stone/browserosaurus/issues/595
