### ISSUE TITLE
FirefoxDeveloperEdition is not detected even if it's in apps.ts

### ISSUE THREAD

**Issue by mclion** [will-stone/browserosaurus#616]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

Browsersaurus does not detect FirefoxDeveloperEdition even if I hit RESCAN.

### Expected Behaviour

FirefoxDeveloperEdition should be detected and displayed in the list.

### Steps To Reproduce

1. Have FirefoxDeveloperEdition on your computer in the Application folder.
2. Open preferences of Browserosaurus.
3. Hit RESCAN near Find Apps.
4. Check the Apps.

### Browserosaurus version

20.0.2

### macOS version

13.2

### CPU Architecture

Intel

### Anything else?

I think the problem is in the naming. FirefoxDeveloperEdition is (now) named FirefoxDeveloperEdition.app, maybe it was with spaces before? In the apps.ts the string identifier is with spaces.

**Comment by will-stone** [comment]
Ah cool, you fancy submitting the PR for that fix?

**Comment by will-stone** [comment]
In case you're not familiar with the codebase, there's a [document on adding support for a new browser](https://github.com/will-stone/browserosaurus/blob/main/guide/supporting-a-browser-or-app.md) that will provide the info you need to update this, but here's the line you will need to change: https://github.com/will-stone/browserosaurus/blob/main/src/config/apps.ts#L56

**Comment by will-stone** [comment]
Ooo, thanks @askazakov 👍
