### ISSUE TITLE
Arc browser not supported

### ISSUE THREAD

**Issue by lovozeto** [will-stone/browserosaurus#622]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

I have [Arc](https://arc.net) as my chromium browser but the app fails to add it as an option to open links.
<img width="712" alt="Screenshot 2023-02-22 at 12 38 23 PM" src="https://user-images.githubusercontent.com/26152210/220710318-be154f1f-08ef-4307-a013-d2a53b7ef41e.png">

I did try doing a factory reset of the the app, but it didn't work

### Expected Behaviour

Arch should pop-up in the list after scanning for new compatible apps

### Steps To Reproduce

1. Install Arc
2. Open Browsersaurus
3. Click on scan apps
4. Go to App list

### Browserosaurus version

18.1.0

### macOS version

13.2

### CPU Architecture

ARM

**Comment by will-stone** [comment]
Can you please upgrade to 20.0.2 and see if that fixes your issue?

https://github.com/will-stone/browserosaurus/releases/tag/v20.0.2

**Comment by will-stone** [comment]
Let me know if the issue persists after you've updated to latest. Closing.

**Comment by susodapop** [comment]
Just confirming that Arc browser appears for me on version 20.7 of Browserosaurus.
