### ISSUE TITLE
Regression: Look for browsers also under ~/Applications folder

### ISSUE THREAD

**Issue by kopach** [will-stone/browserosaurus#632]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

This is regression of existing defect described here https://github.com/will-stone/browserosaurus/issues/150

### Expected Behaviour

Browserosaurus should see browsers from `~/Applications` folder 

### Steps To Reproduce

1. `mkdir ~/Applications` (if doesn't exist)
2. `move /Applications/Firefox ~/Applications/Firefox`
3. Open link in browserosaurus
4. No Firefox browser detected by browserosaurus

### Browserosaurus version

20.2.0

### macOS version

13.3

### CPU Architecture

ARM

### Anything else?

As an option (if you don't want to hard code `~/Applications` folder) - there could be config with `paths` to be used to search for apps

**Comment by kopach** [comment]
Found workaround

1. right click browser (e.g. Firefox) -> select "Make alias" -> you'll get file with name "Firefox alias"
2. move alias to `/Applications` folder
3. rename alias to <Browser name>.app, e.g. "Firefox.app"
4. re-scan apps with Browserosaurus

At this  point browser is found correctly

**Comment by will-stone** [comment]
I've never found the need to put apps anywhere other than `/Applications`. However, please feel free to edit [this line](https://github.com/will-stone/browserosaurus/blob/a7ea62f305eb2fd0b001b8f6bffc77f934529fdf/src/main/utils/get-installed-app-names.ts#L13) and submit a PR. Thanks 😄
