### ISSUE TITLE
c

### ISSUE THREAD

**Issue by sibat119** [will-stone/browserosaurus#635]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

When clicking on a link in small screen app (e.g. outlook), it takes me to another app opened on full screen (e.g. vs code) instead of showing me the preferred option for opening the link.

### Expected Behaviour

When clicking on a link in small screen app, it should show me the preferred option for opening the link.

### Steps To Reproduce

1. go to outlook/discord/whatsapp not opened full screen
2. click on a link

### Browserosaurus version

20.2.0

### macOS version

13.3.1 (22E261)

### CPU Architecture

ARM

**Comment by will-stone** [comment]
Sorry but we need more information.
