### ISSUE TITLE
Not possible to add key on 20.2.1

### ISSUE THREAD

**Issue by porcherie** [will-stone/browserosaurus#636]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

It is not possible to add key shortcut to browser since updating to 20.2.1

### Expected Behaviour

It should be possible to enter custom key

### Steps To Reproduce

https://www.loom.com/share/f091e0434415476ebbd64ab05ca1a019

### Browserosaurus version

20.2.1

### macOS version

13.3.1

### CPU Architecture

ARM

**Comment by will-stone** [comment]
Hi. Not at my computer right now but I can see in your video that you don’t see a cater but can you please confirm pressing a letter does nothing?

**Comment by porcherie** [comment]
yes it does nothing

**Comment by will-stone** [comment]
Cool. And downgrading to 20.2.0 fixes the issue? All releases can be found here: https://github.com/will-stone/browserosaurus/releases

**Comment by porcherie** [comment]
Yes downgrade to previous version fix the issue

**Comment by will-stone** [comment]
Fixed in v20.2.2

**Comment by mreid-tt** [comment]
@will-stone, confirmed that v20.2.2 resolves this issue. Much thanks for the quick turnaround.
