### ISSUE TITLE
JavaScript error occurred

### ISSUE THREAD

**Issue by dinauu** [will-stone/browserosaurus#638]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

When I run Browserosaurus, I get this error:
<img width="503" alt="Screenshot 2023-05-04 at 12 29 29" src="https://user-images.githubusercontent.com/8520806/236156649-3b9b25ab-0eca-4ff4-b539-a8cc391ded74.png">

Tried installing from the release page and from homebrew.

### Expected Behaviour

It works properly.

### Steps To Reproduce

1. Install Browserosaurus from the release page or from homebrew.
2. Launch it.
3. Get an error.

### Browserosaurus version

20.2.2

### macOS version

macOs Ventura 13.3.1 (a)

### CPU Architecture

ARM

**Comment by will-stone** [comment]
Thanks, this is fixed in v20.3.0 👍
