### ISSUE TITLE
When working with multiple screens, Browserosaurus will change to main display.

### ISSUE THREAD

**Issue by ncesar** [will-stone/browserosaurus#642]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/main/guide/supporting-a-browser-or-app.md).

### Current Behaviour

1. Have more than 1 display
2. Go to your secondary screen and click on a Link
3. Browserosaurus should have opened the popup in the secondary screen but instead, it opens in the primary screen, changing my screen to the primary.

### Expected Behaviour

Browserosaurus should have opened the popup in the secondary screen but instead, it opens in the primary screen

### Steps To Reproduce

1. Have more than 1 display
2. Go to your secondary screen and click on a Link
3. Browserosaurus should have opened the popup in the secondary screen but instead, it opens in the primary screen.

### Browserosaurus version

20.3.1

### macOS version

Ventura 13.4

### CPU Architecture

ARM

### Anything else?
This is only fixed when I re-open the app. This also seems to happen when you create a new screen that was not present b efore.
_No response_

**Comment by will-stone** [comment]
Thanks. Dupe: https://github.com/will-stone/browserosaurus/issues/595
