### ISSUE TITLE
'Restore recently closed URL' does not work when the app is relaunched

### ISSUE THREAD

**Issue by navinthomas** [will-stone/browserosaurus#643]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/main/guide/supporting-a-browser-or-app.md).

### Current Behaviour

If the app is quit and launched again, it seems to "forget" what the previous recently closed URL was. Clicking 'Restore recently closed URL' does not open the expected URL, instead the chosen browser just opens up and then nothing happens.

This is a bit frustrating because of https://github.com/will-stone/browserosaurus/issues/595. Quitting the app and relaunching the app would have been a viable workaround for that issue until it is fixed upstream.

### Expected Behaviour

Restore recently closed URL should be able to restore the previous URL like normal, even if the app was just quit and relaunched.

Based on my understanding of the description of tag [v10.3.0](https://github.com/will-stone/browserosaurus/releases/tag/v10.3.0), the URL should still be accessible if the app was relaunched and the button should work as normal. If the URL is no longer accessible, then the Restore recently closed URL option should be grayed out.

### Steps To Reproduce

1. Click any link to trigger the Browserosaurus pop-up
2. Dismiss the pop-up or open the link with any browser
3. Quit the Browserosaurus app and re-launch it
4. Click the Browserosaurus menubar icon and click 'Restore recently closed URL'
5. The Browserosaurus pop-up appears as expected
    - The pop-up does not preview the URL's domain like, for example, "twitter.com". Refer screenshot 1 below.
6. Clicking any of the browser options will open the corresponding browser, but the expected URL is not loaded. In fact, the browser just loads up and nothing happens.

### Browserosaurus version

20.3.1

### macOS version

13.4

### CPU Architecture

ARM

### Screenshot 1
The pop-up does not preview the URL's domain like, for example, "twitter.com". 
<img width="362" alt="SCR-20230621-mokn" src="https://github.com/will-stone/browserosaurus/assets/34918736/ccfe59f6-ff82-468a-b23d-f1e22a47c89a">

**Comment by will-stone** [comment]
Hi @navinthomas It's really just a "Open Picker window" option. I'd rather not store the URL in state as it can be a security concern; I once had a request from someone in China saying they were in a position where their computer could get seized and B was storing clicked links that could be used against them.
I'm happy to change the text to say "Open Picker window". In fact, I think it used to say that, but people got confused by the functionality of B, thinking it's only purpose was to act as a browser launcher 😕

**Comment by navinthomas** [comment]
@will-stone If it's a security concern, then my suggestion would be to just grey out or hide the option when the app is launched initially. That way, the text need not be changed, and the app user experience remains the same.

**Comment by will-stone** [comment]
I use it to open the Picker for development.

**Comment by navinthomas** [comment]
In that case, maybe it's more useful to keep it this. Anyway, this is basically a very unlikely edge case. I don't think people in general are relaunching the app as frequently as I am. So, it shouldn't be a huge inconvenience for others.
