### ISSUE TITLE
Not seeing separate entries for EDGE (Mac) and EDGE (Windows) on Mac with Parallels installed

### ISSUE THREAD

**Issue by divebc** [will-stone/browserosaurus#645]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/main/guide/supporting-a-browser-or-app.md).

### Current Behaviour

On a Mac with Parallels Desktop 18 with Application concurrence enabled, Browserosaurus does not differentiate between the MAC and Windows version of browsers as separate installs.

On my device, anything sent to EDGE is now defaulting to sending to the Windows version, vs being able to select between the WINDOWS and MACOS versions.

The same applies for CHROME, Firefox and any other browser that is installed natively and in the Parallels Desktop.

With both applications are named the same, it seems that Browserosaurus can not handle a situation with a name conflict. 

### Expected Behaviour

I would expect that BOTH OS versions to be seen, and treated as separate applications when Scan is complete allowing for listing of both in the browser list.

Alternatively, I would expect Browserosaurus to detect a name clash and append a modifier on the system to account for the conflict.

Regardless of type of resolution, both browsers should be visible.

### Steps To Reproduce

Install Parallels 18, and enable Application Concurrence
Complete a Browserosaurus scan
Click a link - it will default to one or the other

### Browserosaurus version

20.3.1

### macOS version

13.4.1

### CPU Architecture

ARM

### Anything else?

<img width="647" alt="Screenshot 2023-06-27 at 10 54 26 AM" src="https://github.com/will-stone/browserosaurus/assets/3535943/b964713b-89c5-486f-a20a-e704a8b76dc2">

**Parallels settings for application concurrence**

<img width="609" alt="Screenshot 2023-06-27 at 11 03 56 AM" src="https://github.com/will-stone/browserosaurus/assets/3535943/420d143a-1398-43d7-8c6f-fc4482f91f56">

List of the Apps as visible within Browserosaurus - **Note** ICON does not have white backdrop indicating Windows APP

<img width="186" alt="Screenshot 2023-06-27 at 11 12 52 AM" src="https://github.com/will-stone/browserosaurus/assets/3535943/522cce54-d126-4f1a-ba44-99da4a1e9d25">

Edge Mac icon (white backdrop)

<img width="193" alt="Screenshot 2023-06-27 at 11 13 04 AM" src="https://github.com/will-stone/browserosaurus/assets/3535943/65fa0fc5-2a62-421c-934c-315ba02e2b4a">

Edge Windows icon (no backdrop)

**Comment by will-stone** [comment]
Thanks but this only works with Mac apps.

**Comment by divebc** [comment]
@will-stone - Noted and expected.  I was just curious as the power of Browserosaurus is the ability to run multiple browsers and direct the URL to the browser of choice.  

For our myself and our other Devs the tool allows us to direct to the browser of our choice.  In some instances we need run "older" and "current" releases where this same issue would occur.   The Mac/Windows in our case, is where we have run into this conflict, but we would love to use it to simplify cross platform testing (Mac/Windows.

Much appreciated tool either way, and thanks again for such a great tool.
