### ISSUE TITLE
The browser selection pop-up appears so briefly that selecting one isn't possible

### ISSUE THREAD

**Issue by carlos-cajina** [will-stone/browserosaurus#646]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/main/guide/supporting-a-browser-or-app.md).

### Current Behaviour

Seemingly at random, Browserosaurus stops working: when clicking on a link, the browser selection pop-up appears for only a few seconds, without giving time to choose one. The only way to "fix" this is to close the app and re-open it.

### Expected Behaviour

When clicking on a link, the browser selection pop-up appears and stays open until a selection is made.

### Steps To Reproduce

Can't reproduce using steps as the strange behavior seems to happen at random.

### Browserosaurus version

20.3.1

### macOS version

13.4.1 (22F82)

### CPU Architecture

ARM

### Anything else?

Thank you!

**Comment by will-stone** [comment]
Hi. Is this in full screen apps?

**Comment by carlos-cajina** [comment]
Hello, good day- It's not. I don't normally use apps in full screen. I checked the related thread but could not find something useful for my case. Thanks again!

**Comment by will-stone** [comment]
Okay, please see if you can narrow down the issue to a particular set of steps. Thanks 😊

**Comment by will-stone** [comment]
Nice. Yeah more to the point: Electron is relying on this state. It does sound like this is related to other ticket so I’m closing for now. If the other issue gets fixed and this is still happening, feel free to reopen this ticket.

**Comment by carlos-cajina** [comment]
Hi! – Found another piece of the puzzle although the malfunction still happens randomly: **it happens on apps open on a second desktop**. If I move the app to the main desktop, Browserosaurus works as expected. Closing and re-opening the app is still the workaround.

**Comment by puniserv** [comment]
Hey @will-stone,
I have similar problem. Version: 20.9.1, Sonoma 14.6.1 (23G93), Slack Version 4.41.97
https://github.com/user-attachments/assets/9140cf18-4f37-4ed9-be35-82441fdc683e

After browserosaurus restart, first click always work. Issue only in slack, maybe it's connected with slack link popover 🤔 
What data do you need? :)
