### ISSUE TITLE
When Using Mission Control Browserosarus Popup Always Opens on Desktop 1

### ISSUE THREAD

**Issue by CMWalt** [will-stone/browserosaurus#663]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/main/guide/supporting-a-browser-or-app.md).

### Current Behaviour

When using "Mission Control," Browserosaurus popup always opens on "Desktop 1."

### Expected Behaviour

Browserosarus popup should open on the desktop the hyperlink was clicked on.

### Steps To Reproduce

Open multiple Desktops in Mission Control and click on a hyperlink within any app on any desktop other than "Desktop 1."

### Browserosaurus version

20.5.0

### macOS version

13.5.2

### CPU Architecture

ARM

### Anything else?
While I see any existing bug submission with a related topic, I created a new bug post because this is a focused issue that does not concern fullscreen mode.

**Comment by will-stone** [comment]
Hi. This sounds like it’ll be related to this: https://github.com/will-stone/browserosaurus/issues/595
