### ISSUE TITLE
Firefox opens a blank tab rather than a link

### ISSUE THREAD

**Issue by shanecranor** [will-stone/browserosaurus#679]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/main/guide/supporting-a-browser-or-app.md).

### Current Behaviour

firefox opens a blank tab rather than the link 

### Expected Behaviour

I would expect firefox to open the link I clicked rather than an empty tab

### Steps To Reproduce

Click on a link outside of firefox and use browsersaurus to open firefox. Firefox opens a new window that is blank

### Browserosaurus version

20.7

### macOS version

14.3

### CPU Architecture

Intel

### Anything else?

I was having some issues with firefox profiles so that could be related somehow

**Comment by will-stone** [comment]
Hi, I am unable to reproduce this and I use Firefox most of the time. How about resetting Firefox and seeing if that fixes it? Backup first, of course 🤓 If that doesn't work, a video of the issue would great.

**Comment by shanecranor** [comment]
> Hi, I am unable to reproduce this and I use Firefox most of the time. How about resetting Firefox and seeing if that fixes it? Backup first, of course 🤓 If that doesn't work, a video of the issue would great.

I reset firefox and it asked which firefox profile to open when I clicked on the link. I clicked the correct profile and it opened the link as expected. But now subsequent clicks open a blank tab.

**Comment by will-stone** [comment]
Oh, I’ve never really tried multiple profiles for Firefox. Happy to look at a PR if you or others are able to find the issue. My guess would be that it’s an upstream macOS issue though; all Browserosaurus does is run the `open` command.

**Comment by shanecranor** [comment]
> Oh, I’ve never really tried multiple profiles for Firefox. Happy to look at a PR if you or others are able to find the issue. My guess would be that it’s an upstream macOS issue though; all Browserosaurus does is run the `open` command.


looks like you can launch different profiles with this, I'm not sure it is possible with the `open` command 
`/Applications/Firefox.app/Contents/MacOS/firefox -P "correct-profile" "https://example.com"`

After some debugging it seems like the issue was that I had two Firefox.app, one on the desktop and one in the applications folder (not intentionally, leftover from debugging a different firefox issue). It would probably be cool to get multi profile support for Firefox eventually, but I don't actually really use multiple profiles, so its not a big deal.

Ty for the quick responses :)

**Comment by shanecranor** [comment]
resolved

**Comment by will-stone** [comment]
Oh cool, thanks for digging into it, and updating here with the issue. It may help others in the future. 

Multi profile support isn’t something I use either so won’t have priority.
