### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by fidpa** [will-stone/browserosaurus#686]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/main/guide/supporting-a-browser-or-app.md).

### Current Behaviour

Happens on both my machines (Intel+M1), when I try to update.
![MBA](https://github.com/will-stone/browserosaurus/assets/97551772/3dd25d94-bf7d-4968-bae6-894da94423c2)

### Expected Behaviour

no error message

### Steps To Reproduce

Try to install update

### Browserosaurus version

20.8.0

### macOS version

14.4.1

### CPU Architecture

ARM

**Comment by will-stone** [comment]
Oh no! Does deleting the app and reinstalling it help?

**Comment by fidpa** [comment]
I don't want to reassign all Shortcuts and reorderall my Apps but prefer to wait for it to get eventually fixed.

**Comment by will-stone** [comment]
Well I don't have much to go on, as I can't replicate it so...
