### ISSUE TITLE
Safari not found

### ISSUE THREAD

**Issue by ZTfer** [will-stone/browserosaurus#69]
I can't find safari to open my link

**Comment by will-stone** [comment]
Thanks. I see this is your first issue, please read the link that was in the issue template: https://css-tricks.com/open-source-etiquette-guidebook/#article-header-id-1 and provide enough information as possible. Make sure you've got Safari ticked in the preferences.

**Comment by ZTfer** [comment]
Thanks for your creative work, and I have some problem with this app:

when I open a link in mail.app,i only have 2 browser to use, actually I have Safari Chrome and Firefox,but there only Chrome and Firefox, I can't find Safari to open my link.

My Mac info:
macOS High Sierra, 10.13.6
language: Chinese

**Comment by will-stone** [comment]
Ah, I reckon this has to do with the fact that Safari is probably called something else in non-English languages, and the apps are scanned for browsers by name.

Please can either of you run `system_profiler SPApplicationsDataType >> installedApps.txt` and attach the resulting file.

The easiest solution to this (if it only affects Safari) is to always show Safari as we know it's on every Mac.

**Comment by will-stone** [comment]
Please try https://github.com/will-stone/browserosaurus/releases/tag/v4.2.7 and let me know if it fixes it the issue, including whether it actually opens Safari when you click a link.

**Comment by ZTfer** [comment]
I just download and install v4.2.7, this bug fixed,thank you very much.

**Comment by ZTfer** [comment]
Yes, it actually opens the link when I select Safari
