### ISSUE TITLE
Opening issue with virtual spaces - hides in the background

### ISSUE THREAD

**Issue by ventz** [will-stone/browserosaurus#698]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/main/guide/supporting-a-browser-or-app.md).

### Current Behaviour

When you use Virtual spaces, and for example have something with a link in space 1 and your browser in space 2, when you click on space 1 it moves over to space 2, and seems to immediately hide the launcher.

See attached video.

### Expected Behaviour

Launcher staying visible in the auto changed to space.

### Steps To Reproduce

Setting browser in another virtual space, and then opening link from a different space.

### Browserosaurus version

20.9.1

### macOS version

15.0 (24A335)

### CPU Architecture

ARM

### Anything else?

https://github.com/user-attachments/assets/7d8ec92b-639b-4fc7-b979-2b8c6bff2e7b

**Comment by jotabe87** [comment]
Came here to report exactly this. Sometimes it moves to another space (like in the video) and sometimes it just closes the window with the Browser list so fast that I can't make any selections (selection window just blinks).

**Comment by lucasfoussier** [comment]
I don’t know if it is related but I have the same issue, on my Slack App.

I can see the during a brief period the prompt, but it disappears very fast.

https://github.com/user-attachments/assets/30fec1d7-f7a3-4c60-ac67-c6827f8f7c0e

**Comment by FlavioAandres** [comment]
> I don’t know if it is related but I have the same issue, on my Slack App.
> 
> I can see the during a brief period the prompt, but it disappears very fast.
> 
>  Enregistrement.de.l.ecran.2024-11-08.a.10.20.30.mp4

Same behavior on my side, had to close entirely browserosaurus and then click on a link to make it work again

**Comment by will-stone** [comment]
Oh not this again! Okay, reopening #595 and marking this as dupe 🙄 This is an upstream issue with Electron.

**Comment by ventz** [comment]
Sorry! - but thank you for checking into it! :)
