### ISSUE TITLE
[Feature Request] Support for Safari Technology Preview

### ISSUE THREAD

**Issue by xuebingli** [will-stone/browserosaurus#70]
It would be great to support opening URL in [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/).

I'm happy to give a shot to a PR if you're busy. A quick skim suggests I'll just need to add the browser to [activities.js](https://github.com/will-stone/browserosaurus/blob/5e290eb8c9d5b7b8b8bfc1e38b33c9b47da09b1d/src/config/activities.js).

Thank you for open sourcing the project @will-stone. It makes my daily life much easier.

**Comment by will-stone** [comment]
Hi. All done: https://github.com/will-stone/browserosaurus/releases/tag/v4.3.0

**Comment by xuebingli** [comment]
Thank you @will-stone! Really appreciate it.
