### ISSUE TITLE
On Mojave, URLs are slow to open

### ISSUE THREAD

**Issue by will-stone** [will-stone/browserosaurus#77]
This seems to be the same bug that's affecting my other Electron app (https://github.com/will-stone/SpotSpot/issues/24). When clicking an activity to open a URL with, the app is brought to the front (if running) but the new tab takes a second or two to open. This only started happening since upgrading to Mojave (boo!). Also, this only happens on the built version of B; when run in dev mode (`yarn start`), B behaves the same as it always did.

If anyone stumbles across this and knows the fix, please let me know! This affects both my home and work macs, therefore it's definitely an issue caused by Mojave (please no "me too" posts).

I'd like to experiment with upgrading Electron however this app uses Electron-Forge and it doesn't look like they are keeping v5 up-to-date with the latest Electron; it currently uses v1.8. They do have a v6 which uses Electron v3 but v6 of Electron-Forge is in beta and is plastered with notices of instability. I tried copying over my `src` dir to a brand new v6 Electron-Forge but it didn't work. Therefore, my plan is to start a v6 Electron-Forge and essentially start again, moving items over bit-by-bit. This can also be my opportunity to move over to TS. Unless... someone knows what the issue is and knows a fix.

**Comment by will-stone** [comment]
Have tried NW.js and it has the same problem: ok in dev, slow once packaged. This suggests it's a problem with Mojave or Node.

**Comment by hexcross** [comment]
Same here!

**Comment by will-stone** [comment]
Please let me know if you hear of a solution, whilst on your travels. Otherwise, please no "me too" posts. I've tested this on several Mojave machines and it affects all.

**Comment by CelsoSantos** [comment]
I don't know if this is related or if this is a new issue, but I installed Parallels today and now upon selecting the browser with which to open a link it will always open my bootcamp partition VM.

Is anyone able to test if this is an issue with Mojave or Parallels?

**Comment by will-stone** [comment]
I'd vote that that's a new issue. I don't use Parallels so won't be able to test that. To be honest, my love for this app has subsided since the start of this bug; it really makes it annoying to use. However, I've done everything I can think of to find the bug. Until an app with more clout suffers from the same bug, I can't see this getting fixed soon.

**Comment by CelsoSantos** [comment]
I've checked out the project and I'm trying to debug. I'm using VS Code but I'm having some trouble getting a debug configuration to execute, giving me errors with imports straight away at the first line..

Any chance I could get some pointers or a debug config to use with VS Code (or another editor)?

**Comment by will-stone** [comment]
Thanks for the offer of help. No need to fire-up Browserosaurus at all (the bug is not with Browserosaurus). My suggestion would be to start a new [Electron-Forge](https://electronforge.io/) (that's what this app uses) or Electron-Builder or NWjs app. Then add a button to the HTML and bind it to an eventListener that fires an open browser command:

```js
import { spawn } from 'child_process'
const button = document.getElementById('id-of-button')
button.addEventListener('click', () => {
  spawn('sh', [
    '-c',
    'open "http://google.com/" -a "Google Chrome"',
  ])
})
```

Run it in development mode and you'll notice that the button will open Chrome and a new tab instantly. Now package the app (with forge that's `electron-forge package --platform=darwin --arch=x64`) and run the packaged app. Click the button: it'll have the delay.

The bug is simply that running `spawn` (or `exec` etc.) from a packaged Electron app on Mojave, has a couple of seconds delay.

Good luck. Please let me know how you get on.

**Comment by abuisman** [comment]
@will-stone It would help if you could build the bare application that you are describing. I created a new app with electron-forge, but when I add the event listener for my button there is no `document`.

**Comment by will-stone** [comment]
Hmmm, I can do. Sounds like you're putting the code in the main script rather than the renderer. I'll look into making a bare-bones electron-forge in the coming few days/week.

**Comment by abuisman** [comment]
Yes, I am. In the standard init there doesn’t really seem to be what looks like a ‘rendered’ to me. I could be wrong of course:

```javascript
import { app, BrowserWindow } from 'electron';
import { spawn } from 'child_process'

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) { // eslint-disable-line global-require
  app.quit();
}

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow;

const createWindow = () => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
  });

  // and load the index.html of the app.
  mainWindow.loadURL(`file://${__dirname}/index.html`);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  const button = document.getElementById('mybutton')
  button.addEventListener('click', () => {
    spawn('sh', [
      '-c',
      'open "http://abuisman.nl/" -a "Brave Browser"',
    ])
  })

  // Emitted when the window is closed.
  mainWindow.on('closed', () => {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed.
app.on('window-all-closed', () => {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
```

**Comment by will-stone** [comment]
Yeah, so your `index.html` should be using a script (the renderer process). Put the button code in there, as you would with any website.

**Comment by abuisman** [comment]
Couldn't get it to work. I just run the code to open the page directly now, without a button, but straight on startup. Works fine for what we are doing ;)

**Comment by will-stone** [comment]
Ok peeps, here's a repo to demonstrate the issue: https://github.com/will-stone/electron-spawn-delay-demo

**Comment by will-stone** [comment]
Issue logged with Electron: https://github.com/electron/electron/issues/16166 Please 👍 the issue

**Comment by badouralix** [comment]
I believe the issue does not come from `child_process.spawn`, but from what happens then in the subprocess. For what I saw, the browser gets the focus immediately after choosing it in Browserosaurus, which shows that `/usr/bin/open` already started. Then it takes a few seconds to effectively open the new tab.

Here is a small experiment based on [will-stone/electron-spawn-delay-demo](https://github.com/will-stone/electron-spawn-delay-demo) to try to understand how it happens: [badouralix/output.txt#L8-L13](https://gist.github.com/badouralix/9d8ab6c7cd2a32095de457bb80b05a9b#file-output-txt-L8-L13)

```bash
$ open out/electron-forge-6-beta-darwin-x64/electron-forge-6-beta.app
$ cat /tmp/electron-spawn-delay-demo-{a,b,c,d}
1548644782 # time before subprocess spawn
1548644782 # time after subprocess spawn, before calling open
1548644788 # time after calling open, before process exit 
1548644788 # time after subprocess exit
```

This issue might be related to https://github.com/macvim-dev/macvim/issues/763.

I also noticed that the issue only holds when Browserosaurus is started as an app (from the launchpad or finder for instance), e.g. its ppid is `launchd`:

```bash
$ pstree -g3 -ws Browserosaurus
─┬= 00001 root /sbin/launchd
 └─┬= 36799 badouralix /Applications/Browserosaurus.app/Contents/MacOS/Browserosaurus
   ├─── 36800 badouralix /Applications/Browserosaurus.app/Contents/Frameworks/Browserosaurus Helper.app/Contents/MacOS/Browserosaurus Helper --type=gpu-process --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=0,1,10,24,27,38,41,49,55,63,65,66,67,68,75,76,78,86,87,88,91,94 --disable-gl-extensions=GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent --gpu-vendor-id=0x8086 --gpu-device-id=0x5927 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-active-vendor-id=0x8086 --gpu-active-device-id=0x5927 --service-request-channel-token=...
   ├─── 36801 badouralix /Applications/Browserosaurus.app/Contents/Frameworks/Browserosaurus Helper.app/Contents/MacOS/Browserosaurus Helper --type=renderer --no-sandbox --primordial-pipe-token=... --lang=en-US --app-path=/Applications/Browserosaurus.app/Contents/Resources/app --enable-experimental-web-platform-features --node-integration=true --webview-tag=true --no-sandbox --enable-pinch --num-raster-threads=2 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,34037;0,11,34037;0,12,34037;0,13,3553;0,14,3553;0,15,3553;0,16,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,34037;1,11,34037;1,12,34037;1,13,3553;1,14,3553;1,15,3553;1,16,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,34037;2,11,34037;2,12,34037;2,13,3553;2,14,3553;2,15,3553;2,16,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,34037;3,13,34037;3,14,3553;3,15,34037;3,16,34037;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,34037;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,34037;4,13,34037;4,14,3553;4,15,34037;4,16,34037 --service-request-channel-token=... --renderer-client-id=4
   └─── 36803 badouralix /Applications/Browserosaurus.app/Contents/Frameworks/Browserosaurus Helper.app/Contents/MacOS/Browserosaurus Helper --type=renderer --no-sandbox --primordial-pipe-token=... --lang=en-US --app-path=/Applications/Browserosaurus.app/Contents/Resources/app --enable-experimental-web-platform-features --node-integration=true --webview-tag=true --no-sandbox --enable-pinch --num-raster-threads=2 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,34037;0,11,34037;0,12,34037;0,13,3553;0,14,3553;0,15,3553;0,16,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,34037;1,11,34037;1,12,34037;1,13,3553;1,14,3553;1,15,3553;1,16,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,34037;2,11,34037;2,12,34037;2,13,3553;2,14,3553;2,15,3553;2,16,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,34037;3,13,34037;3,14,3553;3,15,34037;3,16,34037;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,34037;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,34037;4,13,34037;4,14,3553;4,15,34037;4,16,34037 --service-request-channel-token=... --renderer-client-id=6
```

On the other hand, if the binary is run from a shell, even though it has been built with `yarn run make`, Browserosaurus works perfectly fine! So until this issue is fixed, I run Browserosaurus in an always-opened shell with:

```bash
$ /Applications/Browserosaurus.app/Contents/MacOS/Browserosaurus &
[1] 39709
2019-01-28 00:04:23.248 Browserosaurus[39709:600255] *** WARNING: Textured window <AtomNSWindow: 0x7f8e276649e0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
# small warning here ^
```

The process tree is a bit different now:

```bash
$ pstree -g3 -ws Browserosaurus
─┬= 00001 root /sbin/launchd
 └─┬= 00533 badouralix/Applications/iTerm.app/Contents/MacOS/iTerm2
   └─┬= 91231 badouralix /Applications/iTerm.app/Contents/MacOS/iTerm2 --server login -fp badouralix
     └─┬= 91269 root login -fp badouralix
       └─┬= 91278 badouralix -zsh
         └─┬= 39709 badouralix /Applications/Browserosaurus.app/Contents/MacOS/Browserosaurus
           ├─── 39788 badouralix /Applications/Browserosaurus.app/Contents/Frameworks/Browserosaurus Helper.app/Contents/MacOS/Browserosaurus Helper --type=gpu-process --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=0,1,10,24,27,38,41,49,55,63,65,66,67,68,75,76,78,86,87,88,91,94 --disable-gl-extensions=GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent --gpu-vendor-id=0x8086 --gpu-device-id=0x5927 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-active-vendor-id=0x8086 --gpu-active-device-id=0x5927 --service-request-channel-token=...
           ├─── 39789 badouralix /Applications/Browserosaurus.app/Contents/Frameworks/Browserosaurus Helper.app/Contents/MacOS/Browserosaurus Helper --type=renderer --no-sandbox --primordial-pipe-token=... --lang=en-US --app-path=/Applications/Browserosaurus.app/Contents/Resources/app --enable-experimental-web-platform-features --node-integration=true --webview-tag=true --no-sandbox --enable-pinch --num-raster-threads=2 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,34037;0,11,34037;0,12,34037;0,13,3553;0,14,3553;0,15,3553;0,16,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,34037;1,11,34037;1,12,34037;1,13,3553;1,14,3553;1,15,3553;1,16,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,34037;2,11,34037;2,12,34037;2,13,3553;2,14,3553;2,15,3553;2,16,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,34037;3,13,34037;3,14,3553;3,15,34037;3,16,34037;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,34037;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,34037;4,13,34037;4,14,3553;4,15,34037;4,16,34037 --service-request-channel-token=... --renderer-client-id=4
           └─── 39790 badouralix /Applications/Browserosaurus.app/Contents/Frameworks/Browserosaurus Helper.app/Contents/MacOS/Browserosaurus Helper --type=renderer --no-sandbox --primordial-pipe-token=... --lang=en-US --app-path=/Applications/Browserosaurus.app/Contents/Resources/app --enable-experimental-web-platform-features --node-integration=true --webview-tag=true --no-sandbox --enable-pinch --num-raster-threads=2 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,34037;0,11,34037;0,12,34037;0,13,3553;0,14,3553;0,15,3553;0,16,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,34037;1,11,34037;1,12,34037;1,13,3553;1,14,3553;1,15,3553;1,16,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,34037;2,11,34037;2,12,34037;2,13,3553;2,14,3553;2,15,3553;2,16,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,34037;3,13,34037;3,14,3553;3,15,34037;3,16,34037;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,34037;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,34037;4,13,34037;4,14,3553;4,15,34037;4,16,34037 --service-request-channel-token=... --renderer-client-id=6
```

Note that the same experiment as earlier can be run on this workaround, the new tab opens instantaneously: [badouralix/output.txt#L1-L6](https://gist.github.com/badouralix/9d8ab6c7cd2a32095de457bb80b05a9b#file-output-txt-L1-L6)

```bash
$ ./out/electron-forge-6-beta-darwin-x64/electron-forge-6-beta.app/Contents/MacOS/electron-forge-6-beta &
$ cat /tmp/electron-spawn-delay-demo-{a,b,c,d}
1548644678 # time before subprocess spawn
1548644678 # time after subprocess spawn, before calling open
1548644678 # time after calling open, before process exit 
1548644678 # time after subprocess exit
```

Still need to understand why `/usr/bin/open` takes so much time to actually open the new tab. The environment variables in the main processes look quite the same. Same for the main process priorities. Maybe strace the subprocess?

**Comment by bitnot** [comment]
Looks like [macvim-dev/macvim#763](/macvim-dev/macvim/issues/763) is solved by signing the binary.
Is there anyone enrolled in Apple developer program who could try and [sign](https://electronjs.org/docs/tutorial/code-signing) Browserosaurus?

**Comment by CedricGatay** [comment]
Code signing resolves slowness, you can check it with the result of the app in v4.5.0 built with code Signing attached to the release available on my fork (https://github.com/CedricGatay/browserosaurus/releases/tag/v4.5.0-ct).

We (as my company) can contribute this project by providing the certificate, however I am almost certain that we can not commit it "in the wild". We can discuss about this ;)

**Comment by will-stone** [comment]
Hi @CedricGatay. I really appreciate your help in trying to resolve the issue. I'm not sure how I feel about the app having a sponsor though. I presume in a years time, the certificate will expire and I'd be looking for someone else to help me out. For the time being, I'd like to see if there's enough noise from the community that Apple will listen and stop borking the open source devs' apps. If not, I may bite the bullet and get myself a developer account.

**Comment by CedricGatay** [comment]
@will-stone I fully understand your point of view. Typically certificates are valid for a year (during the subscription validity). 
I propose myself as an help on this subject but you're forced of nothing. If you want I can sign binaries to put on release page while the issue is not fixed by another mean.

**Comment by CedricGatay** [comment]
For the record, it appears that the certificate I used expire on 2024-01-30, we've got clear sight ;)

**Comment by bitnot** [comment]
As a workaround I have created an Automator script that runs `/Applications/Browserosaurus.app/Contents/MacOS/Browserosaurus > /dev/null 2>&1 &` shell command and [added it to login items](https://stackoverflow.com/questions/6442364/running-script-upon-login-mac).

**Comment by kopach** [comment]
Thank you @bitnot, your workaround works for me

**Comment by will-stone** [comment]
And this is why I love open-source. Thanks @bitnot! I can use Browserosaurus again (without having to keep a terminal window open) 😄 Do you know if that is portable? I'm thinking I'll commit it to the repo and add it to the README and website as the official workaround.

**Comment by bitnot** [comment]
Hey @will-stone! To make sure I understand you question: what are you planning to commit to repo? Instruction or the workflow app binary itself?
I cannot find any documentation on portability, but I would assume the workflow app _should_ work on a different Mac as long as the path to the actual Browserosaurus app is the same (`/Applications/Browserosaurus.app/Contents/MacOS/Browserosaurus`).

BTW, AppleScript seems to do the job just as fine and the resulting app size is smaller (100kb AppleScript app vs 1.4mb Automator app).

If you open 
[this script](https://github.com/will-stone/browserosaurus/files/2821878/StartBrowserosaurus-source.zip) in "Script Editor" and export it as "Application", you would get [an app](https://github.com/will-stone/browserosaurus/files/2821861/StartBrowserosaurus.zip) that can be launched at start up (through login items).

**Comment by will-stone** [comment]
That's great! Right, I'm gonna commit that into the repo and will instructions in due course...

Thanks again, @bitnot

**Comment by will-stone** [comment]
I decided to bite the bullet and get an Apple Developer account. This means the release is now signed and this bug is officially fixed. However, this now means I incur a yearly cost of £79. Therefore, please consider a donation if you use the app. Thanks.

[![ko-fi](https://www.ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/Z8Z7V0KF)

**Comment by will-stone** [comment]
Also new website: https://browserosaurus.com/
