### ISSUE TITLE
I tried building for Mojave but all I get is spining wheel / blank

### ISSUE THREAD

**Issue by ghost** [will-stone/browserosaurus#78]
If I `git clean -fdx && yarn install && yarn start` (skipping the `yarn build-css` step) I get the following: 

<img width="505" alt="screenshot 2018-09-27 at 12 06 10" src="https://user-images.githubusercontent.com/31992054/46142383-b5e93f80-c24e-11e8-8b76-c4cdfd44a554.png">

If I include the `yarn build-css` step, I get the following: 

<img width="504" alt="screenshot 2018-09-27 at 12 07 27" src="https://user-images.githubusercontent.com/31992054/46142451-edf08280-c24e-11e8-896f-e820c6ba0b0d.png">
<img width="499" alt="screenshot 2018-09-27 at 12 07 34" src="https://user-images.githubusercontent.com/31992054/46142452-edf08280-c24e-11e8-80c8-d263c6d711ae.png">

The context menu popup is also blank when I click on a link (presumably because the functionality to scan system browsers hasn't been run) : 

<img width="599" alt="screenshot 2018-09-27 at 12 16 57" src="https://user-images.githubusercontent.com/31992054/46142542-4031a380-c24f-11e8-9a47-7eff55f17638.png">

This is the first time I've ever used Electron so I appologise that I can't offer much more in the way of info.

I also had to run the following steps to create a build (`yarn run make`) (from history file, not necessarily in order) : 

```
yarn install                                                                                                                                     
yarn build-css                                                                                                                                   
brew upgrade                                                                                                                                     
yarn build-css                                                                                                                                   
npm rebuild node-sass                                                                                                                            
yarn build-css                                                                                                                                   
yarn test                                                                                                                                        
yarn build-css                                                                                                                                   
npm update electron --save                                                                                                                       
yarn install    
```

**Comment by will-stone** [comment]
Hi. Yeah this happens to me sometimes too. Wipe it all out (start in new directory). Update to latest version of Yarn, then do as the README says. Your command history looks like you're trying everything to see what sticks 😆

```sh
yarn
yarn build-css # I don't know why you originally skipped this step
yarn start
```

Then... wait 10 seconds before you open the prefs or picker windows.

If you'd like a comparison, here's my current versions of things, and it starts just fine in dev mode:

```
node  10.11.0
npm   6.4.1
yarn  1.10.0
```

**Comment by bryanhuntesl** [comment]
Hmm versions seem very similar 
```
node --version
v10.11.0
npm --version
6.4.1
yarn --version
1.10.1
```

Purged and checked out again the repository : 

```
rm -rf  ./.^git
git checkout . 
```

Then tried 

```
yarn
yarn build-css # I don't know why you originally skipped this step
yarn start
```

Worth mentioning I'm on mojave with the dark theme - tried switching theme to default but still broke. 

There is also a warning when running the app - I'm not sure what it's trying to tell me though : 

```
2018-09-27 20:12:16.906 Electron[52142:1024120] *** WARNING: Textured window <AtomNSWindow: 0x7fe0a401c600> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
^C
```

**Comment by bryanhuntesl** [comment]
Reason I skipped the 'yarn build-css` before was because I suspected it was something to do with styling - so I thought it would be good to see what was behind the styling (not visible as opposed to not working).

**Comment by will-stone** [comment]
I see. I usually forget to build the css when I run it on a new machine or new directory, and it takes me a while to realise why it looks weird 🙃

That warning is ok. I get that too. 

So... is it still not working?

**Comment by bryanhuntesl** [comment]
Yep - still not working - weird eh ?

**Comment by bryanhuntesl** [comment]
This may not be relevant - but the lockfiles did change after I ran the `yarn install` step. 

I've attached a diff compated to master.

[post-yarn-install-lockfiles.diff.txt](https://github.com/will-stone/browserosaurus/files/2427720/post-yarn-install-lockfiles.diff.txt)

**Comment by bryanhuntesl** [comment]
Ok @will-stone - thanks for looking into it, who knows, I've run into this sort of problem a couple of times before with node stuff - hopefully this will be of use to you if the problem repeats later in your env. Sorry I don't have more of a clue/debugging skills, I'm very amateur when it comes to this stuff.
