### ISSUE TITLE
Stopped detecting firefox nightly

### ISSUE THREAD

**Issue by bendem** [will-stone/browserosaurus#79]
I've been using browserosaurus for a while and yesterday after a reboot, it stopped proposing firefox nightly.

I'm still on macos sierra (10.12.6). Let me know if I can provide more information

**Comment by will-stone** [comment]
Hmmm, maybe Firefox Nightly renamed their app (internally). Which version of Browserosaurus are you using?

**Comment by will-stone** [comment]
Run `system_profiler SPApplicationsDataType >> installedApps.txt` in terminal. Open the resulting file and search for "Nightly". It should show in there as "Firefox Nightly". If it's not in there at all, you may need to reinstall it; as this is the file that B get's its list of installed browsers from.

**Comment by bendem** [comment]
```
    Firefox Nightly:

      Version: 64.0a1
      Obtained from: Identified Developer
      Last Modified: 10/10/2018, 16:05
      Kind: Intel
      64-Bit (Intel): Yes
      Signed by: Developer ID Application: Mozilla Corporation (43AQ936H96), Developer ID Certification Authority, Apple Root CA
      Location: /Applications/Firefox Nightly.app
      Get Info String: Firefox Nightly 64.0a1
```
It's there.

**Comment by will-stone** [comment]
Ok, close Browserosaurus. Then remove your preferences with:

```sh
rm -rf ~/Library/Application Support/Browserosaurus/config.json
```

Reopen and see if it's picked it up now.

**Comment by bendem** [comment]
Yup, that fixed it. Not sure what was up. Maybe there could be an option when rescanning apps to remove that file?

**Comment by will-stone** [comment]
Maybe an artefact between versions and config logic. Could be in some future version's preferences but I'm not worried about it for now.
