### ISSUE TITLE
[Feature Request] Run as a service

### ISSUE THREAD

**Issue by mkubrycz** [will-stone/browserosaurus#84]
Hi, it would be nice if application could run in background as a service, without the menu bar icon visible all the time. [Scroll Reverser](https://github.com/pilotmoon/Scroll-Reverser) and [Spectacle](https://github.com/eczarny/spectacle) both have nice implementations of this functionality :)

Thanks for the app, it's great!

**Comment by will-stone** [comment]
Hi @mkubrycz, thanks for the suggestion. Indeed, I did consider this. However, without either a menubar item or a dock icon, I couldn't find a way for the user to quit the app or show a preferences pane. I think this may just be a limitation of using Electron. If you have precious space left in your menubar, may I suggest [Vanilla](https://matthewpalmer.net/vanilla/) or [Bartender](https://www.macbartender.com/).

**Comment by mkubrycz** [comment]
That's why I pointed out Scroll Reverser and Spectacle. Their flow is something like this:
1. hide menubar icon -> app works as a service
2. open app again from applications list or via Spotlight Search -> menubar icon is reenabled and/or preferences window opened
But if that's impossible with Electron then I understand :)
Thank's for the suggestions. I know both of those apps and I just don't like them for some reason :(

**Comment by will-stone** [comment]
Ha, I'm exactly the same; just can't bring myself to hide any menubar items. I suppose it depends if I release any more Electron apps 😆 

Ok, well let's close this for now but I'll keep it in mind if I notice Electron release anything that could help it be more service-like.
