### ISSUE TITLE
Build 1.0.4 contains development dependencies

### ISSUE THREAD

**Issue by Jackymancs4** [will-stone/browserosaurus#9]
* App version: 1.0.4
* Operating system: macOS 10.13.1

### Actual behavior

Your last build is more than double the size of the previous one. 
Looking inside the package I found that all the devDependencies where included (the most weight regarding babel). An unexpected behavior for electron-forge.
I'm also not been able to replicate it (all my builds in develpment evironments where >150MB).

The only thing I know that behave like this is the --no-prune flag on electron-packager.
Maybe some hidden environment configuration on your system?

Not a real problem to me. Just a note on that ;)

**Comment by will-stone** [comment]
Thanks! I did think it had bloated. I was using a newer version of Node/NPM so maybe that has caused an issue. I'll take a look later and see if there's anything else I can upgrade to fix, otherwise I'll just use the version of Node I know works.

**Comment by Jackymancs4** [comment]
Great! My config is npm 5.5.1 and node v6.11.4 (and with that it work for sure).
I think you are using some node v8like..

**Comment by Ornataweaver** [comment]
Hey @will-stone you keep referring this issue when I speak about size of the app. But this issue seems like foreign language to me.
- What are development dependancies?
- How do they effect the size to grow from 144 MB to 439.4 MB in one update?

**Comment by will-stone** [comment]
Don't worry if this makes no sense :) We're basically saying there was a bug with the build tool I've used on the project. v1.0.5 should hopefully fix the issue.

**Comment by will-stone** [comment]
v1.0.5 fixes the bloated last release. No idea what was the cause but I updated electron-forge, electron-compile, and electron-prebuilt-compile to latest versions, and that seemed to fix the issue.
