### ISSUE TITLE
[Feature Request] Contextual Browser Auto-selection

### ISSUE THREAD

**Issue by basiclines** [will-stone/browserosaurus#91]
First of all thank you for creating such a useful app and for making it open source!

Now the feature request:
I will like Browserosaurus to be smart enough to pick the browser for me and in given situations, let me decide which one to use:

* If no browser is open make Browserosaurus show me the browsers list.
* If i have Browser-A open, let's make any link to open automatically in Browser-A.
* If i have Browser-A and Browser-B open at the same time, show me the browser list.
* If i use a specifc shortcut (alt+click or user defined) when clicking on a link, override any rule and just show me the browser list.

This will reduce my interaction with Browserosaurus to the bare minimum, but it will be present on the critical moments where i really need it!

**Comment by will-stone** [comment]
Hi, thanks for the feature request. Good idea. However, I'm all for muscle-memory and predictably. Therefore this isn't something I'm going to consider right now. Thanks for using Browserosaurus.
