### ISSUE TITLE
[Feature Request] context menu support

### ISSUE THREAD

**Issue by nicgarner** [will-stone/browserosaurus#92]
Add Browserosaurus to browser context menus. For example, when I right click a hyperlink in Chrome, add "Open Link in Browserosaurus" to the menu, so that I can choose to open a link within a browser in another browser.

**Comment by will-stone** [comment]
Hi. This would require a Chrome plugin. Something like [this](https://chrome.google.com/webstore/detail/open-with/cogjlncmljjnjpbgppagklanlcbchlno?hl=en) would probably match what you need. Thanks for using Browserosaurus.
