### ISSUE TITLE
[Feature Request]: Add support for Microsoft Edge

### ISSUE THREAD

**Issue by filipmares** [will-stone/browserosaurus#93]
It would be great to be able to open links in Microsoft Edge (Preview) on OSX once it's released.

**Comment by will-stone** [comment]
I can't seem to find an official download link for this, they all say "[coming soon](https://www.microsoftedgeinsider.com/en-us/download)". I'll definitely add this when it's more widely available.

**Comment by filipmares** [comment]
Oh great. That'll be awesome.

**Comment by fullstack-to** [comment]
The Microsoft Edge (Preview) for macOS is now available.

**Comment by will-stone** [comment]
Microsoft Edge Dev is now in version > 5.5.0
