### ISSUE TITLE
Feature Request: Add Tor browser support

### ISSUE THREAD

**Issue by macgeekpro** [will-stone/browserosaurus#94]
Hi! Will love to see the tor browser supported.

**Comment by will-stone** [comment]
Hmmm, it should be: https://github.com/will-stone/browserosaurus/blob/master/src/config/activities.ts#L93 Maybe the app identifier has changed. I'll look into it when I get a moment.

**Comment by macgeekpro** [comment]
@will-stone i see. no wonder tor doesn't show up in the Favourite list. Noted w/ thanks

**Comment by will-stone** [comment]
Ah, they've definitely changed then id, then.

Would you like to raise a PR?

**Comment by macgeekpro** [comment]
Sure. Just did. Thanks.

**Comment by will-stone** [comment]
Closed with v5.4.0
