### ISSUE TITLE
macOS 10.14.5 requires app to be "notarized". Help requested.

### ISSUE THREAD

**Issue by will-stone** [will-stone/browserosaurus#96]
Apple have gone and stopped the app from working... again! This time round, it's the fact that all apps on macOS > 10.14.5 must be "notarized". Otherwise anyone downloading the app will get this when trying to open the dmg file:

<img width="418" alt="image" src="https://user-images.githubusercontent.com/654103/58004395-06adf100-7adb-11e9-9912-f1f0fc31fe47.png">

I do not know how to do this. From what I can tell, I need to either move to an unstable beta of Electron-Forge (the current framework this app uses) or move to Electron Builder. Even then, it's rather unclear how to notarize the app. I just need one tutorial or, ideally, an example repo 😩 Any help from fellow Electron devs would be greatly appreciated.

**Comment by a-coruble** [comment]
Hi, I'm pretty knew to MacOS and Electron apps, but by taking a quick look, I found this repo that seems to allow you to notarize your Electron app when packaging it. Only thing is you need to have an Apple Developer Id : https://github.com/electron-userland/electron-notarize

**Comment by will-stone** [comment]
Hi @a-coruble, this project uses [Electron Forge](https://electronforge.io/) which uses [Electron Packager](https://github.com/electron-userland/electron-packager) which uses electron-notarize. I've got an Apple Developer Account (now) which is what I have used to sign Browserosaurus (v5.x.x). However, I don't know how to get it to "notarize", which is now required by Apple. I have found one other project on GitHub that's using a similar set-up: https://github.com/lazerwalker/tracery-dot-app/blob/master/package.json#L35 I've tried that but I get an error. I'll contact the owner of that repo and see if they have any tips they can give me. Thanks for the investigation; we'll get there eventually.

**Comment by selfagency** [comment]
@will-stone check this out https://github.com/electron-userland/electron-notarize

**Comment by selfagency** [comment]
I don't know jack about Electron nor about notarizing apps, but I grabbed the repo and started poking around and one thing that stands out to me is this:

```
appleIdPassword: `@keychain:AC_PASSWORD`,
```

Instead of trying to pass in your Apple ID password from the Apple Keychain, what would happen if you passed it as an environment variable like you do your Apple ID itself?

**Comment by will-stone** [comment]
Hi @selfagency. v5.4.5 should be notarized and good to go. Please download from https://browserosaurus.com and let me know. It’s not usually recommended to store passwords in env vars (but it did cross my mind to do so, yes).

**Comment by will-stone** [comment]
Can somebody on this thread please uninstall B, reinstall from https://browserosaurus.com/, and report back if it allows them run Browserosaurus without the "malicious software" message?

**Comment by selfagency** [comment]
I reinstalled from Homebrew, got the prompt to approve an unauthorized developer, and after approving it ran just fine.

**Comment by will-stone** [comment]
That’s great. Back to how it was 😀 Okay, I’m gonna consider this closed. I intend to write up on the readme how to notarize for anyone else having the same issue. However, I’m in the process of upgrading to Electron Forge 6 which may have a better method to notarize (I’ve not tried it yet). Thanks everyone.
