### ISSUE TITLE
Fetch browser logos using npm?

### ISSUE THREAD

**Issue by alrra** [will-stone/browserosaurus#97]
The [browser logos](https://github.com/alrra/browser-logos) are available on [`npm`](https://www.npmjs.com/org/browser-logos). They are usually keep up to date and highly optimized (e.g. see the changelogs for [`Firefox`](https://github.com/alrra/browser-logos/blob/26f3d17cfbef76d4fbeb21141b97273e8f6f8416/src/firefox/CHANGELOG.md#readme), [`Chrome`](https://github.com/alrra/browser-logos/blob/26f3d17cfbef76d4fbeb21141b97273e8f6f8416/src/chrome/CHANGELOG.md#readme), etc.).

**Comment by will-stone** [comment]
Indeed. That's where I get them from. I don't really want this to be dynamic, as I'd rather B comes packaged with everything it needs to run without having to make calls to the internet; the logos do not change regularly enough for this to be an issue. However, if we find a way to scan for all browsers and there's no longer a whitelist, _then_ this could be handy.

**Comment by alrra** [comment]
@will-stone Thank you for your reply!

---

> I don't really want this to be dynamic, as I'd rather B comes packaged with everything it needs to run without having to make calls to the internet; 

I wasn't suggesting you fetch them dynamically. Have them as `devDependencies`, fetch them at build time, and copy them into your build product. Or, if you want to be even safer, have something such as a `npm` script that just updates the local (committed) images.

>  the logos do not change regularly enough for this to be an issue. 

They are constantly being optimized.

**Comment by will-stone** [comment]
Ah, I hadn't realised it was your repo 😆  Well, firstly, thanks for that project it has certainly made getting the logos together much easier. I will look into adding the logos as a devDep. Cheers.

**Comment by will-stone** [comment]
I'm in the process of upgrading the dev environment to use Electron Forge v6, this brings support for webpack and allows me to more easily import the browser logos using your npm package. I hope to have that finished soon, and I've already got the logo import working, so this will come with it.
